### ISSUE TITLE
Warning: Task "server" not found. Use --force to continue.

### ISSUE THREAD

**Issue by isAlmogK** [yeoman/yeoman#1023]
Just upgraded to the new Yeoman from Yeoman 0.9.x to upgrade to 1.0. 

When I create a new project everything is fine, but when I try to run grunt sever in my existing project I'm getting the following error "Warning: Task "server" not found. Use --force to continue." 

I did steps required at Migrate-from-0.9.6-to-1.0 - https://github.com/yeoman/yeoman/wiki/Migrate-from-0.9.6-to-1.0

Any ideas about this?

**Comment by ghostcodelover** [comment]
use this options "-g" when install with npm. this will be like $ npm install -g
