### ISSUE TITLE
console.log() in grunt test

### ISSUE THREAD

**Issue by kraftwer1** [yeoman/yeoman#1037]
I'd like to debug my unit test using `console.log()`. However, nothing shows up:

```
describe "Debugging", ->
    it "says hello", ->
        console.log "Hello world!"
```

Output:

```
Running "mocha:all" (mocha) task
Testing: http://localhost:9000/index.html

  ․

  1 test complete (106 ms)
```

Any idea?

**Comment by takotuesday** [comment]
Now that yeoman output is suppressed, is it possible to re-route the suppressed console.log for debug purposes?
