### ISSUE TITLE
Cannot find angular after generating angular app

### ISSUE THREAD

**Issue by Coder2012** [yeoman/yeoman#1046]
After following through the recent video - http://www.youtube.com/watch?v=iUQ1fvdO9GY by Addy which demonstrates setting up yo with grunt and bower, then creating an angular webapp I have several problems on Windows 7. 
1. It appears that grunt and bower do not automatically install with yo. I installed them separately.
2. Trying to run grunt server fails with - Warning: You need to have Ruby and Compass installed and in your system PATH for this task to work.
3. The next issue I get is that after generating an angular app and running on my local webserver instead of grunt, is an error locating the angular.js file. It is expected in components/angular/angular.js which is never created.

I did not try standard webapp only angular. I hope someone can help me to get past these small problems.

**Comment by mmamongy** [comment]
I'm using Linux, i have just run sudo bower install --allow-root then i've got the bower component in the app directory
