### ISSUE TITLE
How to define RequireJS waitSeconds config value for dist?

### ISSUE THREAD

**Issue by p3k** [yeoman/yeoman#1051]
I was not able to set RequireJS’ `waitSeconds` property to 0 or any other value so that it affects the timeout when loading the optimized module.

Our optimized file is ~7 megs (it’s a game demo and we are okay with this) but loading it as module causes a timeout error. It is directly loaded using require.js and the `data-main` attribute of the script element.

I worked around the issue simply by setting `waitSeconds` directly in the require.js file which then gets copied to the dist directory by usemin or uglify (that’s quite confusing, anyway IMHO.)

Maybe I am missing something but how else could I define `waitSeconds` in our scenario?

**Comment by Crotery** [comment]
does not work :( 
had to change default waitSeconds in require.js by hand
