### ISSUE TITLE
Angular generator error, can't find karma:app generator

### ISSUE THREAD

**Issue by sublimeye** [yeoman/yeoman#1073]
Using win7

Message:
"Error angular

You don't seem to have a generator with the name karma:app installed."

yo --help shows (among others)

Karma  
  karma:lib:generators:app

**Comment by Petya-Naumova** [comment]
@sindresorhus, helped me a lot thanks!

**Comment by wal0x** [comment]
not for me, but installing karma generator manually with <code>npm install -g generator-karma</code> did it :)

**Comment by Deovandski** [comment]
@wal0x method worked for me, but I had to sudo the command.

**Comment by wal0x** [comment]
@Deovandski , I was using Windows. Maybe run command line as an admin can solve the problem I don't remembre my self trying it.

**Comment by Anurag3487** [comment]
npm install -g generator-karma helped me too.
Thanks

**Comment by StackticMain** [comment]
I had the same issue - installing it manually with **sudo npm install -g generator-karma** worked for me. 

Thanks everyone!

**Comment by lacajanegra** [comment]
`sudo npm install -g generator-karma` worked for me too

**Comment by Abhivendra** [comment]
` sudo npm install -g generator-karma `

//this will do it for you

**Comment by Pretorian** [comment]
change where your packages are and don't use sudo, its better that way.
