### ISSUE TITLE
Yeoman ASCII art

### ISSUE THREAD

**Issue by addyosmani** [yeoman/yeoman#110]
Lets add some fun ASCII art into the mix. We've experimented with larger ones in #108, but want to see if I can come up with something that is small and looks like a Yeoman in just a few lines. Speech bubble would be a plus.

**Comment by cancerberoSgx** [comment]
Showing that drawing in the command line of the users, IMHO this is a horrible decision, it is flippant specially for those who want to use yo in the enterprise. Please don't show any ascii art  in the user's command line. I want to build my projects, I don't to watch to some ascii art, if I would want to watch to some art I would go to a museum or turn on the TV.

**Comment by SBoudrias** [comment]
@stephenplusplus Could we add this new art work to yosay?

**Comment by sindresorhus** [comment]
@SBoudrias That's the old one. This issue is ancient.

**Comment by SBoudrias** [comment]
It's a great piece of ascii art no matter what :stuck_out_tongue_closed_eyes: People love diversity!

**Comment by sindresorhus** [comment]
Open an issue/PR on yosay. I don't mind having an option for it.
