### ISSUE TITLE
Yeoman installed successfully, but yo: command not found.

### ISSUE THREAD

**Issue by jarrodmedrano** [yeoman/yeoman#1205]
I think this might be a bash profile problem but I don't know what to put in there to fix it?

npm http GET https://registry.npmjs.org/yo
npm http 304 https://registry.npmjs.org/yo
npm http GET https://registry.npmjs.org/yeoman-generator
npm http GET https://registry.npmjs.org/chalk
npm http GET https://registry.npmjs.org/sudo-block
npm http GET https://registry.npmjs.org/update-notifier
npm http GET https://registry.npmjs.org/open/0.0.4
npm http GET https://registry.npmjs.org/insight
npm http GET https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/update-notifier
npm http 304 https://registry.npmjs.org/chalk
npm http 304 https://registry.npmjs.org/sudo-block
npm http 304 https://registry.npmjs.org/open/0.0.4
npm http 304 https://registry.npmjs.org/yeoman-generator
npm http 304 https://registry.npmjs.org/nopt
npm http 304 https://registry.npmjs.org/insight
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/has-color
npm http GET https://registry.npmjs.org/ansi-styles
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/configstore
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/inquirer
npm http GET https://registry.npmjs.org/abbrev
npm http GET https://registry.npmjs.org/ansi-styles
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/cheerio
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/tar
npm http 304 https://registry.npmjs.org/has-color
npm http 304 https://registry.npmjs.org/ansi-styles
npm http GET https://registry.npmjs.org/diff
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/inquirer
npm http GET https://registry.npmjs.org/underscore.string
npm http 304 https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/findup-sync
npm http GET https://registry.npmjs.org/isbinaryfile
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/configstore
npm http 304 https://registry.npmjs.org/inquirer
npm http GET https://registry.npmjs.org/iconv-lite
npm http GET https://registry.npmjs.org/text-table
npm http GET https://registry.npmjs.org/shelljs
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/dargs
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/abbrev
npm http 304 https://registry.npmjs.org/ansi-styles
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/cheerio
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/tar
npm http 304 https://registry.npmjs.org/diff
npm http 304 https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/inquirer
npm http 304 https://registry.npmjs.org/underscore.string
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/isbinaryfile
npm http 304 https://registry.npmjs.org/findup-sync
npm http 304 https://registry.npmjs.org/iconv-lite
npm http 304 https://registry.npmjs.org/text-table
npm http 304 https://registry.npmjs.org/shelljs
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/dargs
npm http GET https://registry.npmjs.org/js-yaml
npm http GET https://registry.npmjs.org/osenv/0.0.3
npm http 304 https://registry.npmjs.org/js-yaml
npm http 304 https://registry.npmjs.org/osenv/0.0.3
npm http GET https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/fstream
npm http GET https://registry.npmjs.org/mute-stream/0.0.3
npm http GET https://registry.npmjs.org/cli-color
npm http GET https://registry.npmjs.org/block-stream
npm http GET https://registry.npmjs.org/entities
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/cheerio-select
npm http GET https://registry.npmjs.org/htmlparser2/3.1.4
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/cli-color
npm http 304 https://registry.npmjs.org/block-stream
npm http 304 https://registry.npmjs.org/entities
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/cheerio-select
npm http 304 https://registry.npmjs.org/htmlparser2/3.1.4
npm http 304 https://registry.npmjs.org/fstream
npm http 304 https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/http-signature
npm http GET https://registry.npmjs.org/hawk
npm http GET https://registry.npmjs.org/aws-sign
npm http GET https://registry.npmjs.org/tunnel-agent
npm http GET https://registry.npmjs.org/esprima
npm http GET https://registry.npmjs.org/oauth-sign
npm http GET https://registry.npmjs.org/argparse
npm http 304 https://registry.npmjs.org/mute-stream/0.0.3
npm http GET https://registry.npmjs.org/cookie-jar
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/qs
npm http GET https://registry.npmjs.org/form-data/0.0.8
npm http GET https://registry.npmjs.org/forever-agent
npm http GET https://registry.npmjs.org/json-stringify-safe
npm http 304 https://registry.npmjs.org/esprima
npm http 304 https://registry.npmjs.org/oauth-sign
npm http 304 https://registry.npmjs.org/argparse
npm http 304 https://registry.npmjs.org/cookie-jar
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/tunnel-agent
npm http 304 https://registry.npmjs.org/http-signature
npm http 304 https://registry.npmjs.org/hawk
npm http 304 https://registry.npmjs.org/aws-sign
npm http 304 https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/form-data/0.0.8
npm http 304 https://registry.npmjs.org/forever-agent
npm http 304 https://registry.npmjs.org/json-stringify-safe
npm http GET https://registry.npmjs.org/form-data
npm http 304 https://registry.npmjs.org/form-data
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/CSSselect
npm http GET https://registry.npmjs.org/sigmund
npm http GET https://registry.npmjs.org/combined-stream
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/CSSselect
npm http GET https://registry.npmjs.org/ctype/0.5.2
npm http 304 https://registry.npmjs.org/sigmund
npm http GET https://registry.npmjs.org/asn1/0.1.11
npm http GET https://registry.npmjs.org/assert-plus/0.1.2
npm http GET https://registry.npmjs.org/memoizee
npm http GET https://registry.npmjs.org/es5-ext
npm http 304 https://registry.npmjs.org/combined-stream
npm http 304 https://registry.npmjs.org/es5-ext
npm http 304 https://registry.npmjs.org/asn1/0.1.11
npm http 304 https://registry.npmjs.org/assert-plus/0.1.2
npm http 304 https://registry.npmjs.org/memoizee
npm http 304 https://registry.npmjs.org/ctype/0.5.2
npm http GET https://registry.npmjs.org/CSSwhat
npm http GET https://registry.npmjs.org/domutils
npm http 304 https://registry.npmjs.org/CSSwhat
npm http 304 https://registry.npmjs.org/domutils
npm http GET https://registry.npmjs.org/domhandler
npm http GET https://registry.npmjs.org/domelementtype
npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/delayed-stream/0.0.5
npm http GET https://registry.npmjs.org/hoek
npm http GET https://registry.npmjs.org/boom
npm http GET https://registry.npmjs.org/sntp
npm http GET https://registry.npmjs.org/cryptiles
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/domelementtype
npm http 304 https://registry.npmjs.org/boom
npm http 304 https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/cryptiles
npm http 304 https://registry.npmjs.org/delayed-stream/0.0.5
npm http GET https://registry.npmjs.org/hoek
npm http 304 https://registry.npmjs.org/domhandler
npm http 304 https://registry.npmjs.org/hoek
npm http GET https://registry.npmjs.org/event-emitter
npm http GET https://registry.npmjs.org/next-tick
npm http 304 https://registry.npmjs.org/hoek
npm http 304 https://registry.npmjs.org/event-emitter
npm http 304 https://registry.npmjs.org/next-tick
/Users/jarrodmedrano/.node/bin/yo -> /Users/jarrodmedrano/.node/lib/node_modules/yo/bin/yo
yo@1.0.4 /Users/jarrodmedrano/.node/lib/node_modules/yo
├── open@0.0.4
├── async@0.2.9
├── chalk@0.2.1 (has-color@0.1.1, ansi-styles@0.2.0)
├── nopt@2.1.2 (abbrev@1.0.4)
├── sudo-block@0.2.1 (chalk@0.1.1)
├── lodash@1.3.1
├── update-notifier@0.1.6 (chalk@0.1.1, semver@2.0.11, configstore@0.1.5, request@2.22.0)
├── insight@0.2.0 (inquirer@0.2.5, request@2.27.0, configstore@0.1.5)
└── yeoman-generator@0.13.4 (dargs@0.1.0, diff@1.0.7, debug@0.7.2, text-table@0.1.1, mime@1.2.11, mkdirp@0.3.5, isbinaryfile@0.1.9, rimraf@2.2.2, shelljs@0.1.4, glob@3.2.6, tar@0.1.18, underscore.string@2.3.3, findup-sync@0.1.2, iconv-lite@0.2.11, cheerio@0.12.3, request@2.25.0, inquirer@0.3.4)
jarrodsmac-2:/ jarrodmedrano$ yo
-bash: yo: command not found
jarrodsmac-2:/ jarrodmedrano$ yo
-bash: yo: command not found
jarrodsmac-2:/ jarrodmedrano$ yo webapp
-bash: yo: command not found
jarrodsmac-2:/ jarrodmedrano$ npm install -g generator-webapp
npm http GET https://registry.npmjs.org/generator-webapp
npm http 200 https://registry.npmjs.org/generator-webapp
npm http GET https://registry.npmjs.org/generator-webapp/-/generator-webapp-0.4.3.tgz
npm http 200 https://registry.npmjs.org/generator-webapp/-/generator-webapp-0.4.3.tgz
npm http GET https://registry.npmjs.org/yeoman-generator
npm http GET https://registry.npmjs.org/cheerio
npm http 304 https://registry.npmjs.org/cheerio
npm http 304 https://registry.npmjs.org/yeoman-generator
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/cheerio-select
npm http GET https://registry.npmjs.org/htmlparser2/3.1.4
npm http GET https://registry.npmjs.org/entities
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/underscore.string
npm http GET https://registry.npmjs.org/diff
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/tar
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/isbinaryfile
npm http GET https://registry.npmjs.org/iconv-lite
npm http GET https://registry.npmjs.org/dargs
npm http GET https://registry.npmjs.org/inquirer
npm http GET https://registry.npmjs.org/chalk
npm http GET https://registry.npmjs.org/findup-sync
npm http GET https://registry.npmjs.org/text-table
npm http GET https://registry.npmjs.org/shelljs
npm http GET https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/entities
npm http 304 https://registry.npmjs.org/cheerio-select
npm http 304 https://registry.npmjs.org/htmlparser2/3.1.4
npm http 304 https://registry.npmjs.org/underscore.string
npm http 304 https://registry.npmjs.org/diff
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/tar
npm http 304 https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/CSSselect
npm http 304 https://registry.npmjs.org/isbinaryfile
npm http 304 https://registry.npmjs.org/iconv-lite
npm http 304 https://registry.npmjs.org/inquirer
npm http 304 https://registry.npmjs.org/dargs
npm http 304 https://registry.npmjs.org/chalk
npm http 304 https://registry.npmjs.org/findup-sync
npm http 304 https://registry.npmjs.org/text-table
npm http 304 https://registry.npmjs.org/shelljs
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/CSSselect
npm http GET https://registry.npmjs.org/domhandler
npm http GET https://registry.npmjs.org/domutils
npm http GET https://registry.npmjs.org/domelementtype
npm http 304 https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/has-color
npm http GET https://registry.npmjs.org/ansi-styles
npm http GET https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/domelementtype
npm http 304 https://registry.npmjs.org/domutils
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/domhandler
npm http 304 https://registry.npmjs.org/ansi-styles
npm http 304 https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/CSSwhat
npm http 304 https://registry.npmjs.org/has-color
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/CSSwhat
npm http GET https://registry.npmjs.org/block-stream
npm http GET https://registry.npmjs.org/fstream
npm http GET https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/cli-color
npm http GET https://registry.npmjs.org/mute-stream/0.0.3
npm http GET https://registry.npmjs.org/qs
npm http GET https://registry.npmjs.org/json-stringify-safe
npm http GET https://registry.npmjs.org/tunnel-agent
npm http GET https://registry.npmjs.org/forever-agent
npm http GET https://registry.npmjs.org/http-signature
npm http GET https://registry.npmjs.org/hawk
npm http GET https://registry.npmjs.org/aws-sign
npm http GET https://registry.npmjs.org/oauth-sign
npm http GET https://registry.npmjs.org/cookie-jar
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/form-data
npm http 304 https://registry.npmjs.org/block-stream
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/fstream
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/json-stringify-safe
npm http 304 https://registry.npmjs.org/tunnel-agent
npm http 304 https://registry.npmjs.org/forever-agent
npm http 304 https://registry.npmjs.org/http-signature
npm http 304 https://registry.npmjs.org/aws-sign
npm http 304 https://registry.npmjs.org/hawk
npm http 304 https://registry.npmjs.org/oauth-sign
npm http 304 https://registry.npmjs.org/cookie-jar
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/form-data
npm http 304 https://registry.npmjs.org/sigmund
npm http GET https://registry.npmjs.org/combined-stream
npm http GET https://registry.npmjs.org/assert-plus/0.1.2
npm http GET https://registry.npmjs.org/asn1/0.1.11
npm http GET https://registry.npmjs.org/ctype/0.5.2
npm http GET https://registry.npmjs.org/hoek
npm http GET https://registry.npmjs.org/boom
npm http GET https://registry.npmjs.org/cryptiles
npm http GET https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/assert-plus/0.1.2
npm http 304 https://registry.npmjs.org/asn1/0.1.11
npm http 304 https://registry.npmjs.org/ctype/0.5.2
npm http 304 https://registry.npmjs.org/hoek
npm http 304 https://registry.npmjs.org/boom
npm http 304 https://registry.npmjs.org/cryptiles
npm http 304 https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/combined-stream
npm http 304 https://registry.npmjs.org/mute-stream/0.0.3
npm http 304 https://registry.npmjs.org/cli-color
npm http GET https://registry.npmjs.org/delayed-stream/0.0.5
npm http GET https://registry.npmjs.org/es5-ext
npm http GET https://registry.npmjs.org/memoizee
npm http 304 https://registry.npmjs.org/memoizee
npm http 304 https://registry.npmjs.org/es5-ext
npm http GET https://registry.npmjs.org/event-emitter
npm http GET https://registry.npmjs.org/next-tick
npm http 304 https://registry.npmjs.org/delayed-stream/0.0.5
npm http 304 https://registry.npmjs.org/event-emitter
npm http 304 https://registry.npmjs.org/next-tick
generator-webapp@0.4.3 /Users/jarrodmedrano/.node/lib/node_modules/generator-webapp
├── cheerio@0.12.3 (entities@0.3.0, underscore@1.4.4, cheerio-select@0.0.3, htmlparser2@3.1.4)
└── yeoman-generator@0.13.4 (dargs@0.1.0, diff@1.0.7, debug@0.7.2, text-table@0.1.1, mime@1.2.11, async@0.2.9, mkdirp@0.3.5, isbinaryfile@0.1.9, rimraf@2.2.2, chalk@0.2.1, shelljs@0.1.4, underscore.string@2.3.3, iconv-lite@0.2.11, tar@0.1.18, glob@3.2.6, lodash@1.3.1, findup-sync@0.1.2, request@2.25.0, inquirer@0.3.4)
jarrodsmac-2:/ jarrodmedrano$ yo webapp
-bash: yo: command not found

**Comment by daveferrara1** [comment]
These are my .bash_profile path exports that work for me:

After Homebrew - I added

export PATH="/usr/local/bin:/usr/local/sbin:~/bin:$PATH" 
export PATH="/usr/local/Cellar/node/0.10.36/libexec/npm/lib/node_modules:$PATH"
export PATH="/usr/local/Cellar/node/0.10.36/libexec/npm/bin:$PATH"

The first cleared brew doctor error I had about usr/local infront
The second is where node modules live
The third npm bin path (thanks to @SBoudrias  on 10/15/2013)

**Comment by ReemAlattas** [comment]
I tried adding every PATH but it is still not working!!! Any other idea... Please help
