### ISSUE TITLE
'bower' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by vah7id** [yeoman/yeoman#1224]
When I enter yo webapp command after process I get this error:

I'm all done. Running bower install & npm install for you to install the require
d dependencies. If this fails, try running the command yourself.

'bower' is not recognized as an internal or external command,
operable program or batch file.

Compelete log: http://notepad.cc/share/ywZzwAsrO4

**Comment by basherr** [comment]
Either of them are not working for me..

**Comment by KoalaBear84** [comment]
Had the same problem. Solved it by running this:
npm install -g bower

And if that does not work, node.js needs to be also installed I guess.

**Comment by karthigamahe** [comment]
I tried to install bower through npm it install perfectlly 
 _>**npm install -g bower
C:\Program Files\Git\usr\local\bower -> C:\Program Files\Git\usr\local\node_modules\bower\bin\bower
bower@1.7.9 C:\Program Files\Git\usr\local\node_modules\bower**

Then i tried to  check their version it says
 bower --version
bash: bower: command not found


Can anyone help me

**Comment by SBoudrias** [comment]
@karthigamahe you need to add the node_module cli folder to your OS PATH variable. http://notions.me/post/adding-npm-bin-to-path
