### ISSUE TITLE
Assetgraph (grunt-reduce) for production minification

### ISSUE THREAD

**Issue by Munter** [yeoman/yeoman#1234]
I was asked to give a brief overview of what Assetgraph is, and how it can fit into the Yeoman project and the whole Grunt setup, at the irc meeting yesterday. So here goes.

[Assetgraph](https://github.com/One-com/assetgraph) is a project that aims to model web assets and their relations to each other in a graph.

The original intention behind this was to create a web asset build system that could automate web performance optimization. This project is [Assetgraph-builder](https://github.com/One-com/assetgraph-builder) and has a grunt wrapper called [grunt-reduce](https://github.com/Munter/grunt-reduce).

How it works
------------
You seed the graph with an initial asset, typically your index.html or a collection of several html.files. The you run the `populate` transform on assetgraph, which will start an automated population of the graph by parsing each initial asset in the graph, finding all outgoing relations and populating these recursively. We aim to implement any type of relation that is well specified and supported in any way. The list is [quite extensive](https://github.com/One-com/assetgraph/tree/master/lib/relations) by now.

So now you have a populated graph that includes all the assets that are depended on by your initial seed asset (index.html). All of this with a minimal configuration of just that one root file reference.

To work with this graph we've implemented a [query model](https://github.com/One-com/assetgraph/blob/master/lib/query.js) that has a lot of similarities with the MongoDB query model. The essence of it is that you can find assets or relations based on a simple query object where properties can be matched recursively with arrays, strings, booleans, regular expressions or functions with some boolean and/or/not wrappers. This gives you fine grained control of what assets or relations you want to work on and iterate over them.

The third leg of assetgraph are the [transforms](https://github.com/One-com/assetgraph/tree/master/lib/transforms), which are high-level convenience functions that can rework the graph for you in predefined ways. Each of these take an assetgraph as first argument and a continuation callback at second argument, thus allowing for extensibility and chaining of multiple transforms on the same graph instance.

What does it mean?
------------------
There are some major differences from the way file based systems like grunt work to how assetgraph works.

First of all every input file is only read once and the graph is kept in memory through all the transforms, then written to disk on demand. So file IO is drastically reduced compared to a long chain of grunt minification tasks. This has some potential speed implications, hopefully improvements :)

Configuration is drastically reduced. Since the individual graph transformations are chained operations on the already instantiated and populated graph you don't need ell the repetition that a grunt minification task pipeline has. You only configure where your assets are once, and then you still only need to configure your initial assets, which can be [quite simple](https://github.com/Munter/grunt-reduce/blob/master/tasks/grunt-reduce.js#L29-L32).

Only referenced files are included. This means that you won't be including unused libraries just because they happen to be located in a directory you globbed for bundling or similar. Combining this with a dependency based approach, for example with RequireJS, you can completely skip any need for manifest files and move over to trust that the libs you need will be there by automation and no libs you don't need will be included. The caveat here is that is a certain asset relation syntax isn't supported by assetgraph, the asset will not be in the graph and consequently not be written to the desired output directory.

References are automatically updated. If you rename a file in the graph, replace a file reference with a bundle reference or similar, any reference wil be automatically updated. This means that previously hard problems like reving files becomes [somewhat simpler](https://github.com/One-com/assetgraph-builder/blob/master/lib/transforms/buildProduction.js#L141-L163) than when trying to solve the problem without an implicit knowledge of the whole dependency graph. (This should address issues like these https://github.com/yeoman/yeoman/issues/1228)

How can this be implemented?
----------------------------
Luckily I already put in some time to create a grunt wrapper for assetgraph-builder, called [grunt-reduce](https://github.com/Munter/grunt-reduce). This in itself is pretty much a plug in replacement for the whole grunt minification chain that most generators currently set up.

One implication of switching to grunt-reduce is that the workflow might be a bit different from what some people are doing with grunt at the moment. Most importantly assetgraph is supposed to understand anything a browser understands. So it doesn't care for most preprocessing like sass, typescript, coffeescript etc. These preprocessing steps should still be run in grunt, probably with a watcher task to get updates to the browser quickly.

Running grunt-reduce should be manually triggered, not a part of some watcher chain. Production building is a slow process, no matter how much we optimize it. Also I would consider it absolutely best practice to have a working development version running in your `app`-folder with the least amount of abstractions. This should improve the debugging workflow.

Caveats
-------
Sadly this is not all as easy as waving a magic wand. While assetgraph does away with most of the ugliness of the corresponding grunt minification chain, there are also some clutches that need to be known.

One particular problem is that sometimes developers might be using javascript strings as file references. Lets take an example of an app that loads a static json file run time to load in some configuration. The developer does this with a manually run XHR-call. The file reference would now be something like `path/to/file.json`. There is no way assetgraph can interpret any and all strings as file references. So to properly refer to this file the developer will have to do this: `GETSTATICURL('path/to/file.json')`. `GETSTATICURL` is a function that simply returns the first argument at run time, but at build time gets picked up as a file relation and replaced by a raw string with the updated file path on build.

RequireJS plugins. Currently assetgraph understands only some of them: `text`, `json`, `css`, `less`. It also picks up files ending with `.ko` as knockout template references. These are mostly hacks. Assetgraph doesn't evaluate the plugin code itself, and the random naming convention that developers can use for plugins provide insufficient semantics to handle any type of plugin the same way r.js would. We're planning to mitigate this by actually evaluating the build time part of the plugin code in the same way r.js would or simply run r.js on the limited subset of plugins to enable support for any plugin. This is a work in progress.

Next step
---------
My current plan is to make an example implementation of grunt-reduce on a fork of generator-webapp so you can all try this out in action.

I haven't been telling you half of the cool stuff that we can do with this, as I am hoping you will check the readmes of the referenced projects if you are interested. Safe to say I have high hopes for the dependency based approach to build systems.

Please ask any and all questions. I will be very happy to answer to the best of my knowledge.

Ping @papandreou (the brain behind assetgraph)

**Comment by sindresorhus** [comment]
Closing this as there haven't been much activity on this topic lately.

**Comment by Munter** [comment]
Yeah. If anyone in the future is interested in generators with assetgraph as a build tool, take a look at either https://github.com/Munter/generator-greenfield (grunt tasks) or https://github.com/Munter/generator-npm-webapp (npm tasks)
