### ISSUE TITLE
2014 Official Generators Cleanup

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/yeoman#1263]
Building the list of things official generators should've done to be up to date with everything.
- [x] Grunt `server` to become `serve` (#1183)
- [ ] Generators should generate a `.yo-rc` file (even if it doesn't use it for configs at the moment)
- [ ] Use the new `.extend()` method instead of `util.inherit`
- [ ] Remove use of deprecated test methods (deprecation are currently logged to console)
- [ ] update dependencies in the generated bower.json and package.json
- [ ] sync improvements from webapp generator over to the other generators.
- [ ] Make sure `peerDependencies` **do not** use tilde `~` versions. Only use `>=`.

Once the list is complete, we should be good to ping maintainers :)

**Comment by addyosmani** [comment]
@SBoudrias With the clean-up blog post posted 2 years ago and a lot of the ecosystem having moved on, can we close this issue?
