### ISSUE TITLE
Installing on Windows hangs at postinstall yeoman-generator

### ISSUE THREAD

**Issue by raff77** [yeoman/yeoman#1288]
I am trying to Install on Windows with NPM and it hangs on

npm info postinstall yeoman-generator@0.16.0

The End of Full --verbose output:

npm info postinstall decompress@0.1.6
npm verb about to build d:\NodeJs\node_modules\yo\node_modules\yeoman-generator\node_modules\download
npm info build d:\NodeJs\node_modules\yo\node_modules\yeoman-generator\node_modules\download
npm verb linkStuff [ true,
npm verb linkStuff   'd:\NodeJs\node_modules',
npm verb linkStuff   false,
npm verb linkStuff   'd:\NodeJs\node_modules\yo\node_modules\yeoman-generator\node_modules' ]
npm info linkStuff download@0.1.10
npm verb linkBins download@0.1.10
npm verb linkMans download@0.1.10
npm verb rebuildBundles download@0.1.10
npm verb rebuildBundles [ 'decompress', 'each-async', 'request', 'through2' ]
npm info install download@0.1.10
npm info postinstall download@0.1.10
npm verb about to build d:\NodeJs\node_modules\yo\node_modules\yeoman-generator
npm info build d:\NodeJs\node_modules\yo\node_modules\yeoman-generator
npm verb linkStuff [ true,
npm verb linkStuff   'd:\NodeJs\node_modules',
npm verb linkStuff   false,
npm verb linkStuff   'd:\NodeJs\node_modules\yo\node_modules' ]
npm info linkStuff yeoman-generator@0.16.0
npm verb linkBins yeoman-generator@0.16.0
npm verb linkMans yeoman-generator@0.16.0
npm verb rebuildBundles yeoman-generator@0.16.0
npm verb rebuildBundles [ '.bin',
npm verb rebuildBundles   'cheerio',
npm verb rebuildBundles   'class-extend',
npm verb rebuildBundles   'dargs',
npm verb rebuildBundles   'debug',
npm verb rebuildBundles   'diff',
npm verb rebuildBundles   'download',
npm verb rebuildBundles   'file-utils',
npm verb rebuildBundles   'findup-sync',
npm verb rebuildBundles   'glob',
npm verb rebuildBundles   'iconv-lite',
npm verb rebuildBundles   'inquirer',
npm verb rebuildBundles   'isbinaryfile',
npm verb rebuildBundles   'mime',
npm verb rebuildBundles   'mkdirp',
npm verb rebuildBundles   'request',
npm verb rebuildBundles   'rimraf',
npm verb rebuildBundles   'text-table',
npm verb rebuildBundles   'underscore.string' ]
npm info install yeoman-generator@0.16.0
npm info postinstall yeoman-generator@0.16.0

Any idea's? Have reinstalled node and cleared out all cache. I am behind a works firewall but have Node using the proxy. I am running as Admin.

**Comment by Siafu** [comment]
@raff77  Where does one make this change ?

**Comment by robsdudeson** [comment]
@Siafu you have to use following command syntax 'npm config set <key> <value>'.  For example, 'npm config set proxy http://:/' would set the proxy value as showing in @raff77's example
