### ISSUE TITLE
Yo can't find installed generators - no errors given

### ISSUE THREAD

**Issue by tomphp** [yeoman/yeoman#1302]
Hi,

I've put a fresh install of node on Ubuntu 10.10, I've run `npm install -g yo`, it installed perfectly. I've then installed the `angular-generator`, again it installed perfectly with no errors. However now when I type `yo angular` I get the following message.

`Error angular 

You don't seem to have a generator with the name angular installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 0 registered generators run yo with the `--help` option.`

System details below.

Thanks!!!!!!!

`1.1.2
./vendor/bin:/home/tom/bin:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/tom/.local/bin:/home/tom/.npm/bin /usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript
linux { http_parser: '1.0',
  node: '0.10.26',
  v8: '3.14.5.9',
  ares: '1.9.0-DEV',
  uv: '0.10.25',
  zlib: '1.2.3',
  modules: '11',
  openssl: '1.0.1e' }`

**Comment by spiralni** [comment]
yo doctor what a trick!! you saved my life

**Comment by SaurabhBayani** [comment]
SBoudrias, Thanks a lot, U saved my day. I was trying angular-generator :+1:

**Comment by alokadhao20** [comment]
I had same issue "You don't seem to have a generator with the name angular installed."
it got resolved just by typing sodo before yo angular.

**Comment by SBoudrias** [comment]
@alokadhao20 run `yo doctor`

Your issue is that your permissions are messed up. You should NEVER run a program with `sudo`.

**Comment by asimkt** [comment]
`yo doctor` shows the exact error and solution. Thanks. I was messing up the `NODE_PATH` variable.

**Comment by bretonio** [comment]
`yo doctor` gives me a clean bill of health but still I cannot run `hexo-theme` after installing it the usual way ... Oddly this works fine on Linux Mint but not at all on Arch. To do with the Node path perhaps? 'which node`? `/usr/bin/node` ...

**Comment by SBoudrias** [comment]
@bretonio run `DEBUG=yeoman:* yo hexo-theme` and see if that helps you debug your issue.

**Comment by dkinfotech** [comment]
Thank you so much for showing the answer in for ' yo doctor' which made me figure out the problem. This problem wasted my whole day to install yeoman for local dir. No other resource was helpful :) 

Thanks

**Comment by acejordans** [comment]
Setting NODE_PATH did the trick! Thanks
