### ISSUE TITLE
Does yo have a silent mode?

### ISSUE THREAD

**Issue by nichdiekuh** [yeoman/yeoman#1415]
Hi,

I want to use travis-ci to make a few test builds of my generator, but yo keeps asking me question on the command line after install:

```
[?] ==========================================================================
We're constantly looking for ways to make yo better! 
May we anonymously report usage statistics to improve the tool over time? 
More info: https://github.com/yeoman/insight & http://yeoman.io
==========================================================================: (Y/n) 
```

Can I somehow skip this question? It's blocking my build

**Comment by maersu** [comment]
@nichdiekuh its maybe a little late, but on most unix systems you can use `yes`

```
yes | yo my-generator
```

**Comment by msavitskiy** [comment]
```yo --no-insight my-generator``` works for me
