### ISSUE TITLE
Simple generic generator / scaffolder

### ISSUE THREAD

**Issue by Martinspire** [yeoman/yeoman#1430]
I propose the idea of building a default generator which is able to generate files how you see fit. This then has a config and some templates users can adjust for generating parts of their project however they see fit.

So this won't scaffold the base of your app, but you build your own base and then allows to scaffold other parts to extend it. More things for your backend, more things for your frontend. Not only logic, but also styles and views.

So say you have the default Angular Seed project installed and made some changes, you include this generator to your project which creates a new folder called templates with inside your template files and a configuration file. In the config you input:
1) the command to use
2) the files you want to generate
3) with what folder structure you want to generate them
4) and what data to ask or insert by default

And in those files you have a certain syntax to include that data. And then just run your generator. This way you keep configuring to a minimum and customization to a maximum.

Now what would be the reason to do this? Well for the company i work for we started using a framework of our own where we have implemented various functionality which we use or don't use for a certain project. We also have certain pre-made styles and notation, some standard images, some default functions and some basic logic we use. We could make a generator but that would take too much customization and won't be very well suited for making it as generic as we have now. Because now we remove things we don't need, and work on top of the things we already have. The one thing missing is easily scaffold parts of our projects (but use some template files we need to keep changing and include manually).

And perhaps provide the ability to share various configs.

Yeoman seems like a nice way to scaffold but is hard to fit in a pre-existing custom framework or combination of tech.

**Comment by eddiemonge** [comment]
The great thing about Yeoman is that you can make such a generator on your own. It allows you to generate pretty much anything you want with whatever existing structure you have. Thats why there are over 1400 community generators (and thats only the published to npm ones we know of).
