### ISSUE TITLE
Invite @kevva to the Yeoman core team

### ISSUE THREAD

**Issue by addyosmani** [yeoman/yeoman#1434]
I can't believe we haven't done this [sooner](http://i.imgur.com/3RDUxOe.png). Kevin has been a very active contributor to the project since we got started and has done fantastic work taking part in design discussions, helping us improve our generators and responding to community support issues. 

We look forward to working with him to further improve Yeoman and would like to officially invite @kevva to the Yeoman core team.

Could we see some :+1:'s or :-1: 's from the rest of the core team in support of this? :) 

![kevva](https://cloud.githubusercontent.com/assets/110953/4871604/e815c9d6-61bf-11e4-90bd-3e25e004e64e.jpg)

**Comment by arthurvr** [comment]
ping @kevva
