### ISSUE TITLE
Partials system inside a template ?

### ISSUE THREAD

**Issue by tomapp** [yeoman/yeoman#1436]
Hello!

I would like know if there is a solution to "include" and compile partials directly inside a template?

For example :

foo.tpl

```
<h1><%= title %></h1>
```

index.html

```
<div>
     <%= _.awesomeFunction( './foo.tpl', {title: data} );  %>
</div>
```

Thank's to you!

**Comment by eddiemonge** [comment]
I feel like this should be closed
