### ISSUE TITLE
Namespace resolving incorrectly from Environment.prototype.namespace

### ISSUE THREAD

**Issue by adenhertog** [yeoman/yeoman#1461]
Hi,

I've been working with yeoman-environment over the past couple of days as I'm wanting it scaffold out various bits from a Nodejs back end. Yeoman's been great so far.

However I'm having an issue when it's trying to resolve a namespace from a path. 

The following path will resolve the namespace incorrectly (in environment.js:Environment.prototype.namespace)

```
c:\projects\yeoman\generators\generator-example\generators\app\index.js 
EXPECTED: example:app
ACTUAL: example:generators:app
```

Lookups:
```javascript
['.', 'generators', 'lib/generators']
```

This happens because the first "generators" in the path is being replaced. I believe this should replace the last matched lookup in the reduce function like:

```javascript
  // if `ns` contain a lookup dir in it's path, remove it.
  ns = lookups.reduce(function (ns, lookup) {
	// ensure that the lookup is removed from the lowest level folder, and that partial folder names aren't removed
  	var folders = ns.split(path.sep);
  	var replaceIndex = folders.lastIndexOf(lookup);
  	if (replaceIndex > -1) {
  		folders.splice(replaceIndex, 1);
  	}
  	var resolvedPath = folders.join(path.sep);
  	return resolvedPath;
  }, ns);
```

This will also avoid it doing replaces like:
...\generator-example\generators-foo\app\index.js
...\generator-example\-foo\app\index.js

**Comment by SBoudrias** [comment]
Can you open this issue on the environment repo?
