### ISSUE TITLE
something wrong

### ISSUE THREAD

**Issue by humingx** [yeoman/yeoman#1465]
![screenshot from 2015-01-14 22 34 19](https://cloud.githubusercontent.com/assets/7880018/5740420/3b231b70-9c3e-11e4-8bbd-1472df858acb.png)

**Comment by Munter** [comment]
A good bug report has a title that gives you a good idea of what the content is about. Good content describes the scenario in clear text. Just to give you a heads up on how to speed up feedback

**Comment by humingx** [comment]
thanks

**Comment by arthurvr** [comment]
mostly this is regarding permission settings on the node and npm files. You might be interested in reading https://github.com/npm/npm/issues/4815.

**Comment by sindresorhus** [comment]
If only the error message said exactly what to do if you need help.
