### ISSUE TITLE
Model first generator?

### ISSUE THREAD

**Issue by SkydiverFL** [yeoman/yeoman#1466]
Does a model-first generator exist?  Something that feeds from an existing database or model diagram to scaffold a CRUD-based app and/or web service?  I've been looking but haven't found anything.  I'm coming from the Microsoft world and started to build my own [(available here if interested)](https://github.com/FredLackey/Templates-CodeSmith), however it uses a commercial Windows-only generator.  I'd like to be more platform agnostic but I'd also like to use some type of collaborative design tool to visualize and plan the various models.

**Comment by eddiemonge** [comment]
you could make one but otherwise, this wouldnt work as it would have to be very language/platform/framework agnostic.
