### ISSUE TITLE
Unicode block being added to file

### ISSUE THREAD

**Issue by Fynkymynky** [yeoman/yeoman#1467]
I'm not too sure where this issue is coming from, I'm using yeoman to build an angularjs app, but when I edit files in sublimetext2 on OSX and Ubuntu and with gedit the application doesn't work. Looking at the file something keeps adding this
```
��������������������������������������������������������������������������������������������������������������
```
To the end of the file. I don't have this issue when writing PHP or manually writing JavaScript. Also this is happening on two different machines and editors, but I don't know what is causing this issue. Has anyone else ever come across this?

If I open the file with vim and w+q and refresh the page everything works.

**Comment by sindresorhus** [comment]
Please open this on the generator you used.
