### ISSUE TITLE
yeoman is installed but can not run

### ISSUE THREAD

**Issue by angryillusionist** [yeoman/yeoman#1470]
install node and then install generator-webapp -g
create dir. in dir I command yo. but it is not worked. error show:
"yo : The term 'yo' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ yo webapp
+ ~~
    + CategoryInfo          : ObjectNotFound: (yo:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException"

**Comment by kevva** [comment]
You need to install `yo` too:

```sh
$ npm install -g yo`
```

**Comment by angryillusionist** [comment]
Same problem .. Let me told my whole process
install node
npm install -g yo grunt bower
npm install -g generator-webapp
then create a dir and into dir I command yo webapp error show:
"yo : The term 'yo' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1

    yo webapp
    ~~
        CategoryInfo : ObjectNotFound: (yo:String) [], CommandNotFoundException
        FullyQualifiedErrorId : CommandNotFoundException"

**Comment by Munter** [comment]
Sounds like you haven't set up your $PATH to include the globally npm install binaries

**Comment by angryillusionist** [comment]
In my win command line write npm install -g binary
same error is show when I command yo in my code directory.
Could you please tell me how can I set my my $path...

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/guides/blob/master/set-environment-variables.md#windows

**Comment by hfishere** [comment]
Re-installing nodejs (including npm) was solved my problem.

**Comment by kaisukidev** [comment]
> Re-installing nodejs (including npm) was solved my problem.

This works for me, Re-install Nodejs > Grunt > Ruby > Compass
