### ISSUE TITLE
Error during yeoman instalation

### ISSUE THREAD

**Issue by spatil2014** [yeoman/yeoman#1471]
Hi All,

Could you please assist to install yo . During installation I got below error.

npm ERR! yo@1.3.3 postinstall: `yodoctor`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the yo@1.3.3 postinstall script.
npm ERR! This is most likely a problem with the yo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     yodoctor
npm ERR! You can get their info via:
npm ERR!     npm owner ls yo
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\nodejs\\\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\
pm-cli.js" "install" "-g" "yo"
npm ERR! cwd C:\Users\Nag
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! syscall spawn
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! not ok code 0

However I tried "npm cache clean " but no luck !!

**Comment by sindresorhus** [comment]
Upgrade npm.
