### ISSUE TITLE
npm install -g yeoman - fetch failed

### ISSUE THREAD

**Issue by tiagofreres** [yeoman/yeoman#1474]
Hello guys!

I'm having problem to install yeoman, keeps throwing me the following message:

```
npm ERR! fetch failed http://github.com/yeoman/generators/archive/0.9.5.tar.gz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 406
```

Looks like that the dependency `"yeoman-generators":"http://github.com/yeoman/generators/archive/0.9.5.tar.gz"` could not be found (the file is not in that URL).

**Comment by kevva** [comment]
It's `npm install --global yo` nowadays bro.

**Comment by marcusmolchany** [comment]
Should this be changed in the docs? The site you linked says `npm install -g yo`.

**Comment by zckrs** [comment]
npm install --global yo === npm install -g yo === npm i -g yo

**Comment by phantomaxe** [comment]
Should this be changed in the docs? The site you linked says npm install -g yo.
