### ISSUE TITLE
Unable to use `fs.copy` function

### ISSUE THREAD

**Issue by Jberryliu** [yeoman/yeoman#1475]
Unable to use `fs.copy`(`fs.copyTpl`, `fs.move` etc.) in `install` function( in the callback of `npmInstall` especially), and why?

**Comment by SBoudrias** [comment]
@Jberryliu the write phase is already passed at that time. Why do you need to write file as npmInstall callback?

**Comment by Jberryliu** [comment]
cause I need copy the installed files to other directory after npmInstall, so the write phase must run in npmInstall callback. I saw the example shows using grunt in the callback to do this, but I think writing file is the easy one.

**Comment by SBoudrias** [comment]
@Jberryliu Ok, but I don't see why you'd need to copy file you just npm installed? If these are template files, I feel you should copy them from your generator instead of the user project `node_modules`.

**Comment by SBoudrias** [comment]
About a fix, maybe we should triggers events each time `mem-fs` change. Then we schedule a write task each time it changes (using the grouped-queue `once` option so it is only scheduled at most once).

**Comment by SBoudrias** [comment]
Closing in favor of the new issue on yeoman/generator

**Comment by SBoudrias** [comment]
This issue is fixed on master, and will work on our next release. (It'll require an update installation of yo also `npm update`)

**Comment by Jberryliu** [comment]
thanks for help :)
