### ISSUE TITLE
Unable to install using npm

### ISSUE THREAD

**Issue by pankajbhandari08** [yeoman/yeoman#1476]
HI am used the command 
npm install -g yo on windows 7 machine
and also tried with npm install -g yo@1.3.3

but the installation failed.

The error log is :

D:\dev>npm install -g yo
C:\Users\Pankaj Bhandari\AppData\Roaming\npm\yo -> C:\Users\Pankaj Bhandari\AppData\Roaming\npm\node_modules\yo\cli.js

> yo@1.3.3 postinstall C:\Users\Pankaj Bhandari\AppData\Roaming\npm\node_modules\yo
> yodoctor

npm ERR! yo@1.3.3 postinstall: `yodoctor`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the yo@1.3.3 postinstall script.
npm ERR! This is most likely a problem with the yo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     yodoctor
npm ERR! You can get their info via:
npm ERR!     npm owner ls yo
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\nodejs\\\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\n
pm-cli.js" "install" "-g" "yo"
npm ERR! cwd D:\dev
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! syscall spawn
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! not ok code 0

**Comment by kevva** [comment]
https://github.com/yeoman/yo/issues/219
https://www.google.se/search?q=yodoctor+spawn+enoent&oq=yodoctor+spawn+enoent&aqs=chrome..69i57.2863j0j1&sourceid=chrome&es_sm=0&ie=UTF-8
