### ISSUE TITLE
yeoman setup error

### ISSUE THREAD

**Issue by vidyasrini** [yeoman/yeoman#1478]
yodoctor

oman Doctor
nning sanity checks on your system

Global configuration file is valid
NODE_PATH matches the npm root

 found a undefined file in your home directory. This can cause
sues by overriding expected default config. Prefer setting up one `.bowerrc` p

oject.

 delete the file, run: del ~/.bowerrc

und a NaN file in your home directory. Delete it otherwise
oman will generate everything in your home rather then your project folder.

 delete the file, run: del ~/.yo-rc.json

und potential issues on your machine :(
unt-contrib-copy@0.5.0 ..\node_modules\grunt-contrib-copy

unt-rev@0.1.0 ..\node_modules\grunt-rev

ache-server-configs@2.11.0 ..\node_modules\apache-server-configs

unt-contrib-clean@0.6.0 ..\node_modules\grunt-contrib-clean
─ rimraf@2.2.8

unt-concurrent@0.5.0 ..\node_modules\grunt-concurrent
─ async@0.2.10
─ pad-stdio@0.1.1 (lpad@0.2.1)

me-grunt@0.4.0 ..\node_modules\time-grunt
─ date-time@0.1.1
─ figures@1.3.5
─ hooker@0.2.3
─ text-table@0.2.0
─ pretty-ms@0.2.2 (parse-ms@0.1.2)
─ chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0
.0, strip-ansi@0.3.0, has-ansi@0.1.0)

unt-newer@0.7.0 ..\node_modules\grunt-newer
─ async@0.2.10
─ rimraf@2.2.6

ad-grunt-tasks@0.4.0 ..\node_modules\load-grunt-tasks
─ multimatch@0.1.0 (lodash@2.4.1, minimatch@0.2.14)
─ findup-sync@0.1.3 (lodash@2.4.1, glob@3.2.11)

hint-stylish@0.4.0 ..\node_modules\jshint-stylish
─ log-symbols@1.0.1
─ text-table@0.2.0
─ chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0
.0, has-ansi@0.1.0, strip-ansi@0.3.0)

unt-usemin@2.6.2 ..\node_modules\grunt-usemin
─ lodash@2.4.1
─ debug@2.1.1 (ms@0.6.2)
─ chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0
.0, has-ansi@0.1.0, strip-ansi@0.3.0)

unt-contrib-concat@0.5.0 ..\node_modules\grunt-contrib-concat
─ source-map@0.1.43 (amdefine@0.1.0)
─ chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0
.0, has-ansi@0.1.0, strip-ansi@0.3.0)

unt-contrib-watch@0.6.1 ..\node_modules\grunt-contrib-watch
─ async@0.2.10
─ lodash@2.4.1
─ gaze@0.5.1 (globule@0.1.0)
─ tiny-lr-fork@0.0.5 (debug@0.7.4, qs@0.5.6, faye-websocket@0.4.4, noptify@0.0
)

unt-contrib-htmlmin@0.3.0 ..\node_modules\grunt-contrib-htmlmin
─ pretty-bytes@0.1.2
─ chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
─ html-minifier@0.6.9 (relateurl@0.2.6, clean-css@2.2.23, change-case@2.1.6, c
@0.6.5, uglify-js@2.4.16)

unt-svgmin@0.4.0 ..\node_modules\grunt-svgmin
─ each-async@0.1.3
─ pretty-bytes@0.1.2
─ chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
─ svgo@0.4.5 (colors@0.6.2, whet.extend@0.9.9, coa@0.4.1, sax@0.6.1, js-yaml@2
.3)

unt-contrib-connect@0.8.0 ..\node_modules\grunt-contrib-connect
─ connect-livereload@0.4.1
─ open@0.0.5
─ async@0.9.0
─ portscanner@0.2.3 (async@0.1.15)
─ connect@2.19.6 (parseurl@1.0.1, morgan@1.1.1, response-time@2.0.0, qs@0.6.6,
host@1.0.0, pause@0.0.1, bytes@1.0.0, cookie@0.1.2, on-headers@0.0.0, cookie-s
nature@1.0.3, serve-favicon@2.0.1, basic-auth-connect@1.0.0, escape-html@1.0.1
errorhandler@1.0.2, fresh@0.2.2, cookie-parser@1.1.0, debug@1.0.2, connect-tim
ut@1.1.0, method-override@2.0.2, body-parser@1.3.1, express-session@1.2.1, typ
is@1.2.1, csurf@1.2.1, compression@1.0.7, serve-static@1.2.3, multiparty@3.2.8
serve-index@1.1.1)

unt@0.4.5 ..\node_modules\grunt
─ dateformat@1.0.2-1.2.3
─ which@1.0.8
─ eventemitter2@0.4.14
─ getobject@0.1.0
─ colors@0.6.2
─ rimraf@2.2.8
─ async@0.1.22
─ lodash@0.9.2
─ grunt-legacy-util@0.2.0
─ exit@0.1.2
─ hooker@0.2.3
─ iconv-lite@0.2.11
─ coffee-script@1.3.3
─ underscore.string@2.2.1
─ nopt@1.0.10 (abbrev@1.0.5)
─ minimatch@0.2.14 (sigmund@1.0.0, lru-cache@2.5.0)
─ glob@3.1.21 (inherits@1.0.0, graceful-fs@1.2.3)
─ js-yaml@2.0.5 (esprima@1.0.4, argparse@0.1.16)
─ findup-sync@0.1.3 (glob@3.2.11, lodash@2.4.1)
─ grunt-legacy-log@0.1.1 (underscore.string@2.3.3, lodash@2.4.1)

unt-contrib-cssmin@0.10.0 ..\node_modules\grunt-contrib-cssmin
─ chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
─ clean-css@2.2.23 (commander@2.2.0)
─ maxmin@0.2.2 (figures@1.3.5, pretty-bytes@0.1.2, chalk@0.5.1, gzip-size@0.2.

unt-contrib-jshint@0.10.0 ..\node_modules\grunt-contrib-jshint
─ hooker@0.2.3
─ jshint@2.5.11 (strip-json-comments@1.0.2, underscore@1.6.0, minimatch@1.0.0,
xit@0.1.2, shelljs@0.3.0, console-browserify@1.1.0, cli@0.6.5, htmlparser2@3.8
)

unt-wiredep@1.9.0 ..\node_modules\grunt-wiredep
─ wiredep@1.8.6 (propprop@0.3.0, minimist@1.1.0, through2@0.6.3, glob@4.3.5, c
lk@0.5.1, lodash@2.4.1, bower-config@0.5.2)

unt-mocha@0.4.11 ..\node_modules\grunt-mocha
─ lodash@2.3.0
─ mocha@1.18.2 (diff@1.0.7, growl@1.7.0, commander@2.0.0, debug@2.1.1, mkdirp@
3.5, glob@3.2.3, jade@0.26.3)
─ grunt-lib-phantomjs@0.4.0 (eventemitter2@0.4.14, semver@1.0.14, temporary@0.
8, phantomjs@1.9.15)

unt-contrib-uglify@0.5.1 ..\node_modules\grunt-contrib-uglify
─ lodash@2.4.1
─ chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.2, supports-color@0
.0, has-ansi@0.1.0, strip-ansi@0.3.0)
─ uglify-js@2.4.16 (uglify-to-browserify@1.0.2, async@0.2.10, optimist@0.3.7,
urce-map@0.1.34)
─ maxmin@0.2.2 (figures@1.3.5, pretty-bytes@0.1.2, gzip-size@0.2.0)

unt-autoprefixer@1.0.1 ..\node_modules\grunt-autoprefixer
─ diff@1.0.8
─ chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0
.0, has-ansi@0.1.0, strip-ansi@0.3.0)
─ autoprefixer-core@3.1.2 (postcss@2.2.6, caniuse-db@1.0.30000065)

unt-contrib-imagemin@0.8.1 ..\node_modules\grunt-contrib-imagemin
─ async@0.9.0
─ pretty-bytes@1.0.2 (get-stdin@1.0.0)
─ chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0
.0, has-ansi@0.1.0, strip-ansi@0.3.0)
─ imagemin@1.0.5 (get-stdin@3.0.2, stat-mode@0.2.0, ware@0.3.0, nopt@3.0.1, te
file@1.1.0, fs-extra@0.11.1, imagemin-svgo@1.0.2)

\Users\Ashok>del ~/.bowerrc
valid switch - ".bowerrc".

\Users\Ashok>del ~/.yo-rc.json
valid switch - ".yo-rc.json".

\Users\Ashok>

**Comment by eddiemonge** [comment]
this output is cutoff. Can you paste the full output please?

**Comment by kevva** [comment]
Just remove the two files in your home folder using the explorer.

**Comment by vidyasrini** [comment]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Ashok>yo doctor

C:\Users\Ashok\AppData\Roaming\npm\node_modules\yo\cli.js:54
    require('yeoman-doctor').run();
                             ^
TypeError: Object function () {
  var errCount = 0;

  console.log('\n' + chalk.underline.blue('Yeoman Doctor'));
  console.log('Running sanity checks on your system\n');

  eachAsync(objectValues(rules), function (rule, i, cb) {
    rule.verify(function (err) {
      console.log(err ? symbols.error : symbols.success + ' ' + rule.description
);

      if (err) {
        errCount++;
        console.log(err);
      }

      cb();
    });
  }, function () {
    if (errCount === 0) {
      console.log(chalk.green('\nEverything looks all right!'));
    } else {
      console.log(chalk.red('\nFound potential issues on your machine :('));
    }
  });
} has no method 'run'
    at pre (C:\Users\Ashok\AppData\Roaming\npm\node_modules\yo\cli.js:54:30)
    at Object.<anonymous> (C:\Users\Ashok\AppData\Roaming\npm\node_modules\yo\cl
i.js:161:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

C:\Users\Ashok>del "%HOMEPATH%\.bowerrc"
Could Not Find C:\Users\Ashok\.bowerrc

C:\Users\Ashok>del "%HOMEPATH%\.yo-rc.json"
Could Not Find C:\Users\Ashok\.yo-rc.json

C:\Users\Ashok>

**Comment by kevva** [comment]
Don't forget the `\` between `%HOMEPATH%` and the filename.

**Comment by eddiemonge** [comment]
> Last resort; switch to Ubuntu.

Last resort? More like first resort amirite!!?!

**Comment by kevva** [comment]
There should come a USB stick with every PC you buy with an Ubuntu ISO on it.
