### ISSUE TITLE
Grunt error " Error: Cannot find module 'postcss' "

### ISSUE THREAD

**Issue by SlyDeGout** [yeoman/yeoman#1480]
When trying using "grunt doctor", I have the following  error. Any idea anyone

Loading "autoprefixer.js" tasks...ERROR
>> Error: Cannot find module 'postcss'
Warning: Task "doctor" not found. Use --force to continue.

Aborted due to warnings.

**Comment by sindresorhus** [comment]
https://github.com/npm/npm/issues/new
