### ISSUE TITLE
Using MEAN stack on Windows can result with folder hierarchy that is easy to delete

### ISSUE THREAD

**Issue by adriatic** [yeoman/yeoman#1483]
I am not sure whether the title of this issue is well known to everyone on this team, so let me elaborate briefly:
Based on http://yeoman.io/learning/ article I just run the sequence

    npm install -g generator-webapp
    mkdir my-yo-project
    cd my-yo-project
    yo webapp

After some crunching I got some 80 Mbytes worth of app skeleton. As this was just the test to peek into the content of this skeleton, I wanted to delete the my-yo-project -- only to find that any ordinary means to do that led nowhere; I became a victim of quite often encountered problem
 
![image](https://cloud.githubusercontent.com/assets/2712405/6334402/6da617da-bb62-11e4-9e84-987895c8632e.png)

After some amount of wasted time trying all the tricks I had available, I realized that the only real solution (and I am still not sure that it works always) is described [here](http://thenubbyadmin.com/2014/01/15/cant-delete-files-in-windows-because-the-source-file-names-are-larger-than-is-supported-by-the-file-system-and-how-to-solve-it/) (courtesy of Wesley David).

While this solution seems to work, it is incredibly in-elegant hack. Yeoman's utility is big and it should not be tarnished with the reputation of a "disk space waster" -- even if this is a Microsoft problem. 

Yeoman should be able to cleanly clean after itself :-)

**Comment by eddiemonge** [comment]
This is a npm issue as that is there where the paths are too long. Yeoman itself, especially that generator, are not creating a long file name. See https://github.com/joyent/node/issues/6960 as an example.

**Comment by kevva** [comment]
You can use `rimraf` to remove deeply nested directories.

```sh
$ npm install --global rimraf
$ rimraf <dir>
```

**Comment by adriatic** [comment]
I would respectfully disagree @eddiemonge as the problem was created by yeoman (by virtue of using npm, of course). When you are served a food that seems inedible, the waiter should not send you to see the cook - the waiter (if any good) will resolve this issue directly with you (the guest).

I am suggesting to create the gulp task that uses rimraf as pointed to by Kevin. Of course that I can do it in my own fork of the yeoman gulp, but this will not help others who run into this and may be less experienced than I am

**Comment by kevva** [comment]
@adriatic, this is definitely **not** a yeoman problem. It's just how npm works, we can't control how dependencies gets installed etc.

**Comment by eddiemonge** [comment]
@adriatic By that logic you are also asking us to fix Windows itself. Deleting the `node_modules` directory (which is most likely the problem) must be a user initiated thing since you need those to work with the build system. We can't generate the project then immediately delete that folder as it would make the project pretty unusable.

**Comment by adriatic** [comment]
I think that saying "by that logic, are you also asking us to fix Windows itself" is a bit patronizing - and you have no idea who I really am, so taking such position as you did is less than optimal :-), not to mention that customers should always be treated in a courteous way.

Here is the logic I used to write the original proposal - and you are of course free to deem it bad.

- We all know that we cannot fix windows so, there is no need to belabor that point.
- This is only a conditional npm issue as it happens only when it (npm) is driven by a generator like yeoman.
- Without this windows bug, I would not propose to "hack" yeoman by adding the rimraf task to it. However, since the yeoman user will almost always end up with the folder hierarchy that cannot be deleted, I would expect to get the help from that same tool that created the mess for me (and please do not remind me that this is a windows problem, and I should switch to OSX :-)

Additional note to Kevin: this is indeed a problem that is best handled by yeoman as npm is completely unaware of the ways yeoman uses it. npm should not be "fixed" to say "hey I got too deep in the folder nesting, so you mr. user will not be able to delete what I am just creating.

Sorry for disturbing you with this issue - I was thinking to help Yeoman users not Yeoman developers

**Comment by adriatic** [comment]
Oh: do you really believe that I do not understand this situation to the point that you felt the need to explain "We can't generate the project then immediately delete that folder as it would make the project pretty unusable."

**Comment by SBoudrias** [comment]
@adriatic Just to be clear, this is an open source project... I don't think anyone here is a consumer, we have _users_ and no one is entitled to anything.

That being said, I'm sorry you felt some answer were rude.

From our side, this is an issue on the side of npm. This is because node_modules structure is the way node modules are working, and we run on top of node. As users of the node platform, this is out of our direct control.

But know npm is working to alleviate this issue on their next major release. http://blog.npmjs.org/post/110924823920/npm-weekly-5

**Comment by eddiemonge** [comment]
I am sorry if my response came across as rude. I didn't mean it that way. I was merely pointing out a counter argument to your example. There are a lot of rude people that come on here and attack us and sometimes my sarcasm doesn't come across the way I intended it. In this case it was a bit harsh and I apologize. Like Simon said, this is an open source project that we work on out of the goodness of our hearts. We don't get paid for doing it; its a labor of love. Thats why I sometimes take offense when people seem ungrateful. Not saying this was the case here, just providing some context. Again, I sincerely apologize and hope you keep using Yeoman.

Anyone who uses npm on Windows and installs a package that has a lot of dependencies is going to face this problem, not just using Yeoman. npm is aware of the issue so if we were to implement a temporary solution to handle it would most likely be a diversion of our time that could be spent on fixing other bugs like https://github.com/yeoman/generator/issues/754

**Comment by adriatic** [comment]
@SBoudrias : I am well aware of the nature of this project, the fact that everyone working in it works out of the desire to help others and I am very appreciative of all of your efforts. I also really understand your reasoning stated as 
> From our side, this is an issue on the side of npm. This is because node_modules structure is the way node modules are working, and we run on top of node. As users of the node platform, this is out of our direct control.

My initial proposal was a simple fix for people who do not care to understand the internal workings of npm - even to the point that they do not need to grasp the need for depth in node_modules structure. We spent way too much discussing this trivial problem and I persisted because I really liked your immediate reaction to my post. Lastly your [reference to npm updates ](http://blog.npmjs.org/post/110924823920/npm-weekly-5) will address this in the right way (and prove my real point that going as deep simply because unix-like file system is a lot smarter than windows is not a good reason :-)

**Comment by adriatic** [comment]
Simply wonderful response @eddiemonge - getting to meet you in the way I just did was well worth the effort of typing all this :-)
I was not expecting to use Yeoman for longer than to just see what it generates -- since most people find code generation tools less useful as they progress into the use of the code. Now, you changed my mind simply because I liked what you wrote and plan to stick around and share some ideas with you once I get sufficient understand of what you plan to do.
