### ISSUE TITLE
Yeoman Installation issues -- not able to find yo --version && bower --version && grunt --version

### ISSUE THREAD

**Issue by vivekduddempudi** [yeoman/yeoman#1484]
Please let me know ,where i went wrong. 

Not able to find yo --version && bower --version && grunt --version

-------------------------------------------------------------------------------------------------------------------------------
D:\loopbackDemo>node --version && npm --version
v0.12.0
2.6.0
-------------------------------------------------------------------------------------------------------------------------------
D:\loopbackDemo>git --version
git version 1.9.5.msysgit.0
-------------------------------------------------------------------------------------------------------------------------------
D:\loopbackDemo>npm install --global yo bower grunt-cli
npm WARN deprecation Per-package engineStrict will no longer be used
npm WARN deprecation in upcoming versions of npm. Use the config
npm WARN deprecation setting `engine-strict` instead.
npm WARN deprecation Per-package engineStrict will no longer be used
npm WARN deprecation in upcoming versions of npm. Use the config
npm WARN deprecation setting `engine-strict` instead.
npm WARN deprecation Per-package engineStrict will no longer be used
npm WARN deprecation in upcoming versions of npm. Use the config
npm WARN deprecation setting `engine-strict` instead.
npm WARN deprecation Per-package engineStrict will no longer be used
npm WARN deprecation in upcoming versions of npm. Use the config
npm WARN deprecation setting `engine-strict` instead.
npm WARN deprecation Per-package engineStrict will no longer be used
npm WARN deprecation in upcoming versions of npm. Use the config
npm WARN deprecation setting `engine-strict` instead.
npm WARN deprecation Per-package engineStrict will no longer be used
npm WARN deprecation in upcoming versions of npm. Use the config
npm WARN deprecation setting `engine-strict` instead.
npm WARN deprecation Per-package engineStrict will no longer be used
npm WARN deprecation in upcoming versions of npm. Use the config
npm WARN deprecation setting `engine-strict` instead.
npm WARN deprecation Per-package engineStrict will no longer be used
npm WARN deprecation in upcoming versions of npm. Use the config
npm WARN deprecation setting `engine-strict` instead.
npm WARN deprecation Per-package engineStrict will no longer be used
npm WARN deprecation in upcoming versions of npm. Use the config
npm WARN deprecation setting `engine-strict` instead.
npm WARN deprecation Per-package engineStrict will no longer be used
npm WARN deprecation in upcoming versions of npm. Use the config
npm WARN deprecation setting `engine-strict` instead.
npm WARN deprecation Per-package engineStrict will no longer be used
npm WARN deprecation in upcoming versions of npm. Use the config
npm WARN deprecation setting `engine-strict` instead.
npm WARN deprecation Per-package engineStrict will no longer be used
npm WARN deprecation in upcoming versions of npm. Use the config
npm WARN deprecation setting `engine-strict` instead.
C:\Users\Vivek\npm\grunt -> C:\Users\Vivek\npm\node_modules\grunt-cli\bin\grunt
C:\Users\Vivek\npm\yo -> C:\Users\Vivek\npm\node_modules\yo\lib\cli.js

> yo@1.4.5 postinstall C:\Users\Vivek\npm\node_modules\yo
> yodoctor

C:\Users\Vivek\npm\bower -> C:\Users\Vivek\npm\node_modules\bower\bin\bower

Yeoman Doctor
Running sanity checks on your system

√ Global configuration file is valid
√ NODE_PATH matches the npm root
√ No .bowerrc file in home directory
√ No .yo-rc.json file in home directory

Everything looks all right!
grunt-cli@0.1.13 C:\Users\Vivek\npm\node_modules\grunt-cli
├── nopt@1.0.10 (abbrev@1.0.5)
├── resolve@0.3.1
└── findup-sync@0.1.3 (lodash@2.4.1, glob@3.2.11)

bower@1.3.12 C:\Users\Vivek\npm\node_modules\bower
├── is-root@1.0.0
├── stringify-object@1.0.0
├── junk@1.0.1
├── abbrev@1.0.5
├── chmodr@0.1.0
├── which@1.0.8
├── osenv@0.1.0
├── archy@0.0.2
├── rimraf@2.2.8
├── lru-cache@2.5.0
├── opn@1.0.1
├── bower-endpoint-parser@0.2.2
├── bower-logger@0.2.2
├── graceful-fs@3.0.5
├── lockfile@1.0.0
├── retry@0.6.0
├── nopt@3.0.1
├── tmp@0.0.23
├── request-progress@0.3.0 (throttleit@0.0.2)
├── q@1.0.1
├── chalk@0.5.0 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0
.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
├── shell-quote@1.4.2 (array-filter@0.0.1, array-reduce@0.0.0, array-map@0.0.0,
jsonify@0.0.0)
├── bower-json@0.4.0 (intersect@0.0.3, deep-extend@0.2.11, graceful-fs@2.0.3)
├── semver@2.3.2
├── fstream@1.0.4 (inherits@2.0.1)
├── p-throttler@0.1.0 (q@0.9.7)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── promptly@0.2.0 (read@1.0.5)
├── bower-config@0.5.2 (osenv@0.0.3, graceful-fs@2.0.3, optimist@0.6.1)
├── fstream-ignore@1.0.2 (inherits@2.0.1, minimatch@2.0.1)
├── tar-fs@0.5.2 (pump@0.3.5, tar-stream@0.4.7)
├── decompress-zip@0.0.8 (mkpath@0.1.0, nopt@2.2.1, touch@0.0.2, readable-stream
@1.1.13, binary@0.3.0)
├── request@2.42.0 (caseless@0.6.0, json-stringify-safe@5.0.0, forever-agent@0.5
.2, aws-sign2@0.5.0, stringstream@0.0.4, oauth-sign@0.4.0, tunnel-agent@0.4.0, q
s@1.2.2, node-uuid@1.4.2, mime-types@1.0.2, form-data@0.1.4, bl@0.9.4, http-sign
ature@0.10.1, tough-cookie@0.12.1, hawk@1.1.1)
├── glob@4.0.6 (inherits@2.0.1, once@1.3.1, minimatch@1.0.0)
├── bower-registry-client@0.2.3 (graceful-fs@2.0.3, request-replay@0.2.0, lru-ca
che@2.3.1, mkdirp@0.3.5, async@0.2.10, request@2.51.0)
├── cardinal@0.4.0 (redeyed@0.4.4)
├── mout@0.9.1
├── update-notifier@0.2.0 (semver-diff@0.1.0, string-length@0.1.2, latest-versio
n@0.2.0, configstore@0.3.2)
├── handlebars@2.0.0 (optimist@0.3.7, uglify-js@2.3.6)
├── inquirer@0.7.1 (figures@1.3.5, mute-stream@0.0.4, through@2.3.6, readline2@0
.1.1, lodash@2.4.1, cli-color@0.3.2, rx@2.4.1)
└── insight@0.4.3 (object-assign@1.0.0, chalk@0.5.1, async@0.9.0, lodash.debounc
e@2.4.1, os-name@1.0.3, tough-cookie@0.12.1, configstore@0.3.2, inquirer@0.6.0)

yo@1.4.5 C:\Users\Vivek\npm\node_modules\yo
├── titleize@1.0.0
├── array-uniq@1.0.2
├── figures@1.3.5
├── user-home@1.1.1
├── opn@1.0.1
├── sort-on@1.0.2 (dot-prop@1.0.1)
├── humanize-string@1.0.1 (decamelize@1.0.0)
├── yeoman-character@1.0.1 (supports-color@1.3.0)
├── string-length@1.0.0 (strip-ansi@2.0.1)
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0
.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
├── async@0.9.0
├── cross-spawn@0.2.6 (lru-cache@2.5.0)
├── root-check@1.0.0 (sudo-block@1.1.0, downgrade-root@1.1.0)
├── findup@0.1.5 (commander@2.1.0, colors@0.6.2)
├── yosay@1.0.2 (ansi-regex@1.1.1, ansi-styles@2.0.1, strip-ansi@2.0.1, pad-comp
onent@0.0.1, word-wrap@1.0.0, taketalk@1.0.0, minimist@1.1.0)
├── meow@3.0.0 (object-assign@2.0.0, camelcase-keys@1.0.0, minimist@1.1.0, inden
t-string@1.2.1)
├── update-notifier@0.3.0 (is-npm@1.0.0, latest-version@1.0.0, semver-diff@2.0.0
)
├── npm-keyword@1.1.0 (registry-url@3.0.0, got@2.4.0)
├── package-json@1.1.0 (registry-url@3.0.0, got@2.4.0)
├── fullname@1.1.0 (npmconf@2.1.1)
├── lodash@2.4.1
├── insight@0.5.2 (object-assign@2.0.0, lodash.debounce@2.4.1, os-name@1.0.3, to
ugh-cookie@0.12.1, request@2.53.0)
├── yeoman-doctor@1.3.2 (object-values@1.0.0, log-symbols@1.0.2, each-async@1.1.
1, chalk@1.0.0, twig@0.7.2)
├── yeoman-environment@1.2.4 (escape-string-regexp@1.0.3, untildify@2.0.0, diff@
1.2.2, text-table@0.2.0, debug@2.1.1, log-symbols@1.0.2, mem-fs@1.1.0, globby@1.
2.0, grouped-queue@0.3.0, lodash@3.3.0)
├── configstore@0.3.2 (object-assign@2.0.0, xdg-basedir@1.0.1, osenv@0.1.0, grac
eful-fs@3.0.5, uuid@2.0.1, mkdirp@0.5.0, js-yaml@3.2.7)
└── inquirer@0.8.0 (ansi-regex@1.1.1, mute-stream@0.0.4, through@2.3.6, readline
2@0.1.1, cli-color@0.3.2, rx@2.4.1)
-------------------------------------------------------------------------------------------------------------------------------
D:\loopbackDemo>yo --version && bower --version && grunt --version
'yo' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Munter** [comment]
Are globally installed node binaries in your PATH?

**Comment by vivekduddempudi** [comment]
hi Munter

I am new to nodejs. i just followed steps mentioned in this link http://yeoman.io/codelab/setup.html

Please let know clearly regarding my mistake.

**Comment by Munter** [comment]
Including your npm globally installed binary directory in your `PATH` falls within setting up node correctly, which is probably why it's not a part of the Yeoman install guide.

Follow these instructions:
http://stackoverflow.com/questions/23860262/npm-global-install-does-not-add-packages-to-path-on-windows-8-1

**Comment by sindresorhus** [comment]
https://www.google.com/search?q=npm+is+not+recognized+as+an+internal+or+external+command%2C&oq=npm+is+not+recognized+as+an+internal+or+external+command%2C&aqs=chrome..69i57j0l4j69i64.871j0j1&sourceid=chrome&es_sm=91&ie=UTF-8#q=yo+is+not+recognized+as+an+internal+or+external+command%2C

**Comment by vivekduddempudi** [comment]
Thank You very much for your support. My solution for this issue.
I installed node js in D-drive and npm in C:\Users\xxxx\npm 

Open command Prompt[Admin] : $ Path 

here we can find npm path. next 

1. Right-Click on My Computer icon 
2. Select the Advanced tab 
3. Click on Environment Variables 
4. Under "System Variables" locate Path and choose 'EDIT'. 
5. Copy this entire string and paste it into Notepad for safe keeping. 
6. Add the directory that houses your program. Example: C:\Users\xxxx\npm; 
7. Verify that you used a semi-colon followed by a space for item number 6. 
8. Click 'Ok'

Go back to command Prompt[Admin] : 
$ yo --version && bower --version && grunt --version

my result
Yeoman 1.3.2, Bower 1.3.12, and grunt-cli v0.1.13.

This Confirm installation
