### ISSUE TITLE
yo generator does not finish on windows

### ISSUE THREAD

**Issue by idev4u** [yeoman/yeoman#1490]
My environment is as follows:
Prject folder \Developer\web\projects\test-ember>
yo 1.4.5
bower 1.3.12
grunt-cli v0.1.13
grunt v0.4.5
git version 1.9.5.msysgit.0
node v0.12.0
npm 2.5.1

when I run yo ember then the whole process hang maybe at this point.
```
grunt-contrib-imagemin@0.8.1 node_modules\grunt-contrib-imagemin
├── pretty-bytes@1.0.3 (get-stdin@4.0.1)
├── async@0.9.0
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
└── imagemin@1.0.5 (get-stdin@3.0.2, stat-mode@0.2.0, ware@0.3.0, nopt@3.0.1, tempfile@1.1.0, fs-extra@0.11.1, imagemin-svgo@1.0.2, imagemin-jpegtran@1.0.0, imagemin-pngquant@1.0.2, imagemin-gif
sicle@1.0.0, imagemin-optipng@1.0.0)
```
I stop with ctrl-c ok maby to heavy, but what should I do? After that  I run yo doctor and the result is

```
Yeoman Doctor
Running sanity checks on your system

√ Global configuration file is valid
√ NODE_PATH matches the npm root
√ No .bowerrc file in home directory
√ No .yo-rc.json file in home directory

Everything looks all right!
```
but the files are not complite I add the folder tree
![projectfolder](https://cloud.githubusercontent.com/assets/10629367/6480067/8fb02b38-c24f-11e4-8eb1-52d479e655fe.png)

One last hint on OSX it works well with ember

**Comment by SBoudrias** [comment]
Open an issue on the generator you're using.
