### ISSUE TITLE
cannot install Yeoman after updating my Mac OS to Yosemite 

### ISSUE THREAD

**Issue by wramirez09** [yeoman/yeoman#1493]
** h1 here the error thrown. 
env: node: No such file or directory
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "yo"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! yo@1.4.6 postinstall: `yodoctor`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the yo@1.4.6 postinstall script 'yodoctor'.
npm ERR! This is most likely a problem with the yo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     yodoctor
npm ERR! You can get their info via:
npm ERR!     npm owner ls yo
npm ERR! There is likely additional logging output above. 

*please advise

**Comment by SBoudrias** [comment]
Please google it.

**Comment by wramirez09** [comment]
I did no luck

**Comment by SBoudrias** [comment]
I'm sorry you couldn't find anything, but a **LOT** of issues about this specific errors have been opened.

You should find details on one of these: (and I only went through 2 pages of search, there's multiple more)

https://github.com/yeoman/yeoman/issues/1439
https://github.com/yeoman/yeoman/issues/1454
https://github.com/yeoman/yeoman/issues/1379
https://github.com/yeoman/yeoman/issues/1386
https://github.com/yeoman/yeoman/issues/1347

**Comment by ilife5** [comment]
@wramirez09 

```
npm -g install yeoman-doctor
```

can fix it
