### ISSUE TITLE
Subfolders in app

### ISSUE THREAD

**Issue by brunoDegaspare** [yeoman/yeoman#1495]
I apologise if this is not the right place to ask this.

I am using Yeoman to create 3 different templates that shares the same scss and js file. I need to set a structure like this:

![structure](https://cloud.githubusercontent.com/assets/7714748/6755268/b802d8b6-cf19-11e4-8d2b-6270fd8aea4a.jpg)

My question is: How I can set Yeoman Grunt file to watch the scss file inside each template folder and shared folder? I have

    
         <link rel="stylesheet" href="../shared/styles/main.css">
    

inside each index.html file and all I am getting is a 404 error. Any idea?

**Comment by SBoudrias** [comment]
Please refer your questions to StackOverflow.
