### ISSUE TITLE
Installation of bower

### ISSUE THREAD

**Issue by juztinlazaro** [yeoman/yeoman#1496]
Having a problem when im install bower in npm, its give me an error unexpected end of input

and when i use bower init. it not recognized.

**Comment by SBoudrias** [comment]
trace? details?

**Comment by juztinlazaro** [comment]
i've fixed it now :D by using this approach

$ npm config set prefix /usr/local
$ npm install -g bower

$ which bower>> /usr/local/bin/bower


but my problem is when im using bower init

it say bower not recoginized? for newbie here

**Comment by SBoudrias** [comment]
Add bower to your path.

**Comment by juztinlazaro** [comment]
Thanks bro. :)) gb
