### ISSUE TITLE
NPM fails to install yo

### ISSUE THREAD

**Issue by ms-clovis** [yeoman/yeoman#1497]
I am working on a Docker image of ubuntu 14.0.4. Ubuntu and Debian has the fork of node (know as nodejs) and therefore I install node using NVM 1) curl https://raw.githubusercontent.com/creationix/nvm/v0.16.1/install.sh | sh and 2) nvm install 0.12.2.

This leaves me with node -v == 0.12.2, npm -v ==2.7.4 

The error message is 

15886 info linkStuff yo@1.4.6
15887 verbose linkBins yo@1.4.6
15888 verbose link bins [ { yo: 'lib/cli.js' }, '/root/.nvm/versions/v0.12.2/bin', true ]
15889 verbose linkMans yo@1.4.6
15890 verbose rebuildBundles yo@1.4.6
15891 verbose rebuildBundles [ '.bin',
15891 verbose rebuildBundles   'array-uniq',
15891 verbose rebuildBundles   'async',
15891 verbose rebuildBundles   'chalk',
15891 verbose rebuildBundles   'configstore',
15891 verbose rebuildBundles   'cross-spawn',
15891 verbose rebuildBundles   'figures',
15891 verbose rebuildBundles   'findup',
15891 verbose rebuildBundles   'fullname',
15891 verbose rebuildBundles   'got',
15891 verbose rebuildBundles   'humanize-string',
15891 verbose rebuildBundles   'inquirer',
15891 verbose rebuildBundles   'insight',
15891 verbose rebuildBundles   'lodash',
15891 verbose rebuildBundles   'meow',
15891 verbose rebuildBundles   'npm-keyword',
15891 verbose rebuildBundles   'opn',
15891 verbose rebuildBundles   'package-json',
15891 verbose rebuildBundles   'root-check',
15891 verbose rebuildBundles   'sort-on',
15891 verbose rebuildBundles   'string-length',
15891 verbose rebuildBundles   'titleize',
15891 verbose rebuildBundles   'update-notifier',
15891 verbose rebuildBundles   'user-home',
15891 verbose rebuildBundles   'yeoman-character',
15891 verbose rebuildBundles   'yeoman-doctor',
15891 verbose rebuildBundles   'yeoman-environment',
15891 verbose rebuildBundles   'yosay' ]
15892 silly gentlyRm /root/.nvm/versions/v0.12.2/bin/yo is being gently removed
15893 silly gentlyRm verifying /root/.nvm/versions/v0.12.2 is an npm working directory
15894 silly gentlyRm containing path /root/.nvm/versions/v0.12.2 is under npm's control, in /root/.nvm/versions/v0.12.2
15895 silly gentlyRm deletion target /root/.nvm/versions/v0.12.2/bin/yo is under /root/.nvm/versions/v0.12.2
15896 verbose gentlyRm vacuuming from /root/.nvm/versions/v0.12.2/bin/yo up to /root/.nvm/versions/v0.12.2
15897 info install yo@1.4.6
15898 info postinstall yo@1.4.6
15899 verbose unsafe-perm in lifecycle false
15900 info yo@1.4.6 Failed to exec postinstall script
15901 verbose unlock done using /root/.npm/_locks/yo-39fea78c230c11f9.lock for /root/.nvm/versions/v0.12.2/lib/node_modules/yo
15902 verbose stack Error: yo@1.4.6 postinstall: `yodoctor`
15902 verbose stack Exit status 127
15902 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/v0.12.2/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
15902 verbose stack     at EventEmitter.emit (events.js:110:17)
15902 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/v0.12.2/lib/node_modules/npm/lib/utils/spawn.js:14:12)
15902 verbose stack     at ChildProcess.emit (events.js:110:17)
15902 verbose stack     at maybeClose (child_process.js:1015:16)
15902 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
15903 verbose pkgid yo@1.4.6
15904 verbose cwd /root
15905 error Linux 3.18.5-tinycore64
15906 error argv "/root/.nvm/versions/v0.12.2/bin/node" "/root/.nvm/versions/v0.12.2/bin/npm" "install" "yo" "-g"
15907 error node v0.12.2
15908 error npm  v2.7.4
15909 error code ELIFECYCLE
15910 error yo@1.4.6 postinstall: `yodoctor`
15910 error Exit status 127
15911 error Failed at the yo@1.4.6 postinstall script 'yodoctor'.
15911 error This is most likely a problem with the yo package,
15911 error not with npm itself.
15911 error Tell the author that this fails on your system:
15911 error     yodoctor
15911 error You can get their info via:
15911 error     npm owner ls yo
15911 error There is likely additional logging output above.
15912 verbose exit [ 1, true ]
15913 verbose unbuild lib/node_modules/yo
15914 info preuninstall yo@1.4.6
15915 info uninstall yo@1.4.6
15916 verbose unbuild rmStuff yo@1.4.6 from /root/.nvm/versions/v0.12.2/lib/node_modules
15917 silly gentlyRm /root/.nvm/versions/v0.12.2/bin/yo is being gently removed
15918 silly gentlyRm verifying /root/.nvm/versions/v0.12.2 is an npm working directory
15919 silly gentlyRm containing path /root/.nvm/versions/v0.12.2 is under npm's control, in /root/.nvm/versions/v0.12.2
15920 silly gentlyRm deletion target /root/.nvm/versions/v0.12.2/bin/yo is under /root/.nvm/versions/v0.12.2
15921 verbose gentlyRm vacuuming from /root/.nvm/versions/v0.12.2/bin/yo up to /root/.nvm/versions/v0.12.2
15922 silly vacuum-fs removing /root/.nvm/versions/v0.12.2/bin/yo
15923 silly vacuum-fs quitting because other entries in /root/.nvm/versions/v0.12.2/bin
15924 info postuninstall yo@1.4.6
15925 silly gentlyRm /root/.nvm/versions/v0.12.2/lib/node_modules/yo is being purged from base /root/.nvm/versions/v0.12.2
15926 verbose gentlyRm don't care about contents; nuking /root/.nvm/versions/v0.12.2/lib/node_modules/yo
15927 silly vacuum-fs purging /root/.nvm/versions/v0.12.2/lib/node_modules/yo
15928 silly vacuum-fs quitting because other entries in /root/.nvm/versions/v0.12.2/lib/node_modules

I also created an executable file yodoctor which only had an echo statement as a work around. It seemed to work for the install, however when I used yo, the error: 

/root/.nvm/versions/v0.12.2/lib/node_modules/yo/node_modules/configstore/index.js:56
                                throw err;
                                      ^
Error: EACCES, permission denied '/root/.config/configstore/insight-yo.yml'
You don't have access to this file.

was displayed. The directory /root/.config etc does not exists.

Mike

**Comment by SBoudrias** [comment]
> Error: EACCES, permission denied '/root/.config/configstore/insight-yo.yml'

You can google it.

**Comment by ms-clovis** [comment]
Simon,
     Thank you for getting back to me so quickly. I am unsure if I 
explained the situation well. Two quick things. You should be aware that 
npm install yo -g does not work in the situation I described. The error 
message from npm said to notify the yeoman //committers of the issue. 
 From google I found the workaround of making an executable file named 
yodoctor in the path. This workaround was found within two email chains 
on the yeoman issues that had both been closed because they (the raised 
issues) pointed at each other. In both threads it was hard to see if any 
work to fix the issue had been accomplished. The next error (below) was 
what I received when using yo. I understand user permissions and chown 
and chmod. From the error:   permission denied 
'/root/.config/configstore/insight-yo.yml, Note that other than /root, 
the rest of the path (.config/ .... ) does not exist.

Thought you should know,

Mike
