### ISSUE TITLE
Yeoman v 0.19+ seems to break mkdir and copy methods

### ISSUE THREAD

**Issue by xtianus79** [yeoman/yeoman#1498]
I keep getting mkdir is deprecated. Mkdrip module instead.  I also have broken copy directives now.  

https://github.com/xtianus79/generator-aspnet

**Comment by SBoudrias** [comment]
Yes.

No more `this.mkdir`. Use `require('mkdirp')` if you need to create a directory, but directories are automatically created when you write a file into them, so chances are you don't need them.

For your copy directive, my guess is that you're using `_.something()` inside your templates files. This is not valid anymore. Pass lodash manually if you wish to use it in a template. Also, it might be worthwhile to update these methods to use our new file system helpers: http://yeoman.io/authoring/file-system.html

**Comment by xtianus79** [comment]
Does the require('mkdirp')  require any any other var directive?

**Comment by SBoudrias** [comment]
Well, all like usual node.js, I was pointing you need to require an external module.

But please read the documentation, it'll help you.

**Comment by xtianus79** [comment]
how does that help? I don't see any mkdirp anywhere on that page?  How can you require something and not provide documentation on how to use it?  I have gone to mkdri npm and it says to install it but necessarily how to use it in various contexts...

**Comment by SBoudrias** [comment]
https://www.npmjs.com/package/mkdirp

**Comment by xtianus79** [comment]
i've tried installing that dependency and running it but to no avail. still gives the error.  can you post something with better instructions on installing the dependency and then running it within an app to do simple things like mkdir, which you did above, and copy a folder and contents like the example I gave above.  I think that would help everyone out.

**Comment by SBoudrias** [comment]
just replace `this.mkdir()` with `mkdirp()`. It's the same signature and all.

And of course, require mkdirp before trying to use it.

**Comment by xtianus79** [comment]
@SBoudrias I am using at this moment yeoman gen .18.10 and it lists mkdirp as one of it's modules.  However when changing my top line of code to 
var mkdirp = require('mkdirp');

and thus use your example I get the following error. 

cannont find module mkdirp module.js 388

**Comment by SBoudrias** [comment]
You need to add this module to your `package.json` file.

I don't want to be an ass here, so don't take this badly. But this is basic node.js, if you don't understand how the language or the platform work, you should take time to learn it. Github is a tool to track issues with system, it's not a help/support forum.

If you have further questions about Node.js and the way it works you can't figure out, StackOverflow is going to be more helpful to you.

**Comment by xtianus79** [comment]
I'm not taking anything badly so don't worry... I am kind of learning backwards here so that is my fault.  However, with that said, this is a large breaking change and perhaps a little more hand holding or documentation is warranted.  I can't believe that i am going to be the only one here that runs into this problem.  If I am I guess my bad.  But if not then perhaps I might be correct in my inquiry here.  

I will look more into it.  I will say that after I get this working I believe I am going to have the same copy issue so.  if you don't mind I would like to ask you about that to get it straightened out. 

Hopefully this will be a help to someone else.

**Comment by xtianus79** [comment]
@SBoudrias I am an idiot... I realized what you were saying and yes that works perfectly.  sorry about that.  like I said I was trying 10 different things at once and it was a cluster.  

With that said... I want to go out on a limb here and say that I need these two dependencies installed??? https://github.com/sboudrias/mem-fs-editor

lol promise last queston

**Comment by SBoudrias** [comment]
Nope, you don't need these.

**Comment by xtianus79** [comment]
not for this.src.copy?  that was the other copy issue i had.

**Comment by SBoudrias** [comment]
Modules in Node.js are not magical. If you don't use the value they return, then you don't need them.

**Comment by xtianus79** [comment]
lol i know you're hating me but I am almost there.  Microsoft's aspnet omnisharp generator is the same exact code I am trying to fix so your efforts are not without purpose.  

util.inherits(Generator, yeoman.generators.Base);

    Generator.prototype.generateStandardFile = function(sourceFile, targetFile){
       this.log('You called the aspnet subgenerator with the arg ' + sourceFile);

      this.src.copy(sourceFile, targetFile);

      this.log(targetFile + ' created.')
    }

this code is throwing me the src and dest are depracated... I am trying to fix that now.

**Comment by SBoudrias** [comment]
Change `this.src.copy(sourceFile, targetFile);`

to

```js
this.fs.copy(
  this.templatePath(sourceFile),
  this.destinationPath(targetFile)
)
```

If the source file need to be template processed, then use `this.fs.copyTpl` and pass the template context as an object in the 3rd argument.

**Comment by xtianus79** [comment]
@SBoudrias bam... that is what i thought... this is awesome because contextual information can be passed into the subgenerators for asp.net classes and packagejson file creation... 

quick question... is this baked into node hence when the dependency wasn't needed?

**Comment by SBoudrias** [comment]
No, that's part of our generator Base class (defined into `yeoman-generator` package)

**Comment by xtianus79** [comment]
my goodness as yeoman assert changed now too?  these are throwing off erros. 

       describe('aspnet - Empty Application', function () {

         util.goCreateApplication('empty', 'emptyTest');

          describe('Checking directories', function () {
             it('Application directory created', function () {
              assert.file('emptyTest/');
          });
      });

      var files = ['emptyTest/project.json', 'emptyTest/Startup.cs'];
      describe('Checking files', function () {
          for (i = 0; i < files.length; i++) {
              util.filesCheck(files[i]);
          }
      });

      });

**Comment by SBoudrias** [comment]
Nope, these are the same ATM.

**Comment by xtianus79** [comment]
I am getting the before all hooks error and the type error... I can't figure what is causing that... 


  1) "before all" hook

aspnet - Console Application
  2) "before all" hook

aspnet - Unit Test Application
  3) "before all" hook

aspnet - Web Application w/gulp
  4) "before all" hook

aspnet - Web Application w/o gulp
  5) "before all" hook

aspnet - Web Application
  6) "before all" hook

aspnet - Starter Web App - Foundation 5
  7) "before all" hook

aspnet - Web API Application
  8) "before all" hook

aspnet - Nancy Application
  9) "before all" hook


18 passing (804ms)
9 failing

1) aspnet - Class Library "before all" hook:
   TypeError: undefined is not a function


2) aspnet - Console Application "before all" hook:
   TypeError: undefined is not a function

**Comment by SBoudrias** [comment]
See https://github.com/yeoman/generator#debugging

you'll see where your process stop and where you have errors.

**Comment by xtianus79** [comment]
the generator works though with no problems the only thing I did was update the yeoman and the only other thing I possibly did was change my section of the generator to that mkdirp and the one file for the subgenerators and the subgent test works fine

**Comment by xtianus79** [comment]
I don't know what it is but there is something about new generator that is breaking this script... 
https://github.com/xtianus79/generator-aspnet/blob/master/script-base.js

     lines (20 sloc)  0.806 kb
'use strict';
var util = require('util');
var path = require('path');
var yeoman = require('yeoman-generator');
var chalk = require('chalk');

var NamedGenerator = module.exports = function NamedGenerator() {
    yeoman.generators.NamedBase.apply(this, arguments);

    var sourceRoot = '/templates/';
    this.sourceRoot(path.join(__dirname, sourceRoot));
};

util.inherits(NamedGenerator, yeoman.generators.NamedBase);

NamedGenerator.prototype.generateTemplateFile = function (templateFile, targetFile, templateData) {
    this.log('You called the aspnet subgenerator with the arg ' + this.name);

    if (templateData !== null) {
        this.template(templateFile, targetFile, templateData);
    } else {
        this.template(templateFile, targetFile);
    }

    this.log(targetFile + ' created.')
}

**Comment by SBoudrias** [comment]
This is a deprecation release. It is expected to have stuff break.

**Comment by xtianus79** [comment]
ok... i will keep an eye out on it... The generator works fine but the test won't work at all... the funny thing is the subgenerator fix works and the test for that works as well.  

thanks for your help.

**Comment by SBoudrias** [comment]
I guess you're running into this issue https://github.com/yeoman/generator/issues/787

**Comment by xtianus79** [comment]
yes that could be it but I am unfamiliar with the run context is or does.  

Wanted to ask you about the copytpl.  I am assuming you could write a binding function to prompt the user for a question(s) that will then be copied out to a file.  would this be possible with the copytpl?
