### ISSUE TITLE
yeoman doesn't work in ubuntu

### ISSUE THREAD

**Issue by angryhipster** [yeoman/yeoman#1501]
no way to deal with yeoman in ubuntu 14.04. i have installed yeoman by special routine but after generator still do not work. 
for example i installed webapp with npm install -g generator-webapp
and all seems ok
but when i try to launch "Error webapp 
You don't seem to have a generator with the name webapp installed."

**Comment by SBoudrias** [comment]
run `yo doctor`

**Comment by angryhipster** [comment]
Running sanity checks on your system

✔ No .bowerrc file in home directory
✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ No .yo-rc.json file in home directory

Everything looks all right!

**Comment by SBoudrias** [comment]
Make sure you don't have multiple npm installed and that you didn't run anything with sudo

**Comment by angryhipster** [comment]
I don't know how to install multiple npm, as i try to install npm using Ubunu instruction. I used commands with sudo as it was recommended in installation instruction

**Comment by Munter** [comment]
That's your problem. I recommend uninstalling node again and installing it in user space using [nvm](https://github.com/creationix/nvm)
