### ISSUE TITLE
I am always getting a 404 error when serving my production files

### ISSUE THREAD

**Issue by tvanesse** [yeoman/yeoman#1504]
I am not sure if this is the right place to report my problem because I have no idea whether it's a bug or a configuration issue. Anyway, I've opened [a ticket](http://stackoverflow.com/questions/30032048/yeoman-grunt-build-does-not-throw-any-warning-error-but-the-resulting-dist-is-no) on StackOverflow as well.

In short, my problem is that whenever I serve the output files of `grunt build` (or `grunt` or `grunt serve:dist`) of my angular project, I'm getting a 404 error in the console when I land on `index.html`. Namely

    Failed to load resource: the server responded with a status of 404 (Not Found).     http://localhost:9000/components/portal/portal.html
    Error: [$compile:tpload] Failed to load template: components/portal/portal.html

`portal.html` being one of my templates in dev. Is it normal that the minified project is still referring to resources such as `components/xxx`? Pardon my ignorance but I thought everything would be put in `dist/index.html`, `dist/scripts/*` and `dist/styles/*` after minification.

The log of `grunt build` does not display any warning/error message and `yo doctor` said that "Everything looks all right!".

I am running Ubuntu 14.04 - 64bit with Yeoman 1.4.6, though I believe my project was generated with 1.3.3. I used `generator-angular 0.10.0` in this project. Here is my [Gruntfile.js](https://gist.github.com/tvanesse/3138ddb851b92a2c3538#file-gruntfile-js).

Feel free to request more information in case I did not provide enough to diagnose the problem.

**Comment by sindresorhus** [comment]
Open an issue on the generator you used. This is the main issue tracker for centralized stuff.

https://github.com/yeoman/generator-angular/issues/new

**Comment by bhushanvaidya3** [comment]
I'm getting similar error with one of my views. No errors thrown after running grunt build command, but get this error when dist is pushed to github: 

Error: [$compile:tpload] Failed to load template: views/RFQ/managependingrfqs.html (HTTP status: 404 Not Found)

**Comment by jml6m** [comment]
Having similar problems as well. I'm using `grunt-html2js` and it is adding templates to the $templateCache. When building locally (source code present), I can access the files by the key used in $templateCache.

But when deploying to prod, removing source code and compiling everything into an app.js file, I get:

> Failed to load template: ../app/common/filename.html (HTTP status: 404 Not Found)

Where '../app/common/filename.html' is the key used for $templateCache

**Comment by tusharbhatta** [comment]
I'm having this issue, did you solve that..how ?

**Comment by jml6m** [comment]
@tusharbhatta If I remember correctly, I added a `url` entry to my options block, like so:

```javascript
ngtemplates: {
	options: {
		//Use filename only as templateCache key (stripping filename from path)
		url: function (url) {
			return url.replace(/^.*(\\|\/|\:)/, '');
		}
	}
}
```

That allowed me to pass filename only in directives, like so:

```javascript
.directive('dirTest', function () {
	return {
		restrict: 'E',
		templateUrl: 'dir-test.html',
		controller: 'TestCtrl'
	};
})
```
