### ISSUE TITLE
remove files with this.fs.delete

### ISSUE THREAD

**Issue by dzuluaga** [yeoman/yeoman#1505]
Hi there, I'm trying to remove files from a folder. However, nothing happens. Files are never removed. They can be removed though, if they exist under root folder. Am I missing anything?

```js
  removeDir : function() {
      this.fs.delete('./grunt/*.js'); //tried grunt/*js, grunt/**/*.js
  },
```

**Comment by kevva** [comment]
Try this:

```js
removeDir : function() {
  this.fs.delete('./grunt/**/*.js');
}
```

**Comment by SBoudrias** [comment]
> They can be removed though, if they exist under root folder.

What do you mean?

**Comment by dzuluaga** [comment]
Thanks, @kevva. It looks when the function executes in the default priority (#2), the files aren't been copied over yet, so no files are removed. However, when I move the removeDir function to the end priority (#1), it works fine. Is there a way to force the execution of a function within the default priority after another function has been executed? so when the files have been already copied.

```js
//#1 function as part of end priority - works as expected
module.exports = yeoman.generators.Base.extend({
  //...default priority
  end : { // end priority
    removeDir: function () {
        this.fs.delete('grunt/**/apigee-config.js');
    }
  }
});
```
```js
//#2 function as part of default priority - it doesn't remove files
module.exports = yeoman.generators.Base.extend({
    removeDir: function () {
        this.fs.delete('grunt/**/apigee-config.js');
  }
});
```

**Comment by dzuluaga** [comment]
@kevva and @SBoudrias I think somewhere along the lines of managing [Yeoman Grunfile](http://yeoman.io/authoring/gruntfile.html) should help me to figure this out. However, The one on the page doesn't provide an end-to-end example.
Any chance where I can find one? Thanks!

**Comment by SBoudrias** [comment]
> Is there a way to force the execution of a function within the default priority after another function has been executed?

No, when composing, your generators should be context agnostic. They should be standalone and not depends on each other. If you don't want to generate these files, instead of deleting them after creation, pass an option to the sub-generator to not generate them.
