### ISSUE TITLE
i am having issue here 

### ISSUE THREAD

**Issue by Uttammgr** [yeoman/yeoman#1507]
Amits-MacBook-Pro:~ Amit$ npm install -g yeoman
npm WARN deprecated yeoman@0.9.6: The Yeoman CLI is deprecated. See http://yeoman.io/migrate.html for more info.
npm ERR! fetch failed http://github.com/yeoman/generators/archive/0.9.5.tar.gz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 406
npm WARN excluding symbolic link test/fixtures/octocat-link.png -> octocat.png
npm ERR! fetch failed http://github.com/yeoman/generators/archive/0.9.5.tar.gz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 406
npm ERR! fetch failed http://github.com/yeoman/generators/archive/0.9.5.tar.gz
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "yeoman"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! fetch failed with status code 406
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Amit/npm-debug.log

**Comment by kevva** [comment]
> npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues

**Comment by SBoudrias** [comment]
Actually the relevant message is:

>  The Yeoman CLI is deprecated

Now you need to install `yo`: `npm -g install yo`.

Please see http://yeoman.io for up to date documentation.

**Comment by kevva** [comment]
Hah, I missed that.

**Comment by Uttammgr** [comment]
it doesn't pull the request from the git in my folder 
![screen shot 2015-05-13 at 1 17 23 pm](https://cloud.githubusercontent.com/assets/9637242/7605761/73552416-f972-11e4-8df8-db0e2124342d.png)

**Comment by SBoudrias** [comment]
What?

**Comment by Uttammgr** [comment]
i mean download the webapp to download bootstrap and sass 
now i am having this issue gosh got really bad day 

can any body have time for assisting me by team viewer session to fix this

![screen shot 2015-05-13 at 2 05 25 pm](https://cloud.githubusercontent.com/assets/9637242/7606539/4e91838e-f979-11e4-9857-a5272937d130.png)

**Comment by SBoudrias** [comment]
You need to add npm binary to your path. Please follow a guide on how to install npm and node.
