### ISSUE TITLE
Extended EJS Syntax in JSON files

### ISSUE THREAD

**Issue by akullpp** [yeoman/yeoman#1509]
I'm trying to use a simple for loop or conditional if in `package.json` during templating phase which results  in `TypeError`s. Is it possible to use the entire EJS syntax with yo?

Example:
```
"keywords": [
    <% keywords.forEach(function(keyword){ %>
      "<%= keyword %>"
    <% }) %>
  ],
```

**Comment by SBoudrias** [comment]
We only use EJS - like in raw EJS. Not sure where your type error is coming from, but you probably made a syntax error somewhere in your file.
