### ISSUE TITLE
Conflicting

### ISSUE THREAD

**Issue by markat1** [yeoman/yeoman#1510]
Hello

I get a conflict after i ran the command: 

yo angular StockDog

I dont know why its making a conflict with package.json, but I am hoping someone know this problem and how to fix it.

![image](https://cloud.githubusercontent.com/assets/8057282/7788023/b4e51c0a-0229-11e5-8b3f-7ccbbd79d750.png)

**Comment by sindresorhus** [comment]
You most likely already had a `package.json` file. Use StackOveflow for support questions.

**Comment by markat1** [comment]
where to be exact? I doesnt show anything :(

**Comment by arthurvr** [comment]
@markat1 It's a known issue: https://github.com/yeoman/generator-angular/issues/1071.

**Comment by markat1** [comment]
Maybe, but it perhaps hasnt been fixed. Sorry, I dont want to install an early version and I also get some problem with some ENOMEN (I dont know what it is)

![image](https://cloud.githubusercontent.com/assets/8057282/7788148/69e3b26a-022f-11e5-80ee-f68d9de0d24f.png)

**Comment by SBoudrias** [comment]
Looks like your process can't access the npm bin.

**Comment by markat1** [comment]
hmm ok, thank for answer.  I will look into that - Btw I'm using vagrant.
