### ISSUE TITLE
npm install failure on mac 10.10.3

### ISSUE THREAD

**Issue by JamesJosephFinn** [yeoman/yeoman#1511]
`npm install -g yo` returns:

```
/Users/jamesfinn/.node_modules_global/bin/yo -> /Users/jamesfinn/.node_modules_global/lib/node_modules/yo/lib/cli.js

> yo@1.4.6 postinstall /Users/jamesfinn/.node_modules_global/lib/node_modules/yo
> yodoctor

sh: yodoctor: command not found
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/Users/jamesfinn/.node_modules_global/bin/npm" "install" "-g" "yo"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! yo@1.4.6 postinstall: `yodoctor`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the yo@1.4.6 postinstall script 'yodoctor'.
npm ERR! This is most likely a problem with the yo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     yodoctor
npm ERR! You can get their info via:
npm ERR!     npm owner ls yo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jamesfinn/npm-debug.log
```

`npm-debug.log` can be viewed [here](https://gist.githubusercontent.com/JamesJosephFinn/0b50a91bee52bfd168f1/raw/npm-debug.log)

**Comment by JamesJosephFinn** [comment]
I've updated to npm v. 2.10.1, with the same result.

**Comment by febLey** [comment]
**Temporary fix**

Try to create a bash file in one of your PATH directories named **yodoctor** with the following contents
```
#!/bin/bash
yo doctor
```
Make the file executable with
```
chmod +x yodoctor
```
Restart your terminal and now you should be able to install yeoman.

**Comment by kevva** [comment]
https://github.com/yeoman/yo/issues/253 http://stackoverflow.com/questions/21211340/how-to-fix-yo-command-not-found-after-installing-yeoman

**Comment by JamesJosephFinn** [comment]
@kevva Walk me through this, please. I do not see how this is relevant. The problem is not with running `yo` — I can't **install** `yo` at all.

**Comment by kevva** [comment]
@JamesJosephFinn, the error output is the same.

**Comment by JamesJosephFinn** [comment]
Thanks for your time – I'm new here...

Are you saying I shouldn't have set this:
```
~/.node_modules_global/bin/npm
```

I did it to avoid `sudo`, and this is the first time I've had a problem.

**Comment by JamesJosephFinn** [comment]
I created a symlink:
```
ln -s /usr/local/bin/npm ~/.node_modules_global/bin/npm
```

...and added this to my `~/.bash_profile`:
```
export PATH="$HOME/.node_modules_global/bin:$PATH"
```

**Comment by JamesJosephFinn** [comment]
Fixed. My *no-sudo* hack was bad. I found my fix here via @sindresorhus 

https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md

Thanks guys. Yeoman running now! :smile:
