### ISSUE TITLE
Type in option is not working

### ISSUE THREAD

**Issue by dszymczuk** [yeoman/yeoman#1512]
Results of:

    yo --version && node -e "console.log(process.platform, process.versions)"

    1.4.7
    win32 { http_parser: '1.0',
      node: '0.10.33',
      v8: '3.14.5.9',
      ares: '1.9.0-DEV',
      uv: '0.10.29',
      zlib: '1.2.3',
      modules: '11',
      openssl: '1.0.1j' }

**This code:**

    this.argument('arg1', {
        type: String
    });
    console.log(this.arg1);

WORKS:

    $ yo szkolenieyeoman test

WORKS (show error):

    $ yo szkolenieyeoman 123

**This code:**

    this.option('opt1',{
        type: Number
    });
    console.log(this.options.opt1);

WORKS:

    $ yo szkolenieyeoman --opt1 123

THIS:

    $ yo szkolenieyeoman --opt1 test

show "test" on console but it shouldn't (type is number)

**Comment by SBoudrias** [comment]
Actually, open this issue on the relevant repository here: https://github.com/yeoman/generator/issues
