### ISSUE TITLE
Scaffolding an App, tutorial fix

### ISSUE THREAD

**Issue by bundgaard** [yeoman/yeoman#1514]
Hi,

Please see to fix this issue @ http://yeoman.io/codelab/scaffold-app.html, when going through your guide , you want us to select bootstrap, but the latest bootstrap bower install 3.3.5 would not contain the css files, and it contains only the LESS files, which I'm not quite familiar with, therefor my fix would be, don't select to use Bootstrap, install it afterwards using `bower install bootstrap#3.3.4` and then wiredep would work as expected.

Took me a long time to work around it.

Best 

David

**Comment by eddiemonge** [comment]
It should be working fine now.
