### ISSUE TITLE
Generator page doesn't load! JQuery not loading...

### ISSUE THREAD

**Issue by bostondevin** [yeoman/yeoman#1515]
You're generator page has been down for at least a week that i've noticed - http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js is coming up broken

You might not notice it unless you clear your cache. Please fix!

**Comment by arthurvr** [comment]
The generator page is broken indeed because yeoman-generator-list is down: https://github.com/yeoman/yeoman-generator-list/issues/17#issuecomment-115999419. Nothing to do with the Google CDN.

**Comment by bostondevin** [comment]
I still can't bring the page up on the website? You referenced a closed issue but i'm still unable to see the list of generators located at this URL: http://yeoman.io/generators

**Comment by arthurvr** [comment]
@bostondevin works for me. Anything in the console?

**Comment by bostondevin** [comment]
Strange! Try clearing out your cache and then refreshing maybe? I'm getting this:

GET http://fonts.googleapis.com/css?family=Roboto+Slab:400,700|Roboto:400,700,700italic,400italic net::ERR_EMPTY_RESPONSE
yeoman.io/:29 GET http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js net::ERR_EMPTY_RESPONSE
scripts.a84d.js:1 Uncaught ReferenceError: jQuery is not defined(anonymous function) @ scripts.a84d.js:1
(index):30 GET http://www.google-analytics.com/ga.js net::ERR_EMPTY_RESPONSE

**Comment by bostondevin** [comment]
I'm getting an empty response when I go to this URL: http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js

**Comment by arthurvr** [comment]
I can't repro.

> I'm getting an empty response when I go to this URL

You seem to be unable to connect to the google CDN as well as google fonts. That's not a yeoman.io issue.
