### ISSUE TITLE
Fatal Error: Unable to find gruntfile

### ISSUE THREAD

**Issue by celticslegends** [yeoman/yeoman#1516]
I have made it to Step 5 of the Scaffold web app with Yeoman (http://yeoman.io/codelab/preview-inbrowser.html). I'm a beginner when it comes to programming and have been teaching myself. I have been able to use Terminal on my Mac and added in all of the necessary tools needed to do this. I have created a directory on Microsoft Visual for the mytodo app, but every time I try to create a local server, the Terminal is unable to locate the grunt file. I have tried everything. Looking in the code on visual, everything seems to be in order. I even tried typing in some other code, but to no avail. It keeps saying Fatal Error.

If anyone can help me with this I would greatly appreciate it. I have a feeling it is something very simple and I just need to make a simple adjustment. I see myself in the next 6 months-1 year becoming a professional programmer. It will be one hurdle after another. Thanks!

**Comment by addyosmani** [comment]
Could you confirm you're sure the Gruntfile.js is present in the directory you're working in?

**Comment by celticslegends** [comment]
Yes, Gruntfile.js is present in the microsoft visual file I have. I have attached a screenshot so you can see it. 
![screen shot 2015-06-28 at 10 11 38 am](https://cloud.githubusercontent.com/assets/13083202/8396863/1e0b1832-1d7e-11e5-9ee1-b03716e1c618.png)

**Comment by celticslegends** [comment]
Did you receive my online message about the Gruntfile issue I am having?

Matthew

**Comment by arthurvr** [comment]
> Terminal is unable to locate the grunt file. 

Can you make sure you're working in the right directory?

I'm going to close this as this is eighter a Grunt issue, an issue with the generator you're using or very likely just a support question.

> Did you receive my online message about the Gruntfile issue I am having?

@celticslegends We did. No need to start doing that kind of comments after 2 days. We're all busy ;)
