### ISSUE TITLE
Warning: Task "karma" not found. Use --force to continue.

### ISSUE THREAD

**Issue by houmanka** [yeoman/yeoman#1517]
Sorry guys, I searched internet inside out. I have not choice but to ask in here/

I have installed Yeoman all done with no issue. When I ran grunt I got this error `Warning: Task "karma" not found. Use --force to continue.`

Can you please shed some lights on this? Thanks

**Comment by SBoudrias** [comment]
Open this issue on the yeoman generator you're using.
