### ISSUE TITLE
Yeoman - webapp with grunt-php, how to configure gruntfile.js?

### ISSUE THREAD

**Issue by chriscodeweb** [yeoman/yeoman#1518]
Hello, I am a big fan of the webapp generator. I want to persuade my work to use it as well, but they also work with some basic php files. So I am trying to integrate grunt-php with yo webapp.
But I don't get it to work and I have spend lot's of hours now. Does anyone now how to configure the gruntfile.js to make grunt-php work? 

And is is perhaps possible to generate a php webapp version? That would be great!

Thanks in advance,

Chris.

**Comment by arthurvr** [comment]
Please don't use our bug tracker for support questions. You can always open an issue at the [generator-webapp](https://github.com/yeoman/generator-webapp/issues) bug tracker asking for a recipe, although, it should be fairly easy.

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/yeoman
Paste in the link to the question here so others can follow ;)
