### ISSUE TITLE
Welcome Arthur Verschaeve to the Yeoman team

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/yeoman#1519]
For a while now @arthurvr have been lurking around our Yeoman repositories. He've been providing invaluable feedback, help and code to our community.

Faced with such devotion and involvement, we have no choice but to offer him a place on our core team!

If you so wish, then we're only asking from you to send 2 PR:

 - [x] 1. Adding yourself to the [yeoman.io homepage](http://yeoman.io)
 - [x] 2. Adding yourself to the core team list on the `yeoman/yeoman` repository

Welcome!

**Comment by arthurvr** [comment]
Yay! :tada:

**Comment by sindresorhus** [comment]
:+1: Well deserved! Welcome :) :tada:

![od3vvoq](https://cloud.githubusercontent.com/assets/170270/8594506/9821a282-2641-11e5-974b-ea6416e00d64.gif)

**Comment by eddiemonge** [comment]
:+1: :birthday:

**Comment by addyosmani** [comment]
Welcome to the team, @arthurvr! :tada:

**Comment by ragingwind** [comment]
한영! Welcome! :tada:

**Comment by phanan** [comment]
Oh wow. Way to go @arthurvr!

**Comment by zckrs** [comment]
:clap: :clap: :clap: @arthurvr

**Comment by kevva** [comment]
Welcome :).

**Comment by hemanth** [comment]
Welcome @arthurvr :clap:  :smiley_cat:
