### ISSUE TITLE
Documentation generator for users

### ISSUE THREAD

**Issue by addyosmani** [yeoman/yeoman#152]
A potential user today asked if Yeoman plans on supporting a documentation generator such as Docco. 

I'm not sure whether or not this is a little too much to try squeezing in for the first version, but I found the below and thought we could at least discuss whether we want to give people a docs generator of some sort.

https://github.com/DavidSouther/grunt-docco

**Comment by georgschlenkhoff** [comment]
check out https://github.com/kengz/dokker
