### ISSUE TITLE
Generator pages down

### ISSUE THREAD

**Issue by bsitruk** [yeoman/yeoman#1528]
Failed to load resource: the server responded with a status of 503 (Service Unavailable)
(index):1 XMLHttpRequest cannot load https://yeoman-generator-list.herokuapp.com/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://yeoman.io' is therefore not allowed access. The response had HTTP status code 503.

**Comment by SBoudrias** [comment]
Fixed.
