### ISSUE TITLE
Loop priority issue - running prompts after bower install

### ISSUE THREAD

**Issue by lazabogdan** [yeoman/yeoman#1529]
I'm working on a generator which is supposed to:

1. Ask the user for a couple of bower package names
2. The generator validates the package names via prompt validate running async and using bower's API to fetch info for each package.
3. Install the bower dependencies supplied by the user
4. Prompts the user to select some files from the installed packages and then further process those files in other steps.

Each step works properly on it's own, but the problem is I can't get it working together in that specific order.

Would appreciate any ideas on this.

Thank you.

**Comment by SBoudrias** [comment]
Questions are better asked on stackoverflow.

This seem like a JavaScript issue. Yeoman, Inquirer and Node.js all support such a flow. You need to orchestrate them so they wait for their previous task to be done.

You can see an async prompt example here: http://yeoman.io/authoring/user-interactions.html

**Comment by lazabogdan** [comment]
@SBoudrias Thanks for replying. I was experiencing some very weird behaviour but I managed to track the issue down to inquirer.

Please see https://github.com/SBoudrias/Inquirer.js/issues/263
