### ISSUE TITLE
Better generator extension mechanism and trusteeship system

### ISSUE THREAD

**Issue by rafaelrinaldi** [yeoman/yeoman#1533]
Let’s say I want to create a node module, I will search for a generator containing “node” and Yeoman will retrieve me tons of variations of the same thing. Essentially they have the same goal but everyone has their own personal choices.
Correct me if I’m wrong, but the way I see it today I cannot create a slightly different version of any existing generator without having to register it as a new generator on Yeoman’s registry. That means I will need a new unique name for my generator and we all know that naming things is hard and can be really frustrating sometimes.

What if we allow users to simply fork “canonical” generators, make their own modifications and use it without the need of publishing it to the registry? That would enable us to have a more clean and flexible workflow.

I also think that will be a huge improvement on the current “trusteeship system”, since all the variations will come from “canonical” generators.

The way I imagine this in action:

```sh
# The way it is today
$ npm install -g bower grunt-cli gulp

# With npm custom endpoints
$ npm install -g rafaelrinaldi/generator-node-module

# We could have a Yeoman command to handle that too
# That would resolve the endpoint assuming it’s a GitHub repository
$ yo import rafaelrinaldi/generator-node-module

# Allow full path for endpoints
$ yo import git@github.com:rafaelrinaldi/generator-node-module.git

# An example of a Bitbucket endpoint
$ yo import git@bitbucket.org:rafaelrinaldi/generator-node-module.git

# We could even allow zip files
$ yo import https://github.com/rafaelrinaldi/generator-node-module/archive/master.zip
```

I would love to hear your thoughts on this.

**Comment by SBoudrias** [comment]
I believe that'll come by itself with npm namespaces. They'll have `npm install @sboudrias/generator-node`, etc.

**Comment by sindresorhus** [comment]
Yes, a [scoped package](https://docs.npmjs.com/getting-started/scoped-packages) is the way to go. We should add this recommendation somewhere in the docs.

**Comment by rafaelrinaldi** [comment]
Yeah, this is something that definitely can be more clear on the documentation. Thanks for the answers, though. Nice to know this is somewhat already possible.

**Comment by sindresorhus** [comment]
Opened an issue so we don't forget: https://github.com/yeoman/yeoman.io/issues/518 ;)
