### ISSUE TITLE
Is there a way to prevent the base generator from getting called if I specify an invalid sub-generator name?

### ISSUE THREAD

**Issue by greymind** [yeoman/yeoman#1537]
Hey everyone!

Say I have a base generator `generator-supergen` and a sub-generator `supergen:alpha`.

If I erroneously type `yo supergen:beta`, the base generator gets called, which makes this command equivalent to `yo supergen`. This is not desirable behavior for me.

Is there a way to find out what the command line call was or something, so I can handle it in the base generator or something similar to that effect?

Thanks!
Balki

**Comment by SBoudrias** [comment]
This is a piece of legacy code that just stayed around up to now. I don't think anyone ever reported an issue like this so we never thought about fixing it.

That being said, there's nothing you can do on your side. It just should be fix on ours.

**Comment by SBoudrias** [comment]
Closing in favor of https://github.com/yeoman/environment/issues/48

**Comment by greymind** [comment]
Thanks! Looking forward to it so I can throw away my ugly process.argv[2] check ;)
