### ISSUE TITLE
503 error on heroku

### ISSUE THREAD

**Issue by ivanbportugal** [yeoman/yeoman#1541]
Hello,

Obviously you have an awesome project and I truly commend you for that. For whatever reason right now I am getting the following error when trying to view the list of generators. It appears that perhaps your heroku app is on a different domain?

`XMLHttpRequest cannot load https://yeoman-generator-list.herokuapp.com/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://yeoman.io' is therefore not allowed access. The response had HTTP status code 503.`

**Comment by ruyadorno** [comment]
Thanks @ivanbportugal, it has been reported already https://github.com/yeoman/yeoman.io/issues/531
