### ISSUE TITLE
Angular-ui-router is deleted automatically 

### ISSUE THREAD

**Issue by yogieputra8** [yeoman/yeoman#1542]
So, I do a basic project using yeoman. After I install it, I want to use Angular-ui-router, so I do ```bower install ui-router```. I injected ```<script src="bower_components/angular-ui-router/release/angular-ui-router.js"></script>``` in my index.html and do everything as explained in many tutorials. 
But the problem came when I do the ```grunt serve```, the ```<script src="bower_components/angular-ui-router/release/angular-ui-router.js"></script>``` which I was injected in index.html is being deleted automatically. I need that component. 
Can you guys help me how to fix this issue?

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/yeoman
Paste in the link to the question here so others can follow ;)
