### ISSUE TITLE
yeoman generator local to one project (eg not install it globally)

### ISSUE THREAD

**Issue by netei** [yeoman/yeoman#1544]
On the project I'm working on, we want to create a generator that is specific to that particular project.

I would like to know if it is somehow possible to run a generator without having to install it globally.

For example, given the following structure in folder `acme`:

```
├── etc
├── node_modules
├── src
├── generator-acme
└── test
```

and if you are currently in the folder `acme`, it would be great to be able to run `yo acme:command` without having to install generator-acme globally manually.

Does such a feature already exists ? If not, would you accept a pull request for that ?

**Comment by sindresorhus** [comment]
You can `npm link` the generator.

**Comment by netei** [comment]
Ok, that should indeed work fine. Thanks !
