### ISSUE TITLE
build  lssue

### ISSUE THREAD

**Issue by leke2015** [yeoman/yeoman#1547]
I created a couple of html pages in the project
Why grunt build several html pages that are not generated in dist directory

**Comment by sindresorhus** [comment]
You included absolutely no actionable information in this issue.

Try asking on StackOverflow and included a lot more info. Which generator you used, etc.

**Comment by leke2015** [comment]
You can not solve this problem?
My code in https://coding.net/u/Rockts/p/tsflea.com/git/tree/dev/
Can you help me find it?
