### ISSUE TITLE
yo wordpress 

### ISSUE THREAD

**Issue by leke2015** [yeoman/yeoman#1548]
yo yo-wordpress 

How to run a web application?

**Comment by sindresorhus** [comment]
Please stop asking support questions here. This is not a support forum.

Gonna [repeat](https://github.com/yeoman/yeoman/issues/1547#issuecomment-142504613) myself:

> Try asking on StackOverflow and included a lot more info. Which generator you used, etc.

**Comment by leke2015** [comment]
ok, sorry
