### ISSUE TITLE
`yo doctor` just look up home dir

### ISSUE THREAD

**Issue by DenniJensen** [yeoman/yeoman#1549]
Hey,

I crashed to an issue where have to find out that yeoman did not scaffold in my current dir.
I put my in `$HOME/code`. In this directory I started a scaffold by mistake, so an `.yo-rc.json` was created. 

`yo doctor` did not show me this in any kind, then I was in a dir like `$HOME/code/myApplication`. It was a stupid mistake on my side, but it could be useful if yeoman can tell me, that I have a yo-file in one of my parent directories to remove any surprise.

**Comment by sindresorhus** [comment]
Can you open this here instead: https://github.com/yeoman/doctor
