### ISSUE TITLE
yeoman won't install! Two different types of errors.

### ISSUE THREAD

**Issue by Elliot87** [yeoman/yeoman#1550]
Hello, I am trying to get yeoman installed, and it just doesn't want to happen for me. I have been at it for 2-3 days now trying to get this working, I would much prefer to fix my mistakes myself and learn from them, but I'm simply out of ideas here!

node version: 4.1.2
npm version: 3.3.7
git version: 2.6.0.windows.1
OS: Windows 7 pro

The issue started off when I originally installed yeoman with an older version of npm....it was 2.4 I think? So still new enough to run yeoman, according to the documentation.....however at that time, I didn't know there was a manual process involved with updating npm, so I thought I was on the latest version. With the older version of npm though, yeoman itself seemed like it installed just fine, I didn't have any problems until i tried to download and use generators -- I tried a variety of generators, h5bp, gulp-bootstrap, gulp-bootstrap3, generator-bootstrap,  and google web starter kit, and all of them seemed to have the same problem, either a spam of ECONNRESET errors that turned into a 12.3k line debug log, or it would install but give a bunch of dependency + deprecation warnings. It seemed to install the necessary files for the generator, but also seemed to install a bunch of other stuff that I don't think was necessary for the generator I had downloaded, the nodes-modules directory contained dozens of subdirectories, way more than listed in the package.json, and when trying to use gulp it gave a bunch more errors.....

It wasn't until today that I found out that I wasn't on the latest npm version, and installed the npm-windows-upgrade module to get on the right version.....but my problem now is I can't even seem to get past the install. Either I get the same old spam of ECONNRESET with a ridiculously huge npm-debug.log....https://gist.github.com/Elliot87/c6bb50b6deca3a895d98 -- brace yourself, its just short of 16,000 lines...

........Or it will appear to be installing smoothly, and then at the very end it throws `npm ERR! code 1 ` but appears to still install , and create a yo directory in C:\users\elliot\appdata\roaming\npm\node_modules, but when I try to use the `yo` command, it gives me this error:

    module.js:338
    throw err;
    ^

    Error Cannot find module  'C:\Program Files\nodejs\node_modules\yo\lib\cli.js'
      at Function.Module._resolveFilename (module.js:336:15)
      at Function.Module_load (module.js:286:25)
      at Function.Module.runMain (module.js:475:10)
      at startup (node.js:118:18)
      at node.js:952:3

You'll have to forgive me because I'm a bit new to npm, however in the past few weeks I have been learning how to use the all of the various modules and everything was a breeze up until trying to use yeoman. I must have made a rookie mistake somewhere, but I have been following the yeoman codelab  word for word and still having problems. I have been trying for days to get this running now and I'm at the point where I don't know what to do next. :(

Update -- I decided to just try using cmder, since it says it's the preferred input method for yeoman, I was originally trying to avoid adding any additional terminals that aren't 100% required because I didn't want to add any confusion in my learning process--  I was originally confused as to which terminal to run each module with, but so far git bash has been working for everything else npm related....I had tried to install yo in powershell, cmd.exe, git bash, git cmd already, and I have now tried with cmder as well, which still did not work, however it gave me a more clear error message. It looks like the install is failing at the `node postinstall` point because when it gets there it says : 

    'node' is recognized as an internal or external command, operable program or batch file.
    npm WARN install:spawn-sync@1.0.13 spawn-sync@1.0.13 postinstall `node postinstall`
    npm WARN install:spawn-sync@1.0.13 Exit status 1
    C:\Program Files\nodejs
    ------Empty

    npm ERR! code 1

using the `yo` command returns the same error as before.

**Comment by sindresorhus** [comment]
Seems like you're having some network problems when installing. From error log:

> 7735 error network read ECONNRESET
7735 error network This is most likely not a problem with npm itself
7735 error network and is related to network connectivity.
7735 error network In most cases you are behind a proxy or have bad network settings.
7735 error network
7735 error network If you are behind a proxy, please make sure that the
7735 error network 'proxy' config is set properly.  See: 'npm help config'

You're not having problems with Yeoman. You're having problems with `npm`. Installing is done with `npm` and out of our hands. You can try getting install support at https://github.com/npm/npm/issues
