### ISSUE TITLE
Accidently published a generator with copy pasted repository in package.json

### ISSUE THREAD

**Issue by kornosaurus** [yeoman/yeoman#1551]
I copy pasted the `'repository': 'yeoman/generator-angular'` from the angular generator to my package.json and the forgot about it. Later today i published my generator to npmjs and this lead to that the angular generator on http://yeoman.io/generators/ had gotten the name of my new generator.. I have unpublished, deleted tag on github repo, then republished the generator with correct package.json..

http://yeoman.io/generators/ hasn't been update yet and still has my generator as name.. Am i missing something or is this a cache?

**Comment by kornosaurus** [comment]
Seems to be fixed

**Comment by SBoudrias** [comment]
We're caching the results for one hour I believe. So there's a slight delay in the update.
