### ISSUE TITLE
including packages in the build/ compilation of project

### ISSUE THREAD

**Issue by karneaud** [yeoman/yeoman#1554]
I have a installed *--save* a bower_component 'angular-iscroll' which also installed its dependency 'iscroll' however, during compiling the bower_component 'iscroll' isn't getting included into the build process despite being present.

How do I configure it to be included into the build?

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/yeoman
Paste in the link to the question here so others can follow ;)

**Comment by sindresorhus** [comment]
Make sure to include what generator you used.
