### ISSUE TITLE
Yeoman checkboxes not working (spacebar does nothing) on Windows 10 cmd

### ISSUE THREAD

**Issue by freeseus** [yeoman/yeoman#1559]
Spacebar doesn't seem to do anything here:

![spacebarbroke](https://cloud.githubusercontent.com/assets/11297204/11045652/ba295a12-86f6-11e5-9f2e-02c8387c088c.png)

Reinstalled Windows 10, then git, nodejs
Then
npm install yo grunt-cli bower gulp -g
npm install generator-webapp -g

then made a project folder

npm install yo
I get the picture above, enter will install all 3 of those options, but spacebar does nothing except add spaces AFTER "modernizr." Also, typing other letters will write the letters after the word "modernizr."

Thoughts?

**Comment by freeseus** [comment]
As an fyi, this screenshot is from my work computer running win7, my win10 machine is a laptop next to it. The issue is only on my Win10 laptop.

**Comment by SBoudrias** [comment]
See https://github.com/yeoman/yo/issues/360 - basically it's a Node bug with Windows. A fix have just been merged in Node master, so hopefully in the next couple day it'll be released.

You can launch webapp from `yo` for the time being.
