### ISSUE TITLE
How to define a test spec using .withGenerators()

### ISSUE THREAD

**Issue by canercandan** [yeoman/yeoman#1560]
I encounter an issue with my yeoman generator test spec, since it uses other generators (cf. `node:readme`), I'd used `.withGenerators()` with a dummy generator using the same namespace but when I run the test it still go through the `node:readme` generator.

Is that the way it should go ? I thought it should replace the `node:readme` by the mocked one

Thanks.

**Comment by SBoudrias** [comment]
I'm pretty sure you're running into https://github.com/yeoman/generator/issues/704

**Comment by canercandan** [comment]
Thanks.
