### ISSUE TITLE
Tip: How to use the USAGE file

### ISSUE THREAD

**Issue by pacav69** [yeoman/yeoman#1562]
# Tip: Using the USAGE file in your generator
Sometimes there are requirements on the usage of generator especially when you have sub-generators, sure you can look up the readme.md file but it would be better if you could use the command line to find out the syntax of how to use a particular generator or sub-generators.

- Filename:  USAGE 
- File location: [generator_name]\app

## Help
Information on how to use sub-generators can be found by using: 

	yo  [generator_name] --help

### Sample contents of USAGE file

Description:
    Creates Joomla 2.5 and 3.0 files

Options:
    --skip-install: Skips the automatic execution of `bower` and `npm`
      after scaffolding has finished.
    --s: alias --skip-install

Example:
    yo joomla-spc [--skip-install] [--silent]

sub-generators:    
these can be called after the scaffold has been created

- model: yo joomla-spc:model "model-name"
- view: yo joomla-spc:view "view-name" 
- controller: yo joomla-spc:controller "controller-name"
- helper: yo joomla-spc:helper "helper-name"

## When the user types:

	yo joomla-spc --help

### The following will appear:

Usage:
  yo joomla-spc:app [options]

Options:
  -h,   --help  # Print generator's options and usage  Default: false

Description:
    Creates Joomla 2.5 and 3.0 files

Options:
    --skip-install: Skips the automatic execution of `bower` and `npm`
      after scaffolding has finished.
    --s: alias --skip-install

Example:
    yo joomla-spc [--skip-install] [--silent]

sub-generators:
these can be called after the scaffold has been created

    model: yo joomla-spc:model "model-name"
    view: yo joomla-spc:view "view-name"
    controller: yo joomla-spc:controller "controller-name"
    helper: yo joomla-spc:helper "helper-name"

Then the user can copy and paste the sub-generator text to execute the command.

**Comment by eddiemonge** [comment]
I don't really know what you are asking here. That's what help already outputs if you set your generator up correctly. A USAGE file is not required.

**Comment by pacav69** [comment]
As i stated in the opening paragraph it is useful for generators that have sub-generators if the USAGE file is included with the generator. I have seen in some generators that have information in the readme.md file and the information is not included when the user types yo  [generator_name] --help. 
i was poinring out this little snipper of information is not well documented and would be good to have included in the yo generator-generator app.

**Comment by eddiemonge** [comment]
As you said,

> information is not included when the user types yo [generator_name] --help

that means its a bug in that generator and should be fixed. You could send a PR to help them out. Other than that, I'm still not really sure what you are asking for. Do you want the --help info to be in two places, meaning they will both likely get out of date? Or do you want the USAGE file to be used instead of code in the generator itself?
