### ISSUE TITLE
Yeoman generator froze iCloud Drive

### ISSUE THREAD

**Issue by warrenonline** [yeoman/yeoman#1564]
This is probably an iCloud issue, but Im adding it here as an FYI. I am currently learning how to run Yeoman and Gulp and used them together for the first time yesterday. I made a root folder in my iCloud Drive directory so it would sync and I could work on it remotely. I installed Yeoman via npm and generator-gulp-webapp. I used Terminal and navigated to my web app folder and ran "yo gulp-webapp". Yeoman did everything it was supposed to and scaffolded the web app. In my local iCloud Drive it looked like it worked perfectly. At the end of the build process iCloud Drive was completely stuck and would not up or download anything. My iCloud Drive continued to work on my iPad and the web. Apple Support was no help on the issue and I had to stop using iCloud Drive to get it to unlock. This deleted my local files and downloaded new copies from the remote iCloud Drive when I turned it back on. When the local files were back I ran the "yo gulp-webapp" again and it happened again. Yes I am that dumb but I didn't think the issue was Yeoman at the time.

Yeoman is the newest version and I am running OSX El Capitan. I don't have any error messages to offer as the local issue was overwritten when iCloud came back on. Running "brctl log --wait --shorten" in Terminal just showed iCloud Drive hanging and not moving any files. The Activity Monitor showed a process called "bird" using 96 to 99.2% of CPU while iCloud Drive was stuck. This "bird" is an iCloud process that went back to normal after I nuked the iCloud Drive. Hope this helps someone !

**Comment by eddiemonge** [comment]
I'm assuming this is either a OSX or iCould bug. Try doing something like `npm i generator-angular yo generator express grunt bower `, basically something that makes npm install a lot of files. It'll probably lock it up. This is not a Yeoman specific bug.
