### ISSUE TITLE
To pass nested prompt values in the test spec

### ISSUE THREAD

**Issue by canercandan** [yeoman/yeoman#1565]
I am not sure if this is a bad test spec design wrt yeoman test routines, but is there a way to pass nested prompt values in case we have subgenerators such as node:app that ask for inquier answers ? thanks

**Comment by sindresorhus** [comment]
https://github.com/yeoman/yeoman#support

**Comment by canercandan** [comment]
@sindresorhus sorry for my misunderstanding, where should I post this issue then ?

**Comment by SBoudrias** [comment]
@canercandan there's no way to specify prompt for sub-generators. Maybe open a feature request on yeoman/generator.

**Comment by canercandan** [comment]
@sindresorhus ok got it should be posted on yeoman/generator project, will know next time :+1: 

@SBoudrias no need to go further, I just read your intervention on https://github.com/yeoman/generator/issues/553 and I understand better the generators composition philosophy behind yeoman. As a suggestion, the documentation should highlights the usage of options for data passing between generators and sub-generators as the only way to go.

As far as I understood, the *:app should only be used if it corresponds to the end sub-generator used by the built generator otherwise if data passing is necessary while composing, the dev should turn to the non-*:app sub-generators that are not using inquirer prompts but instead options.
