### ISSUE TITLE
The `module.exports` problem

### ISSUE THREAD

**Issue by GantMan** [yeoman/yeoman#1567]
Currently, creating a generator relies on people implementing `module.exports` as stated in the documentation:  http://yeoman.io/authoring/index.html

For those of us moving towards Babel and ES6 this recently became a big problem with Babel 6.  There's just no clean/clear way to do this.  http://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default

As a good 8/20 rule we can keep Yeoman flexible with a secondary workflow which will easily work with simple conversion from ES6.

**Comment by sindresorhus** [comment]
Just use this plugin then: https://www.npmjs.com/package/babel-plugin-add-module-exports

**Comment by GantMan** [comment]
I had some trouble with that plugin.   Is it a bad idea to give us a clean solution that won't force all Yeoman users to go find a plugin?

**Comment by SBoudrias** [comment]
Yeah it is. Yeoman is a node tool. As such, we follow Node.js conventions.

If that's an issue, then it's an issue with Babel and they should fix it.

**Comment by GantMan** [comment]
:+1:
