### ISSUE TITLE
Doesn't find generators

### ISSUE THREAD

**Issue by semeano** [yeoman/yeoman#1570]
OS X 10.9.5
Node: 5.1.0
NPM: 3.3.12
Yeoman: 1.5.0

I've tried:
- "yo doctor" (everything is right)
- installing the generators from yeoman doesn't solve it
- "npm -g root" shows the path where the generators (and yeoman) are installed (globally)
- "echo $NODE_PATH" shows the path where the global packages are installed (/usr/local/lib/node_modules)
- I've already uninstalled yeoman and the generators, and installed again. Nothing. https://www.dropbox.com/s/klml05tjeulkh00/Screenshot%202015-11-24%2000.49.15.png?dl=0

Any other options?

PS: I've installed node using homebrew.

**Comment by SBoudrias** [comment]
What generator did you installed (`npm linked`)?

Also, make sure inside the node process, npm is still referring to your global npm (you might have multiple npm installed on your machine).

**Comment by semeano** [comment]
So, I've uninstalled node and made sure I didn't had any other node or npm installed.
Installed again using brew and this is what I got.

    semeano:~ semeano$ node -v
    v5.1.0
    semeano:~ semeano$ npm -v
    3.3.12
    semeano:~ semeano$ npm install -g yo
    /usr/local/bin/yo -> /usr/local/lib/node_modules/yo/lib/cli.js

    > yo@1.5.0 postinstall /usr/local/lib/node_modules/yo
    > yodoctor


    Yeoman Doctor
    Running sanity checks on your system

    ✔ Global configuration file is valid
    ✔ Node.js version
    ✔ No .bowerrc file in home directory
    ✔ No .yo-rc.json file in home directory
    ✔ npm version
    ✔ NODE_PATH matches the npm root

    Everything looks all right!
    /usr/local/lib
    `-- yo@1.5.0 
      +-- async@1.5.0 
      +-- chalk@1.1.1 
      | +-- ansi-styles@2.1.0 
      | +-- escape-string-regexp@1.0.3 
      | +-- has-ansi@2.0.0 
      | +-- strip-ansi@3.0.0 
      | `-- supports-color@2.0.0 
      +-- configstore@1.3.0 
      | +-- graceful-fs@4.1.2 
      | +-- mkdirp@0.5.1 
      | | `-- minimist@0.0.8 
      | +-- object-assign@4.0.1 
      | +-- os-tmpdir@1.0.1 
      | +-- osenv@0.1.3 
      | +-- uuid@2.0.1 
      | +-- write-file-atomic@1.1.3 
      | | `-- slide@1.1.6 
      | `-- xdg-basedir@2.0.0 
      +-- cross-spawn-async@2.0.0 
      | +-- lru-cache@2.7.1 
      | `-- which@1.2.0 
      |   `-- is-absolute@0.1.7 
      |     `-- is-relative@0.1.3 
      +-- figures@1.4.0 
      +-- fullname@2.1.0 
      | +-- npmconf@2.1.2 
      | | +-- config-chain@1.1.9 
      | | | `-- proto-list@1.2.4 
      | | +-- inherits@2.0.1 
      | | +-- ini@1.3.4 
      | | +-- nopt@3.0.6 
      | | | `-- abbrev@1.0.7 
      | | +-- once@1.3.3 
      | | | `-- wrappy@1.0.1 
      | | +-- semver@4.3.6 
      | | `-- uid-number@0.0.5 
      | +-- pify@2.3.0 
      | `-- pinkie-promise@2.0.0 
      |   `-- pinkie@2.0.1 
      +-- got@5.1.0 
      | +-- create-error-class@2.0.1 
      | | `-- capture-stack-trace@1.0.0 
      | +-- duplexify@3.4.2 
      | | +-- end-of-stream@1.0.0 
      | | `-- readable-stream@2.0.4 
      | |   +-- core-util-is@1.0.2 
      | |   +-- isarray@0.0.1 
      | |   +-- process-nextick-args@1.0.3 
      | |   +-- string_decoder@0.10.31 
      | |   `-- util-deprecate@1.0.2 
      | +-- is-plain-obj@1.1.0 
      | +-- is-redirect@1.0.0 
      | +-- is-stream@1.0.1 
      | +-- lowercase-keys@1.0.0 
      | +-- node-status-codes@1.0.0 
      | +-- parse-json@2.2.0 
      | | `-- error-ex@1.3.0 
      | |   `-- is-arrayish@0.2.1 
      | +-- pinkie-promise@1.0.0 
      | | `-- pinkie@1.0.0 
      | +-- read-all-stream@3.0.1 
      | | `-- pinkie-promise@1.0.0 
      | |   `-- pinkie@1.0.0 
      | +-- timed-out@2.0.0 
      | +-- unzip-response@1.0.0 
      | `-- url-parse-lax@1.0.0 
      |   `-- prepend-http@1.0.3 
      +-- humanize-string@1.0.1 
      | `-- decamelize@1.1.1 
      +-- inquirer@0.11.0 
      | +-- ansi-escapes@1.1.0 
      | +-- ansi-regex@2.0.0 
      | +-- cli-cursor@1.0.2 
      | | `-- restore-cursor@1.0.1 
      | |   `-- exit-hook@1.1.1 
      | +-- cli-width@1.1.0 
      | +-- readline2@1.0.1 
      | | +-- code-point-at@1.0.0 
      | | +-- is-fullwidth-code-point@1.0.0 
      | | `-- mute-stream@0.0.5 
      | +-- run-async@0.1.0 
      | +-- rx-lite@3.1.2 
      | `-- through@2.3.8 
      +-- insight@0.7.0 
      | +-- inquirer@0.10.1 
      | +-- lodash.debounce@3.1.1 
      | | `-- lodash._getnative@3.9.1 
      | +-- os-name@1.0.3 
      | | +-- osx-release@1.1.0 
      | | | `-- minimist@1.2.0 
      | | `-- win-release@1.1.1 
      | |   `-- semver@5.1.0 
      | +-- request@2.67.0 
      | | +-- aws-sign2@0.6.0 
      | | +-- bl@1.0.0 
      | | +-- caseless@0.11.0 
      | | +-- combined-stream@1.0.5 
      | | | `-- delayed-stream@1.0.0 
      | | +-- extend@3.0.0 
      | | +-- forever-agent@0.6.1 
      | | +-- form-data@1.0.0-rc3 
      | | +-- har-validator@2.0.2 
      | | | +-- commander@2.9.0 
      | | | | `-- graceful-readlink@1.0.1 
      | | | +-- is-my-json-valid@2.12.3 
      | | | | +-- generate-function@2.0.0 
      | | | | +-- generate-object-property@1.2.0 
      | | | | | `-- is-property@1.0.2 
      | | | | `-- jsonpointer@2.0.0 
      | | | `-- pinkie-promise@1.0.0 
      | | |   `-- pinkie@1.0.0 
      | | +-- hawk@3.1.2 
      | | | +-- boom@2.10.1 
      | | | +-- cryptiles@2.0.5 
      | | | +-- hoek@2.16.3 
      | | | `-- sntp@1.0.9 
      | | +-- http-signature@1.1.0 
      | | | +-- assert-plus@0.1.5 
      | | | +-- jsprim@1.2.2 
      | | | | +-- extsprintf@1.0.2 
      | | | | +-- json-schema@0.2.2 
      | | | | `-- verror@1.3.6 
      | | | `-- sshpk@1.7.0 
      | | |   +-- asn1@0.2.3 
      | | |   +-- assert-plus@0.2.0 
      | | |   +-- dashdash@1.10.1 
      | | |   +-- ecc-jsbn@0.1.1 
      | | |   +-- jodid25519@1.0.2 
      | | |   +-- jsbn@0.1.0 
      | | |   `-- tweetnacl@0.13.2 
      | | +-- is-typedarray@1.0.0 
      | | +-- isstream@0.1.2 
      | | +-- json-stringify-safe@5.0.1 
      | | +-- mime-types@2.1.7 
      | | | `-- mime-db@1.19.0 
      | | +-- node-uuid@1.4.7 
      | | +-- oauth-sign@0.8.0 
      | | +-- qs@5.2.0 
      | | +-- stringstream@0.0.5 
      | | `-- tunnel-agent@0.4.1 
      | `-- tough-cookie@2.2.1 
      +-- lodash@3.10.1 
      +-- meow@3.6.0 
      | +-- camelcase-keys@2.0.0 
      | | +-- camelcase@2.0.1 
      | | `-- map-obj@1.0.1 
      | +-- loud-rejection@1.2.0 
      | | `-- signal-exit@2.1.2 
      | +-- minimist@1.2.0 
      | +-- normalize-package-data@2.3.5 
      | | +-- hosted-git-info@2.1.4 
      | | +-- is-builtin-module@1.0.0 
      | | | `-- builtin-modules@1.1.0 
      | | `-- validate-npm-package-license@3.0.1 
      | |   +-- spdx-correct@1.0.2 
      | |   | `-- spdx-license-ids@1.1.0 
      | |   `-- spdx-expression-parse@1.0.1 
      | |     `-- spdx-exceptions@1.0.4 
      | +-- redent@1.0.0 
      | | +-- indent-string@2.1.0 
      | | `-- strip-indent@1.0.1 
      | `-- trim-newlines@1.0.0 
      +-- npm-keyword@4.2.0 
      | `-- registry-url@3.0.3 
      +-- opn@3.0.3 
      +-- package-json@2.2.1 
      | `-- rc@1.1.5 
      |   +-- deep-extend@0.4.0 
      |   +-- minimist@1.2.0 
      |   `-- strip-json-comments@1.0.4 
      +-- read-pkg-up@1.0.1 
      | +-- find-up@1.1.0 
      | | `-- path-exists@2.1.0 
      | `-- read-pkg@1.1.0 
      |   +-- load-json-file@1.1.0 
      |   | `-- strip-bom@2.0.0 
      |   |   `-- is-utf8@0.2.0 
      |   `-- path-type@1.1.0 
      +-- repeating@2.0.0 
      | `-- is-finite@1.0.1 
      |   `-- number-is-nan@1.0.0 
      +-- root-check@1.0.0 
      | +-- downgrade-root@1.1.0 
      | | +-- default-uid@1.0.0 
      | | `-- is-root@1.0.0 
      | `-- sudo-block@1.2.0 
      |   `-- is-docker@1.0.0 
      +-- sort-on@1.2.2 
      | +-- arrify@1.0.0 
      | `-- dot-prop@2.2.0 
      +-- string-length@1.0.1 
      +-- titleize@1.0.0 
      +-- update-notifier@0.5.0 
      | +-- is-npm@1.0.0 
      | +-- latest-version@1.0.1 
      | | `-- package-json@1.2.0 
      | |   `-- got@3.3.1 
      | |     +-- infinity-agent@2.0.3 
      | |     +-- nested-error-stacks@1.0.2 
      | |     `-- object-assign@3.0.0 
      | +-- repeating@1.1.3 
      | `-- semver-diff@2.1.0 
      |   `-- semver@5.1.0 
      +-- user-home@2.0.0 
      | `-- os-homedir@1.0.1 
      +-- yeoman-character@1.1.0 
      | `-- supports-color@3.1.2 
      |   `-- has-flag@1.0.0 
      +-- yeoman-doctor@2.0.0 
      | +-- bin-version-check@2.1.0 
      | | +-- bin-version@1.0.4 
      | | | `-- find-versions@1.2.1 
      | | |   `-- semver-regex@1.0.0 
      | | +-- minimist@1.2.0 
      | | `-- semver-truncate@1.1.0 
      | |   `-- semver@5.1.0 
      | +-- each-async@1.1.1 
      | | +-- onetime@1.0.0 
      | | `-- set-immediate-shim@1.0.1 
      | +-- log-symbols@1.0.2 
      | +-- object-values@1.0.0 
      | +-- semver@5.1.0 
      | `-- twig@0.8.2 
      |   +-- minimatch@0.2.14 
      |   | `-- sigmund@1.0.1 
      |   `-- walk@2.3.9 
      |     `-- foreachasync@3.0.0 
      +-- yeoman-environment@1.3.0 
      | +-- debug@2.2.0 
      | | `-- ms@0.7.1 
      | +-- diff@2.2.1 
      | +-- globby@3.0.1 
      | | +-- array-union@1.0.1 
      | | | `-- array-uniq@1.0.2 
      | | +-- glob@5.0.15 
      | | | +-- inflight@1.0.4 
      | | | +-- minimatch@3.0.0 
      | | | | `-- brace-expansion@1.1.1 
      | | | |   +-- balanced-match@0.2.1 
      | | | |   `-- concat-map@0.0.1 
      | | | `-- path-is-absolute@1.0.0 
      | | `-- pinkie-promise@1.0.0 
      | |   `-- pinkie@1.0.0 
      | +-- grouped-queue@0.3.0 
      | | +-- lodash@2.4.2 
      | | `-- setimmediate@1.0.4 
      | +-- mem-fs@1.1.1 
      | | +-- through2@2.0.0 
      | | | `-- xtend@4.0.1 
      | | +-- vinyl@1.1.0 
      | | | +-- clone@1.0.2 
      | | | +-- clone-stats@0.0.1 
      | | | `-- replace-ext@0.0.1 
      | | `-- vinyl-file@1.3.0 
      | |   `-- strip-bom-stream@1.0.0 
      | |     `-- first-chunk-stream@1.0.0 
      | +-- text-table@0.2.0 
      | `-- untildify@2.1.0 
      `-- yosay@1.1.0 
        +-- minimist@1.2.0 
        +-- pad-component@0.0.1 
        +-- string-width@1.0.1 
        +-- taketalk@1.0.0 
        | +-- get-stdin@4.0.1 
        | `-- minimist@1.2.0 
    ? Here's what I found. Official generator → ෴
      Install one? gulp-angular Yeoman generator for AngularJS with Gulp

    > spawn-sync@1.0.14 postinstall /usr/local/lib/node_modules/generator-gulp-angular/node_modules/spawn-sync
    > node postinstall

    /usr/local/lib
    `-- generator-gulp-angular@1.0.1 
      +-- chalk@1.1.1 
      | +-- ansi-styles@2.1.0 
      | +-- escape-string-regexp@1.0.3 
      | +-- has-ansi@2.0.0 
      | | `-- ansi-regex@2.0.0 
      | +-- strip-ansi@3.0.0 
      | `-- supports-color@2.0.0 
      +-- insight@0.7.0 
      | +-- async@1.5.0 
      | +-- configstore@1.3.0 
      | | +-- graceful-fs@4.1.2 
      | | +-- os-tmpdir@1.0.1 
      | | +-- osenv@0.1.3 
      | | +-- uuid@2.0.1 
      | | `-- write-file-atomic@1.1.3 
      | |   `-- slide@1.1.6 
      | +-- inquirer@0.10.1 
      | | +-- ansi-escapes@1.1.0 
      | | +-- cli-cursor@1.0.2 
      | | | `-- restore-cursor@1.0.1 
      | | |   `-- exit-hook@1.1.1 
      | | +-- cli-width@1.1.0 
      | | +-- figures@1.4.0 
      | | +-- readline2@1.0.1 
      | | | `-- mute-stream@0.0.5 
      | | +-- rx-lite@3.1.2 
      | | `-- through@2.3.8 
      | +-- lodash.debounce@3.1.1 
      | | `-- lodash._getnative@3.9.1 
      | +-- object-assign@4.0.1 
      | +-- os-name@1.0.3 
      | | +-- osx-release@1.1.0 
      | | | `-- minimist@1.2.0 
      | | `-- win-release@1.1.1 
      | |   `-- semver@5.1.0 
      | +-- request@2.67.0 
      | | +-- aws-sign2@0.6.0 
      | | +-- bl@1.0.0 
      | | +-- caseless@0.11.0 
      | | +-- combined-stream@1.0.5 
      | | | `-- delayed-stream@1.0.0 
      | | +-- extend@3.0.0 
      | | +-- forever-agent@0.6.1 
      | | +-- form-data@1.0.0-rc3 
      | | +-- har-validator@2.0.2 
      | | | +-- commander@2.9.0 
      | | | | `-- graceful-readlink@1.0.1 
      | | | +-- is-my-json-valid@2.12.3 
      | | | | +-- generate-function@2.0.0 
      | | | | +-- generate-object-property@1.2.0 
      | | | | | `-- is-property@1.0.2 
      | | | | `-- jsonpointer@2.0.0 
      | | | `-- pinkie-promise@1.0.0 
      | | |   `-- pinkie@1.0.0 
      | | +-- hawk@3.1.2 
      | | | +-- boom@2.10.1 
      | | | +-- cryptiles@2.0.5 
      | | | +-- hoek@2.16.3 
      | | | `-- sntp@1.0.9 
      | | +-- http-signature@1.1.0 
      | | | +-- assert-plus@0.1.5 
      | | | +-- jsprim@1.2.2 
      | | | | +-- extsprintf@1.0.2 
      | | | | +-- json-schema@0.2.2 
      | | | | `-- verror@1.3.6 
      | | | `-- sshpk@1.7.0 
      | | |   +-- asn1@0.2.3 
      | | |   +-- assert-plus@0.2.0 
      | | |   +-- dashdash@1.10.1 
      | | |   +-- ecc-jsbn@0.1.1 
      | | |   +-- jodid25519@1.0.2 
      | | |   +-- jsbn@0.1.0 
      | | |   `-- tweetnacl@0.13.2 
      | | +-- is-typedarray@1.0.0 
      | | +-- isstream@0.1.2 
      | | +-- json-stringify-safe@5.0.1 
      | | +-- mime-types@2.1.7 
      | | | `-- mime-db@1.19.0 
      | | +-- node-uuid@1.4.7 
      | | +-- oauth-sign@0.8.0 
      | | +-- qs@5.2.0 
      | | +-- stringstream@0.0.5 
      | | `-- tunnel-agent@0.4.1 
      | `-- tough-cookie@2.2.1 
      +-- lodash@3.10.1 
      +-- slash@1.0.0 
      +-- underscore.string@3.2.2 
      +-- yeoman-generator@0.20.3 
      | +-- class-extend@0.1.2 
      | | `-- object-assign@2.1.1 
      | +-- cli-table@0.3.1 
      | | `-- colors@1.0.3 
      | +-- cross-spawn@2.0.0 
      | | +-- cross-spawn-async@2.0.0 
      | | | +-- lru-cache@2.7.1 
      | | | `-- which@1.2.0 
      | | |   `-- is-absolute@0.1.7 
      | | |     `-- is-relative@0.1.3 
      | | `-- spawn-sync@1.0.14 
      | |   `-- os-shim@0.1.3 
      | +-- dargs@4.0.1 
      | | `-- number-is-nan@1.0.0 
      | +-- dateformat@1.0.12 
      | | +-- get-stdin@4.0.1 
      | | `-- meow@3.6.0 
      | |   +-- camelcase-keys@2.0.0 
      | |   | +-- camelcase@2.0.1 
      | |   | `-- map-obj@1.0.1 
      | |   +-- loud-rejection@1.2.0 
      | |   | `-- signal-exit@2.1.2 
      | |   +-- minimist@1.2.0 
      | |   +-- normalize-package-data@2.3.5 
      | |   | +-- hosted-git-info@2.1.4 
      | |   | +-- is-builtin-module@1.0.0 
      | |   | | `-- builtin-modules@1.1.0 
      | |   | `-- validate-npm-package-license@3.0.1 
      | |   |   +-- spdx-correct@1.0.2 
      | |   |   | `-- spdx-license-ids@1.1.0 
      | |   |   `-- spdx-expression-parse@1.0.1 
      | |   |     `-- spdx-exceptions@1.0.4 
      | |   +-- read-pkg-up@1.0.1 
      | |   | +-- find-up@1.1.0 
      | |   | | +-- path-exists@2.1.0 
      | |   | | `-- pinkie-promise@2.0.0 
      | |   | |   `-- pinkie@2.0.1 
      | |   | `-- read-pkg@1.1.0 
      | |   |   +-- load-json-file@1.1.0 
      | |   |   | `-- pinkie-promise@2.0.0 
      | |   |   |   `-- pinkie@2.0.1 
      | |   |   `-- path-type@1.1.0 
      | |   |     `-- pinkie-promise@2.0.0 
      | |   |       `-- pinkie@2.0.1 
      | |   +-- redent@1.0.0 
      | |   | +-- indent-string@2.1.0 
      | |   | | `-- repeating@2.0.0 
      | |   | `-- strip-indent@1.0.1 
      | |   `-- trim-newlines@1.0.0 
      | +-- debug@2.2.0 
      | | `-- ms@0.7.1 
      | +-- detect-conflict@1.0.0 
      | +-- diff@2.2.1 
      | +-- download@4.4.3 
      | | +-- caw@1.1.0 
      | | | +-- get-proxy@1.0.1 
      | | | | `-- rc@0.5.5 
      | | | |   +-- deep-extend@0.2.11 
      | | | |   +-- ini@1.3.4 
      | | | |   `-- strip-json-comments@0.1.3 
      | | | +-- is-obj@1.0.0 
      | | | `-- object-assign@3.0.0 
      | | +-- concat-stream@1.5.1 
      | | | `-- typedarray@0.0.6 
      | | +-- each-async@1.1.1 
      | | | +-- onetime@1.0.0 
      | | | `-- set-immediate-shim@1.0.1 
      | | +-- filenamify@1.2.0 
      | | | +-- filename-reserved-regex@1.0.0 
      | | | +-- strip-outer@1.0.0 
      | | | `-- trim-repeated@1.0.0 
      | | +-- got@5.1.0 
      | | | +-- create-error-class@2.0.1 
      | | | | `-- capture-stack-trace@1.0.0 
      | | | +-- duplexify@3.4.2 
      | | | | `-- end-of-stream@1.0.0 
      | | | +-- is-plain-obj@1.1.0 
      | | | +-- is-redirect@1.0.0 
      | | | +-- is-stream@1.0.1 
      | | | +-- lowercase-keys@1.0.0 
      | | | +-- node-status-codes@1.0.0 
      | | | +-- parse-json@2.2.0 
      | | | | `-- error-ex@1.3.0 
      | | | |   `-- is-arrayish@0.2.1 
      | | | +-- timed-out@2.0.0 
      | | | +-- unzip-response@1.0.0 
      | | | `-- url-parse-lax@1.0.0 
      | | |   `-- prepend-http@1.0.3 
      | | +-- gulp-decompress@1.2.0 
      | | | +-- archive-type@3.0.2 
      | | | | `-- file-type@3.3.0 
      | | | +-- decompress@3.0.0 
      | | | | +-- buffer-to-vinyl@1.1.0 
      | | | | +-- decompress-tar@3.1.0 
      | | | | | +-- is-tar@1.0.0 
      | | | | | +-- object-assign@2.1.1 
      | | | | | +-- strip-dirs@1.1.1 
      | | | | | | +-- is-natural-number@2.0.0 
      | | | | | | +-- minimist@1.2.0 
      | | | | | | `-- sum-up@1.0.2 
      | | | | | +-- tar-stream@1.3.1 
      | | | | | +-- through2@0.6.5 
      | | | | | | `-- readable-stream@1.0.33 
      | | | | | `-- vinyl@0.4.6 
      | | | | |   `-- clone@0.2.0 
      | | | | +-- decompress-tarbz2@3.1.0 
      | | | | | +-- is-bzip2@1.0.0 
      | | | | | +-- object-assign@2.1.1 
      | | | | | +-- seek-bzip@1.0.5 
      | | | | | | `-- commander@2.8.1 
      | | | | | +-- through2@0.6.5 
      | | | | | | `-- readable-stream@1.0.33 
      | | | | | `-- vinyl@0.4.6 
      | | | | |   `-- clone@0.2.0 
      | | | | +-- decompress-targz@3.1.0 
      | | | | | +-- is-gzip@1.0.0 
      | | | | | +-- object-assign@2.1.1 
      | | | | | +-- through2@0.6.5 
      | | | | | | `-- readable-stream@1.0.33 
      | | | | | `-- vinyl@0.4.6 
      | | | | |   `-- clone@0.2.0 
      | | | | +-- decompress-unzip@3.4.0 
      | | | | | +-- is-zip@1.0.0 
      | | | | | +-- stat-mode@0.2.1 
      | | | | | `-- yauzl@2.3.1 
      | | | | |   +-- fd-slicer@1.0.1 
      | | | | |   `-- pend@1.2.0 
      | | | | `-- vinyl-assign@1.2.1 
      | | | `-- gulp-util@3.0.7 
      | | |   +-- array-uniq@1.0.2 
      | | |   +-- beeper@1.1.0 
      | | |   +-- fancy-log@1.1.0 
      | | |   +-- gulplog@1.0.0 
      | | |   | `-- glogg@1.0.0 
      | | |   +-- has-gulplog@0.1.0 
      | | |   | `-- sparkles@1.0.0 
      | | |   +-- lodash._reescape@3.0.0 
      | | |   +-- lodash._reevaluate@3.0.0 
      | | |   +-- lodash._reinterpolate@3.0.0 
      | | |   +-- lodash.template@3.6.2 
      | | |   | +-- lodash._basecopy@3.0.1 
      | | |   | +-- lodash._basetostring@3.0.1 
      | | |   | +-- lodash._basevalues@3.0.0 
      | | |   | +-- lodash._isiterateecall@3.0.9 
      | | |   | +-- lodash.escape@3.0.0 
      | | |   | +-- lodash.keys@3.1.2 
      | | |   | | +-- lodash.isarguments@3.0.4 
      | | |   | | `-- lodash.isarray@3.0.4 
      | | |   | +-- lodash.restparam@3.6.1 
      | | |   | `-- lodash.templatesettings@3.1.0 
      | | |   +-- minimist@1.2.0 
      | | |   +-- multipipe@0.1.2 
      | | |   | `-- duplexer2@0.0.2 
      | | |   |   `-- readable-stream@1.1.13 
      | | |   +-- object-assign@3.0.0 
      | | |   `-- vinyl@0.5.3 
      | | +-- gulp-rename@1.2.2 
      | | +-- is-url@1.2.1 
      | | +-- read-all-stream@3.0.1 
      | | +-- readable-stream@2.0.4 
      | | | +-- core-util-is@1.0.2 
      | | | +-- isarray@0.0.1 
      | | | +-- process-nextick-args@1.0.3 
      | | | +-- string_decoder@0.10.31 
      | | | `-- util-deprecate@1.0.2 
      | | +-- stream-combiner2@1.1.1 
      | | | `-- duplexer2@0.1.4 
      | | +-- vinyl@1.1.0 
      | | | +-- clone@1.0.2 
      | | | +-- clone-stats@0.0.1 
      | | | `-- replace-ext@0.0.1 
      | | +-- vinyl-fs@2.2.1 
      | | | +-- glob-stream@5.2.0 
      | | | | +-- glob2base@0.0.12 
      | | | | | `-- find-index@0.1.1 
      | | | | +-- ordered-read-streams@0.3.0 
      | | | | +-- through2@0.6.5 
      | | | | | `-- readable-stream@1.0.33 
      | | | | +-- to-absolute-glob@0.1.1 
      | | | | | `-- extend-shallow@2.0.1 
      | | | | |   `-- is-extendable@0.1.1 
      | | | | `-- unique-stream@2.2.0 
      | | | +-- gulp-sourcemaps@1.6.0 
      | | | | `-- convert-source-map@1.1.2 
      | | | +-- is-valid-glob@0.3.0 
      | | | +-- merge-stream@1.0.0 
      | | | +-- strip-bom@2.0.0 
      | | | | `-- is-utf8@0.2.0 
      | | | +-- strip-bom-stream@1.0.0 
      | | | | `-- first-chunk-stream@1.0.0 
      | | | `-- through2-filter@2.0.0 
      | | `-- ware@1.3.0 
      | |   `-- wrap-fn@0.1.4 
      | |     `-- co@3.1.0 
      | +-- findup-sync@0.2.1 
      | | `-- glob@4.3.5 
      | +-- github-username@2.1.0 
      | | `-- gh-got@2.3.0 
      | |   `-- pinkie-promise@2.0.0 
      | |     `-- pinkie@2.0.1 
      | +-- glob@5.0.15 
      | | +-- inflight@1.0.4 
      | | | `-- wrappy@1.0.1 
      | | +-- inherits@2.0.1 
      | | +-- minimatch@2.0.10 
      | | | `-- brace-expansion@1.1.1 
      | | |   +-- balanced-match@0.2.1 
      | | |   `-- concat-map@0.0.1 
      | | `-- once@1.3.3 
      | +-- gruntfile-editor@1.1.0 
      | | `-- ast-query@1.0.1 
      | |   +-- escodegen@1.7.0 
      | |   | +-- esprima@1.2.5 
      | |   | +-- estraverse@1.9.3 
      | |   | +-- esutils@2.0.2 
      | |   | +-- optionator@0.5.0 
      | |   | | +-- deep-is@0.1.3 
      | |   | | +-- fast-levenshtein@1.0.7 
      | |   | | +-- levn@0.2.5 
      | |   | | +-- prelude-ls@1.1.2 
      | |   | | +-- type-check@0.3.1 
      | |   | | `-- wordwrap@0.0.3 
      | |   | `-- source-map@0.2.0 
      | |   |   `-- amdefine@1.0.0 
      | |   +-- esprima@2.7.0 
      | |   `-- traverse@0.6.6 
      | +-- html-wiring@1.2.0 
      | | +-- cheerio@0.19.0 
      | | | +-- css-select@1.0.0 
      | | | | +-- boolbase@1.0.0 
      | | | | +-- css-what@1.0.0 
      | | | | +-- domutils@1.4.3 
      | | | | `-- nth-check@1.0.1 
      | | | +-- dom-serializer@0.1.0 
      | | | | `-- domelementtype@1.1.3 
      | | | +-- entities@1.1.1 
      | | | `-- htmlparser2@3.8.3 
      | | |   +-- domelementtype@1.3.0 
      | | |   +-- domhandler@2.3.0 
      | | |   +-- domutils@1.5.1 
      | | |   +-- entities@1.0.0 
      | | |   `-- readable-stream@1.1.13 
      | | `-- detect-newline@1.0.3 
      | |   `-- minimist@1.2.0 
      | +-- inquirer@0.8.5 
      | | +-- ansi-regex@1.1.1 
      | | +-- readline2@0.1.1 
      | | | +-- mute-stream@0.0.4 
      | | | `-- strip-ansi@2.0.1 
      | | `-- rx@2.5.3 
      | +-- istextorbinary@1.0.2 
      | | +-- binaryextensions@1.0.0 
      | | `-- textextensions@1.0.1 
      | +-- mem-fs-editor@2.1.0 
      | | +-- commondir@1.0.1 
      | | +-- deep-extend@0.4.0 
      | | +-- ejs@2.3.4 
      | | +-- glob@6.0.1 
      | | +-- globby@4.0.0 
      | | | +-- array-union@1.0.1 
      | | | +-- arrify@1.0.0 
      | | | +-- glob@6.0.1 
      | | | +-- pify@2.3.0 
      | | | `-- pinkie-promise@2.0.0 
      | | |   `-- pinkie@2.0.1 
      | | `-- multimatch@2.1.0 
      | |   +-- array-differ@1.0.0 
      | |   `-- minimatch@3.0.0 
      | +-- mime@1.3.4 
      | +-- mkdirp@0.5.1 
      | | `-- minimist@0.0.8 
      | +-- nopt@3.0.6 
      | | `-- abbrev@1.0.7 
      | +-- path-exists@1.0.0 
      | +-- path-is-absolute@1.0.0 
      | +-- pretty-bytes@2.0.1 
      | +-- read-chunk@1.0.1 
      | +-- rimraf@2.4.4 
      | +-- run-async@0.1.0 
      | +-- shelljs@0.5.3 
      | +-- sinon@1.17.2 
      | | +-- formatio@1.1.1 
      | | +-- lolex@1.3.2 
      | | +-- samsam@1.1.2 
      | | `-- util@0.10.3 
      | +-- text-table@0.2.0 
      | +-- through2@2.0.0 
      | | `-- xtend@4.0.1 
      | +-- user-home@2.0.0 
      | | `-- os-homedir@1.0.1 
      | +-- xdg-basedir@2.0.0 
      | +-- yeoman-assert@2.1.0 
      | +-- yeoman-environment@1.3.0 
      | | +-- globby@3.0.1 
      | | +-- grouped-queue@0.3.0 
      | | | +-- lodash@2.4.2 
      | | | `-- setimmediate@1.0.4 
      | | +-- inquirer@0.11.0 
      | | +-- log-symbols@1.0.2 
      | | +-- mem-fs@1.1.1 
      | | | `-- vinyl-file@1.3.0 
      | | `-- untildify@2.1.0 
      | `-- yeoman-welcome@1.0.1 
      `-- yosay@1.0.5 
        +-- ansi-regex@1.1.1 
        +-- minimist@1.2.0 
        +-- pad-component@0.0.1 
        +-- repeating@1.1.3 
        | `-- is-finite@1.0.1 
        +-- string-width@1.0.1 
        | +-- code-point-at@1.0.0 
        | `-- is-fullwidth-code-point@1.0.0 
        +-- strip-ansi@2.0.1 
        +-- taketalk@1.0.0 
        | `-- minimist@1.2.0 
        `-- word-wrap@1.1.0 


    I just installed a generator by running:

        npm install -g generator-gulp-angular

    ? 'Allo Pedro! What would you like to do? Get me out of here!

         _-----_
        |       |    .-----------------------.
        |--(o)--|    |      Bye from us!     |
       `---------´   |       Chat soon.      |
        ( _´U`_ )    |      Yeoman team      |
        /___A___\    |    http://yeoman.io   |
         |  ~  |     '-----------------------'
       __'.___.'__   
     ´   `  |° ´ Y ` 

    semeano:~ semeano$ yo gulp-angular
    Error gulp-angular 

    You don't seem to have a generator with the name gulp-angular installed.
    You can see available generators with npm search yeoman-generator and then install them with npm install [name].
    To see the 0 registered generators run yo with the `--help` option.
    semeano:~ semeano$

**Comment by semeano** [comment]
Ok, so I've tried to install another generator (webapp) and that one works fine.

Probably a generator bug?

**Comment by semeano** [comment]
It was a bug on the generator.

https://github.com/Swiip/generator-gulp-angular/issues/923
