### ISSUE TITLE
Yo angular dist problems

### ISSUE THREAD

**Issue by roestigraben** [yeoman/yeoman#1572]
Hello, 
I have a problem with yeoman to build the distribution version of myApp
first are some info about my system/install

OSX 10.10.5
bower : 1.6.8
npm:  3.5.0
yo: 1.5.0

To scaffold my App, I do run the command with the options
yo angular myApp
Gulp?  no
Sass? no
Bootstrap? yes
angular-animate? no
angular-aria? no
angular-cookies? no
angular-resources? no
angular-route? yes
angular-sanitize? no
angular-touch? no

the build process runs OK with the following issue only
UNMET PEER DEPENDENCY jasmine-core@*
├── UNMET PEER DEPENDENCY karma@^0.13.0 || >= 0.14.0-rc.0
├── karma-jasmine@0.3.6 
├─┬ karma-phantomjs-launcher@0.2.1 
│ └── lodash@3.10.1 
└── UNMET PEER DEPENDENCY phantomjs@>=1.9

when I start the grunt serve, everything is OK

the doing grunt to get the dist be built, iI get aborted as per
Running "connect:test" (connect) task
Started connect web server on http://localhost:9001
Loading "grunt-karma.js" tasks...ERROR
>> Error: Cannot find module 'karma'
Warning: Task "karma" failed. Use --force to continue.

Aborted due to warnings.

When  I do grunt --force I get it done but I get

  Warning: Running "imagemin:dist" (imagemin) task
    Fatal error: Cannot read property 'contents' of undefined
    
    
    Execution Time (2015-11-30 11:17:49 UTC)
    loading tasks                   391ms  ▇▇▇▇▇▇▇▇▇▇ 32%
    loading grunt-contrib-imagemin  478ms  ▇▇▇▇▇▇▇▇▇▇▇▇ 39%
    imagemin:dist                   354ms  ▇▇▇▇▇▇▇▇▇ 29%
    Total 1.2s Used --force, continuing.
        
    Running "imagemin:dist" (imagemin) task
    Fatal error: Cannot read property 'contents' of undefined
    
Can someone help me to  get thisresolved please
many thanks
Peter

**Comment by addyosmani** [comment]
This issue was moved to yeoman/generator-angular#1222

**Comment by roestigraben** [comment]
Sorry, what does this mean " was moved to ....." ???

**Comment by SBoudrias** [comment]
@roestigraben We've just copied the content of your issue to the generator-angular repository. This is an generator-angular issue, so it goes into the generator-angular project.
