### ISSUE TITLE
Globally installed generators?

### ISSUE THREAD

**Issue by killswitch** [yeoman/yeoman#1573]
Is there a reason I have to `npm install -g some-spectacular-generator-here`? If the generator is only ever used with `yo` why is it being installed globally by itself? Wouldn't it make more sense to have something like `yo install generator-name` and have the package installed in some place that Yeoman can require from? I'm not a fan of having a crap ton of globally installed packages for no reason.

**Comment by SBoudrias** [comment]
@killswitch local installation also works.
