### ISSUE TITLE
manually created js files are not autoincluded

### ISSUE THREAD

**Issue by pulkitnandan** [yeoman/yeoman#1575]
I'm creating some controllers, services which are auto included in index.html after grunt serve while if they are created using yo angular command they are auto included.

 Command posted in contributing guidelines " yo --version && echo %PATH% %NODE_PATH% && node -e "console.log(process.platform, process.versions)" && type Gruntfile.js" gives irrelevant output of some mysql configuration in command prompt of windows 10.

I could not deduce which actual grunt step is doing the task of including non-vendor js source. 
I could not anything in whole of app where this magical grunt step is magically tracking of automatically created js source.

 I have to fallback to call the command but this becomes.

What am I missing here?

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
Paste in the link to the question here so others can follow ;)

**Comment by sindresorhus** [comment]
https://github.com/taptapship/wiredep is what's used to inject dependencies.
