### ISSUE TITLE
Installation Logic and Path Adaptation

### ISSUE THREAD

**Issue by DenDx** [yeoman/yeoman#1578]
I'm on Linux Mint 17.x using LAMP (LAMPP)

I want to talk and ask questions about adapting path statements.
I have constructed a template system for a dedicated development drive on Linux, mounted on my home folder as Devl. It looks like this:

These folders are the information library
[business].management, operations, and support
[web].planning, design, development, launch, and post launch

These folders contain project specific information
[projects] - contains the template (see next paragraph) of business and web folders
[project websites] - contains HTML structures (build tasks for Yeoman, bower, and grunt)

The [business] and [web] structure (without the information) is used as a template set that is copied into each [projects].project folder to create workflows, where the output is the [project websites].sandbox and [project websites].production.

npm has installed into /home/user
yo and generator-webapp have installed into /home/user/npm/lib

the google chrome beta has installed into /opt
lampp has installed into /opt
apache2 has installed into /opt/lampp
Using Apache server, the project websites are forced into a root folder /opt/lampp/htdocs

nvm has installed into /usr/local

Seems disorganized to me with opt, lampp, local, user and the many attending directories being used instead of having one central top down hierarchical file structure. Now it's search for a set of installation locations, make path corrections, and then test to see if it worked (which in my case it did not). BTW, I am using the Atom editor, which is a nice piece of work. I'm also a Linux noob that hasn't read all the docs, but I'm working on it.

Bash: Bash is sending no command for yo
Question pre: I've seen scripts to correct, but also comments that chmod kills security so not to use it, and not to install with sudo, I'm confused. So, what are the bash paths I need to set for npm or nvm, yo, bower, and grunt?  Do I need to uninstall  anything, change the paths, and then reinstall? Is there a page on the Internet illustrating the operational file structure with path connections that makes this all work? Thanks, Den

**Comment by SBoudrias** [comment]
See StackOverflow for supports questions - especially those not regarding Yeoman itself.
