### ISSUE TITLE
Found Issue while installation

### ISSUE THREAD

**Issue by ankurongit** [yeoman/yeoman#1579]
Found potential issues on your machine :(
grunt-cli@0.1.13 /usr/lib/node_modules/grunt-cli
├── resolve@0.3.1
├── nopt@1.0.10 (abbrev@1.0.7)
└── findup-sync@0.1.3 (lodash@2.4.2, glob@3.2.11)

bower@1.7.1 /usr/lib/node_modules/bower
└── semver-utils@1.1.1

yo@1.5.0 /usr/lib/node_modules/yo
├── titleize@1.0.0
├── figures@1.4.0
├── async@1.5.0
├── humanize-string@1.0.1 (decamelize@1.1.1)
├── user-home@2.0.0 (os-homedir@1.0.1)
├── sort-on@1.2.2 (dot-prop@2.2.0, arrify@1.0.1)
├── opn@3.0.3 (object-assign@4.0.1)
├── string-length@1.0.1 (strip-ansi@3.0.0)
├── chalk@1.1.1 (escape-string-regexp@1.0.4, supports-color@2.0.0, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
├── repeating@2.0.0 (is-finite@1.0.1)
├── root-check@1.0.0 (downgrade-root@1.1.0, sudo-block@1.2.0)
├── yeoman-character@1.1.0 (supports-color@3.1.2)
├── package-json@2.3.0 (registry-url@3.0.3, semver@5.1.0, rc@1.1.5)
├── npm-keyword@4.2.0 (object-assign@4.0.1, pinkie-promise@2.0.0, registry-url@3.0.3)
├── yosay@1.1.0 (strip-ansi@3.0.0, ansi-styles@2.1.0, ansi-regex@2.0.0, word-wrap@1.1.0, pad-component@0.0.1, minimist@1.2.0, taketalk@1.0.0, string-width@1.0.1)
├── configstore@1.4.0 (os-tmpdir@1.0.1, object-assign@4.0.1, graceful-fs@4.1.2, xdg-basedir@2.0.0, uuid@2.0.1, osenv@0.1.3, write-file-atomic@1.1.4, mkdirp@0.5.1)
├── cross-spawn-async@2.1.1 (lru-cache@3.2.0, which@1.2.0)
├── meow@3.6.0 (trim-newlines@1.0.0, object-assign@4.0.1, minimist@1.2.0, camelcase-keys@2.0.0, redent@1.0.0, loud-rejection@1.2.0, normalize-package-data@2.3.5)
├── read-pkg-up@1.0.1 (find-up@1.1.0, read-pkg@1.1.0)
├── yeoman-doctor@2.0.0 (object-values@1.0.0, log-symbols@1.0.2, semver@5.1.0, each-async@1.1.1, bin-version-check@2.1.0, twig@0.8.2)
├── lodash@3.10.1
├── inquirer@0.11.0 (ansi-regex@2.0.0, strip-ansi@3.0.0, ansi-escapes@1.1.0, cli-width@1.1.0, rx-lite@3.1.2, through@2.3.8, readline2@1.0.1, cli-cursor@1.0.2, run-async@0.1.0)
├── fullname@2.1.0 (pify@2.3.0, pinkie-promise@2.0.0, npmconf@2.1.2)
├── insight@0.7.0 (object-assign@4.0.1, tough-cookie@2.2.1, lodash.debounce@3.1.1, os-name@1.0.3, request@2.67.0, inquirer@0.10.1)
├── got@5.3.0 (lowercase-keys@1.0.0, timed-out@2.0.0, is-stream@1.0.1, is-redirect@1.0.0, is-plain-obj@1.1.0, object-assign@4.0.1, unzip-response@1.0.0, node-status-codes@1.0.0, pinkie-promise@2.0.0, create-error-class@2.0.1, url-parse-lax@1.0.0, parse-json@2.2.0, read-all-stream@3.0.1, duplexify@3.4.2)
├── yeoman-environment@1.4.0 (log-symbols@1.0.2, escape-string-regexp@1.0.4, grouped-queue@0.3.2, text-table@0.2.0, untildify@2.1.0, diff@2.2.1, debug@2.2.0, mem-fs@1.1.2, globby@4.0.0)
└── update-notifier@0.5.0 (is-npm@1.0.0, semver-diff@2.1.0, repeating@1.1.3, latest-version@1.0.1)
ankur@ankurshukla-535U4C:~/Downloads$ yo --version && bower --version && grunt --version
1.5.0
1.7.1
grunt-cli v0.1.13

**Comment by ankurongit** [comment]
How do i fix them ?

**Comment by SBoudrias** [comment]
Please provide a trace or an error. This is not useful.
