### ISSUE TITLE
generator-angular failing to find itself

### ISSUE THREAD

**Issue by dean-me** [yeoman/yeoman#1580]
Hi,
On a fresh node install (5.3.0) with the latest npm (3.5.2) I'm attempting create a project with generator-angular. Prior to running "yo angular" everything checks out fine (print below). Running "yo angular" the generator starts up fine & asks the usual setup questions. During generation it fails with this error:

"Error angular

You don't seem to have a generator with the name angular:common:C:\Users\dean\Ap
pData\Roaming\npm\node_modules\generator-angular\app\index.js installed."

What? generator-angular can't find itself? What's up?

------------------- CLI PRINT OUT BELOW ----------------------------

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\WINDOWS\system32>npm install -g grunt-cli bower yo generator-karma generator-
angular
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'

npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
C:\Users\dean\AppData\Roaming\npm\bower -> C:\Users\dean\AppData\Roaming\npm\nod
e_modules\bower\bin\bower
C:\Users\dean\AppData\Roaming\npm\grunt -> C:\Users\dean\AppData\Roaming\npm\nod
e_modules\grunt-cli\bin\grunt
C:\Users\dean\AppData\Roaming\npm\yo -> C:\Users\dean\AppData\Roaming\npm\node_m
odules\yo\lib\cli.js

> yo@1.5.1 postinstall C:\Users\dean\AppData\Roaming\npm\node_modules\yo
> yodoctor

Yeoman Doctor
Running sanity checks on your system

√ Global configuration file is valid
√ NODE_PATH matches the npm root
√ Node.js version
√ No .bowerrc file in home directory
√ No .yo-rc.json file in home directory
√ npm version

Everything looks all right!
C:\Users\dean\AppData\Roaming\npm
├── bower@1.7.1
├── generator-angular@0.15.1
├── generator-karma@1.0.1
├── grunt-cli@0.1.13
└── yo@1.5.1

C:\WINDOWS\system32>cd C:\UniServerZ\www\yeo_ang

C:\UniServerZ\www\yeo_ang>yo angular

     _-----_
    |       |    .--------------------------.
    |--(o)--|    |    Welcome to Yeoman,    |
   `---------'   |   ladies and gentlemen!  |
    ( _'U`_ )    '--------------------------'
    /___A___\
     |  ~  |
   __'.___.'__
 '   `  |° ' Y `

Out of the box I include Bootstrap and some AngularJS recommended modules.

? Would you like to use Gulp (experimental) instead of Grunt? No
? Would you like to use Sass (with Compass)? Yes
? Would you like to include Bootstrap? No
? Which modules would you like to include? angular-animate.js, angular-cookies.j
   create app\styles\main.scssr-route.js, angular-sanitize.js, angular-touch.js
   create app\index.html
   create bower.json
   create .bowerrc
   create package.json
   create Gruntfile.js
   create README.md
Error angular

You don't seem to have a generator with the name angular:common:C:\Users\dean\Ap
pData\Roaming\npm\node_modules\generator-angular\app\index.js installed.
You can see available generators with npm search yeoman-generator and then insta
ll them with npm install [name].
To see the 15 registered generators run yo with the `--help` option.

**Comment by Spasms** [comment]
I'm on mac and seeing the exact same thing. Latest version of node, npm, yo, bower, grunt-cli and generator-angular.

Running `yo angular` gives the following output:

```
○ → yo angular

     _-----_
    |       |    .--------------------------.
    |--(o)--|    |    Welcome to Yeoman,    |
   `---------´   |   ladies and gentlemen!  |
    ( _´U`_ )    '--------------------------'
    /___A___\
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

Out of the box I include Bootstrap and some AngularJS recommended modules.

? Would you like to use Gulp (experimental) instead of Grunt? Yes
? Would you like to use Sass? No
? Would you like to include Bootstrap? Yes
? Which modules would you like to include? angular-animate.js, angular-cookies.js, angular-resource.js, angular-route.js, angular-sanitize.js, angular-touch.js
   create app/styles/main.css
   create app/index.html
   create bower.json
   create .bowerrc
   create package.json
   create gulpfile.js
   create README.md
Error angular

You don't seem to have a generator with the name angular:common:/Users/home/.npm-packages/lib/node_modules/generator-angular/app/index.js installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 15 registered generators run yo with the `--help` option.
```

**Comment by rof20004** [comment]
Same here

**Comment by rohit-creo** [comment]
Same here.

**Comment by bcbogdan** [comment]
I get the same error on elementary Freya. 

The output from 'yo doctor' is 'Everything looks ok!'
Tried to clean everything and reinstall node but it got me to the same issue.

**Comment by SBoudrias** [comment]
cc @eddiemonge

**Comment by SBoudrias** [comment]
Duplicate https://github.com/yeoman/generator-angular/issues/1239

**Comment by techneo1** [comment]
same here!! :+1:
