### ISSUE TITLE
Angular generator fails. Ruby required ?

### ISSUE THREAD

**Issue by pisani** [yeoman/yeoman#1583]
Hi, 
I have followed the Yeoman getting started material on the Yeoman website, to setup a new Dev environment on my Win7, 64 bit PC.

I want to start a new Angular project and used the 'angular' generator.

To my surprise, however, after issueing the 'grunt serve' command for the first time, the script comomplains that 'compass.bat' does not exist in the root project folder (it hasn't been created).

Note: I do not have Ruby installed, as this was never a requirement when setting up the tools and packages before issuing the 'yo angular' command.

Why is 'compass.bat not being created and must I use Saas and Ruby ??

Thanks

**Comment by SBoudrias** [comment]
Compass is a ruby, my guess is you'll need to install both.

**Comment by SBoudrias** [comment]
Which is done with first installing ruby https://www.ruby-lang.org/en/documentation/installation/

Then running `gem install compass` in your cmd.

**Comment by pisani** [comment]
Thanks.  I agree. I have to install Ruby.

But: Should someone update the Getting Started articles on the Yeoman website, or the READ.ME file in https://github.com/yeoman/generator-angular actually say that, to use the angular-generator you absolutely must install Ruby.

I mean... What If I don't want/can't install Ruby? Can I still use Yeoman to create and angularJS project ?

**Comment by SBoudrias** [comment]
You'd need to manually change some stuff related to the CSS.

**Comment by SBoudrias** [comment]
Please open the issue over here https://github.com/yeoman/generator-angular if you want to talk more with the generator-angular maintainers about updating documentation. - But really the best you could do is send a fix yourself to the documentation so the next person doesn't have the same surprise.
