### ISSUE TITLE
npm dependencies included in top level 'node_modules' folder

### ISSUE THREAD

**Issue by falkop** [yeoman/yeoman#1584]
env | version
------------ | -------------
osx | 10.10.5
yeoman | 1.5.1
npm | 3.5.2
node | v0.12.4

---

I'm installing some npm via the function npmInstall if I do this then the packages will be installed like a charm. The only issue is that the dependencies of the packages are installed on the top level of the node_modules folder.

So far I can remember in the past it didn't happen maybe it's because I updated npm to a newer version. Am I the only one who has that phenomenon?

I'd appreciate if anybody has an idea ;) 

thanks in advance

e.g.:
```javascript
this.npmInstall(['grunt'], {'saveDev': true	});
```

the result would be:
```
node_modules
    ├── abbrev
    ├── argparse
    │   ├── examples
    │   ├── lib
    │   │   ├── action
    │   │   │   ├── append
    │   │   │   └── store
    │   │   ├── argument
    │   │   └── help
    │   └── node_modules
    │       └── underscore.string
    │           └── lib
    ├── async
    │   └── lib
    ├── coffee-script
    │   ├── bin
    │   ├── extras
    │   └── lib
    │       └── coffee-script
    ├── colors
    │   └── themes
    ├── dateformat
    │   ├── lib
    │   └── test
    ├── esprima
    │   ├── bin
    │   └── test
    ├── eventemitter2
    │   └── lib
    ├── exit
    │   ├── lib
    │   └── test
    │       └── fixtures
   ......
```

**Comment by SBoudrias** [comment]
npm3 now install dependencies as flat as possible. It'll only nest to resolve version conflicts.

**Comment by falkop** [comment]
thanks a lot for the info!
