### ISSUE TITLE
Do not see generators 

### ISSUE THREAD

**Issue by codemon2002** [yeoman/yeoman#1585]
So I have had this webpage waiting for 15 min now, no response, I have tried it multiple times with different browsers.  The list of generators are not loading.
![image](https://cloud.githubusercontent.com/assets/7032806/12497202/f97e306e-c05f-11e5-869e-f9a2942dc5e8.png)

**Comment by SBoudrias** [comment]
Any error in your console or anything? It's working for me currently

**Comment by codemon2002** [comment]
I figured it out, I was trying to access it at work and work security is
blocking only the populating part of the list of generators.  I don't know
if this can be fixed.

Simon Boudrias <notifications@github.com>于2016年1月21日周四 下午5:22写道：

**Comment by SBoudrias** [comment]
Well, your work would need to unblock our api site.
