### ISSUE TITLE
Web site issue - generator-webapp

### ISSUE THREAD

**Issue by StfBauer** [yeoman/yeoman#1587]
The yeoman.io web site still points to the outdated [generator-webapp](http://yeoman.io/learning/index.html) instead of generator-gulp-webapp. The problem I ran into was that you still can install generator-webapp but when you try to create a new web app it says that this generator does not exist anymore.

**Comment by SBoudrias** [comment]
cc @silvenon

**Comment by silvenon** [comment]
That's weird, [it exists](https://www.npmjs.com/package/generator-webapp), running it should work just fine :confused:

**Comment by StfBauer** [comment]
What I read on the issue list of generator-webapp is that this grunt based generator shouldn't be used anymore so I was curious if in general the guidance of yeoman is to use the new one rather then the old one.

[Deprecation issue on GitHub](https://github.com/yeoman/generator-webapp/issues/567)

I think it just will create some confusion when it is deprecated and everything still points to this generator.
Last weekend I played a little bit around because a customer had an issue with browser-sync on windows too. A problem I was able to solver for all windows Versions.

**Comment by silvenon** [comment]
Yeah, it's not actively maintained, but we still listen, accept PRs and fix critical bugs. It should definitely still work. I agree, we should really update Yeoman's site to point to the Gulp version as well, thanks for the feedback. We'll leave this open until this happens one way or another.

**Comment by eddiemonge** [comment]
Closing this as the gulp one was made the default one.

**Comment by StfBauer** [comment]
:+1:
