### ISSUE TITLE
How could i get a yo version > 1.0.4

### ISSUE THREAD

**Issue by NajehM** [yeoman/yeoman#1589]
**i run the command;**
$ npm install -g generator-yo-wordpress  
**i got this problem**
C:\Users\hp.hp-PC\AppData\Roaming\npm
+-- generator-yo-wordpress@1.4.9
| `-- yeoman-generator@0.22.5
|   +-- download@4.4.3
|   | `-- gulp-decompress@1.2.0
|   |   +-- archive-type@3.2.0
|   |   | `-- file-type@3.7.0
|   |   `-- gulp-util@3.0.7
|   |     `-- lodash.template@3.6.2
|   |       `-- lodash.escape@3.2.0
|   |         `-- lodash._root@3.0.0
|   `-- through2@2.0.1
`-- UNMET PEER DEPENDENCY yo@>=1.0.4

npm WARN generator-yo-wordpress@1.4.9 requires a peer of yo@>=1.0.4 but none was installed.

**what shall i do please**
**i work with npm v 3.3.12
node v 5.5.0
windows 7**

**Comment by SBoudrias** [comment]
You don't need to do anything about it. It's only a warning.

**Comment by NajehM** [comment]
thank you
