### ISSUE TITLE
How to call a subgenerator?

### ISSUE THREAD

**Issue by johannesjo** [yeoman/yeoman#1591]
As asked here http://stackoverflow.com/questions/20721060/yeoman-call-sub-generator-with-user-supplied-arguments

E.g.
```
yo gen:something
// should run programmatically
yo gen:somethingElse someArg
```
I could simply do this by executing a shell command, but that seems stupid.

**Comment by SBoudrias** [comment]
Use `this.composeWith` http://yeoman.io/authoring/composability.html

**Comment by johannesjo** [comment]
For anyone who wonders, that is the right syntax for sub modules:
```
this.composeWith('<generatorName>:<subGenName>', {
        args: [],
        options: {}
    },
    {
        local: require.resolve('<pathToSubGen>')
    });
```

It's a little stupid imho, that you need to manually enter the name of the (parent) generator your currently using.
