### ISSUE TITLE
Yeoman won't reinstall

### ISSUE THREAD

**Issue by mattlbrody** [yeoman/yeoman#1594]
I recently ran yeoman for the first time in over 6 months, I was told to update, which I promptly did. When I did that, it told me to update node, which I also did. I followed the instructions exactly but I must have done something wrong, and I can't figure this out after going through dozens of threads on similar issues. 

I reinstalled node, npm, bower, and grunt. But when I try to install yo, I get a weird error. 

Macintosh-6:~ Xia$ sudo npm -g install yo
Password:
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
/Users/xia/.npm-packages/bin/yo -> /Users/xia/.npm-packages/lib/node_modules/yo/lib/cli.js

> yo@1.6.0 postinstall /Users/xia/.npm-packages/lib/node_modules/yo
> yodoctor

Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✖ npm version

Your npm version is outdated.

Upgrade to the latest version by running:
npm install -g npm

Found potential issues on your machine :(
/Users/xia/.npm-packages/lib
└── yo@1.6.0 

I've tried both versions of node, LTS and Stable, but neither seem to work. 

I'm also required to write sudo, only when installing yeoman, this is the error I get otherwise.

Macintosh-6:~ Xia$ npm -g install yo
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN checkPermissions Missing write access to /Users/xia/.npm-packages/lib/node_modules/yo
/Users/xia/.npm-packages/lib
└── yo@1.6.0 

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "-g" "install" "yo"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! path /Users/xia/.npm-packages/lib/node_modules/yo
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/Users/xia/.npm-packages/lib/node_modules/yo'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/Users/xia/.npm-packages/lib/node_modules/yo']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/Users/xia/.npm-packages/lib/node_modules/yo' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xia/npm-debug.log

Please help :)

**Comment by sindresorhus** [comment]
Please use our support channels: https://github.com/yeoman/yeoman#support

**Comment by SBoudrias** [comment]
Google `EACCES: permission denied`
