### ISSUE TITLE
There's no gruntfile.js on the project which not created with "yo angular"??

### ISSUE THREAD

**Issue by Derekc1031** [yeoman/yeoman#1595]
HI, all

I'm totally freshman to yeoman, I created two projects , one was created with command "yo angular" and the other was not (only installed "sass" and "bootstrap" with yeoman).

But I found a strange thing on the project which is not created with command "yo angular" , 
there was no gruntfile.js but only gulpfile.babel.js !! Why?? Is it normal??

**Comment by SBoudrias** [comment]
Please open the issue on the generator you used or ask for help on StackOverflow.
