### ISSUE TITLE
Error with installation of yeoman Failed at the yo@1.7.0 postinstall script 'yodoctor'

### ISSUE THREAD

**Issue by Indomita** [yeoman/yeoman#1599]
Cannot install Yo. Tried all the ways uninstalling npm and node. yodoctor shows everithing looks all right!

Here is a copy of the npm-debug.log error:

456 verbose stack Error: yo@1.7.0 postinstall: `yodoctor`
25456 verbose stack spawn ENOENT
25456 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:17:16)
25456 verbose stack     at emitTwo (events.js:100:13)
25456 verbose stack     at ChildProcess.emit (events.js:185:7)
25456 verbose stack     at maybeClose (internal/child_process.js:850:16)
25456 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
25457 verbose pkgid yo@1.7.0
25458 verbose cwd /
25459 error Darwin 14.0.0
25460 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "yo"
25461 error node v5.8.0
25462 error npm  v3.7.3
25463 error file sh
25464 error code ELIFECYCLE
25465 error errno ENOENT
25466 error syscall spawn
25467 error yo@1.7.0 postinstall: `yodoctor`
25467 error spawn ENOENT
25468 error Failed at the yo@1.7.0 postinstall script 'yodoctor'.
25468 error Make sure you have the latest version of node.js and npm installed.
25468 error If you do, this is most likely a problem with the yo package,
25468 error not with npm itself.
25468 error Tell the author that this fails on your system:
25468 error     yodoctor
25468 error You can get information on how to open an issue for this project with:
25468 error     npm bugs yo
25468 error Or if that isn't available, you can get their info via:
25468 error     npm owner ls yo
25468 error There is likely additional logging output above.
25469 verbose exit [ 1, true ]

**Comment by SBoudrias** [comment]
http://stackoverflow.com/questions/33487085/yodoctor-command-not-found-when-installing-yo-from-terminal
