### ISSUE TITLE
Can't install yoman on MAC, ENOTEMPTY error

### ISSUE THREAD

**Issue by MengtingXie** [yeoman/yeoman#1600]
when use npm install -g yo to install yoman, I get : 

npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/5.1.0/bin/node" "/usr/local/bin/npm" "i" "-g" "yo"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! path /usr/local/lib/node_modules/yo
npm ERR! code ENOTEMPTY
npm ERR! errno -66
npm ERR! syscall rename

npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/yo' -> '/usr/local/lib/node_modules/.yo.DELETE'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

Please help!

**Comment by SBoudrias** [comment]
> npm ERR! If you need help, you may report this error at:
> npm ERR! https://github.com/npm/npm/issues
