### ISSUE TITLE
Blacklist link doesn't work

### ISSUE THREAD

**Issue by kamarouski** [yeoman/yeoman#1601]
I've created a new generator and it doesn't appear in the list of yeoman generators after 12h after submission to npm  (angular-components-es6 https://www.npmjs.com/package/generator-angular-components-es6),

When I want to check if it's blacklisted the link does nothing (http://yeoman.io/generators/) . I do not see a list of blacklisted generators.

**Comment by SBoudrias** [comment]
cc @eddiemonge

**Comment by eddiemonge** [comment]
The blacklist file is here: https://github.com/yeoman/yeoman-generator-list/blob/master/src/blacklist.js

I also added an issue in the repo to publish a problem list

**Comment by kamarouski** [comment]
It probably a dumb question, but how frequently yeoman indexes generators? Website says it's once an hour but my generator still not in the list and I don't understand why :(

**Comment by eddiemonge** [comment]
It should be in there now. Its supposed to be once an hour when things run smoothly. Google cloud had an issue that broke the uploads. Its back to normal though
