### ISSUE TITLE
Is it possible to use a generator that is defined in a library?

### ISSUE THREAD

**Issue by vjpr** [yeoman/yeoman#1602]
I have a library that has a bunch of gulp tasks for various things such as babel transpiling, running nodemon, eslinting, etc.

I want to store the generators inside this library because depending on which version of this library you use, you will want to use the corresponding generator versions.

I think this is quite common with frameworks too. You want the generators to be tied to the version of the framework you are using.

I could only think of something like this but I get an error that the namespace doesn't exist.

```
const generatorPath = path.join(this.destinationRoot(), 'node_modules/mylib/generators')
this.composeWith('live:webpackerator', {local: generatorPath})
```

```
# mylib/generators.js
export default class Generator extends yeoman.Base {

}
```

It would be great if you could pass in a generator `class` (object extending from `yeoman.Base`) to `composeWith`.

**Comment by vjpr** [comment]
It just occurred to me that maybe its best to reference plain functions from my library from a main generator, instead of trying to square the circle.

**Comment by vjpr** [comment]
Seems it has been discussed here and was not intended to be the cleanest solution: https://github.com/yeoman/generator/issues/484#

**Comment by SBoudrias** [comment]
@vjpr the issue in your example is that the paths to a yeoman generator needs to be "standarized" to how yeoman parses paths.

It always need to be one of:

- `generator-NAME/app` (or other generator name)
- `generator-NAME/generators/app`

That is, unless you run with yo through a path `yo ./gen/whatever/`

**Comment by vjpr** [comment]
Ok thanks. Would be great to decouple generators from the file structure. I think I've seen discussion of this for v1 elsewhere so I will close this issue.

**Comment by SBoudrias** [comment]
Yes, we talked about it a few times. But it's really hard to do without breaking the current ecosystem.

**Comment by vjpr** [comment]
I'm just going to use a mixin approach.

```
      const generatorsPath = path.join(this.destinationRoot(), 'node_modules/mylib/generators')
      const generators = require(generatorsPath)
      console.log('Configuring modules:', Object.values(generators))
      _(generators).map((generator, key) => generator.prompting.call(this))
```

```
module.exports = {
  babel: {
    prompting() { ... },
    writing() { ... },
  },
  foo: {
    writing() { ... }
  }
}
```
