### ISSUE TITLE
Cannot install Yeoman on Mac OS X 10.11.3

### ISSUE THREAD

**Issue by worldofweirdthings** [yeoman/yeoman#1603]
Hi there!

For some reason, I'm unable to install Yeoman to create an MVC 6 project on Mac OS X 10.11.3 with npm version 3.8.3 using the standard `sudo npm install -g yo` command. It also failed to install with a 2.8.x version of npm asking me to update to a more recent version. After I did this, the following error comes up with every attempt to install it...

> ENOENT: no such file or directory, open '/tmp/npm-578-fd1b07ee/unpack-e6ba4806/package.json'

I attached the [log file](https://github.com/yeoman/yeoman/files/201062/npm-debug-log.txt) as requested and am hoping for any advice for what I might be missing or doing wrong. Thanks ahead!

**Comment by SBoudrias** [comment]
Update npm and retry?

That's not related to yeoman.
