### ISSUE TITLE
Grunt Dist Builds should disable angular debug (or an option to)?

### ISSUE THREAD

**Issue by fishgills** [yeoman/yeoman#1605]
I'm freaking loving Yeoman. It's making angular super duper duper easy.

One feature I feel is missing is disabling angular debug mode for production builds.

https://docs.angularjs.org/guide/production

I realize a user could do this themselves (For my work projects, I use Gulp and have done this) but not everyone is going to be savvy with Grunt/Gulp. Could just append the `vendor.js` or maybe separate JS file that gets concatenated into `vendor.js`? I dunno. Just a thought.

**Comment by SBoudrias** [comment]
PR are always welcomed!

**Comment by sindresorhus** [comment]
Open an issue on the generator you're referring to. This issue tracker is for general Yeoman stuff.
