### ISSUE TITLE
Issue with Template Regeneration

### ISSUE THREAD

**Issue by abwaters** [yeoman/yeoman#1608]
I'm not sure if this is an issue or not but it feels like one.  I'm asking here because i'm not sure the right place to ask.

'grunt build' works fine but when I do 'grunt serve' and I make a change, it all breaks due to the templates not rebuilding.  I get the following error:

Uncaught ReferenceError: JST is not defined

I typically have to stop the grunt webserver (ctrl-c) and execute grunt build and rerun grunt serve.  I'm assuming the templates should rebuild during watch as well.  Is there a step missing in my gruntfile.js?  I'm not really sure where to look and the error is all over the web for a dozen different reasons...

any guidance is appreciated.

Thanks!

**Comment by SBoudrias** [comment]
Can you open this issue on the repository of the generator you used?
