### ISSUE TITLE
fails to install on debian jessie

### ISSUE THREAD

**Issue by r3wt** [yeoman/yeoman#1609]
http://stackoverflow.com/questions/37195275/error-installing-yeoman-on-debian-jessie

Let me know of any additional details you need. 

It prompts me to select whether to dump post install to STDOUT or write it to bashrc. if i select to write to the file, throws a bunch of weird errors. if i select the first option and run `yo-complete` nothing happens. then when tyring to run a generator i get the error in the above question.

**Comment by eddiemonge** [comment]
closing since there are some helpful answers on the stackoverflow question. Also, you probably shouldn't be running things as root

**Comment by r3wt** [comment]
There isn't a single answer on the question though.

**Comment by SBoudrias** [comment]
cc @mklabs auto complete related on a unix distro

@r3wt if you re-open this issue on the yeoman/yo bug tracker, we'll follow up.
