### ISSUE TITLE
unable to install "yo"

### ISSUE THREAD

**Issue by FabienDehopre** [yeoman/yeoman#1614]
When I try to install "yo" on my freshly installed windows 10, I receive an error (at the end) telling me that a file cannot be found.

Here is the console output of the npm install command:
```
PS C:\Users\Fabien\devs> npm i -g yo
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm ERR! Windows_NT 10.0.14295
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "yo"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! path C:\Users\Fabien\AppData\Roaming\npm\node_modules\yo\lib\cli.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\Fabien\AppData\Roaming\npm\node_modules\yo\lib\cli.js'
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\Fabien\AppData\Roaming\npm\node_modules\yo\lib\cli.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Fabien\devs\npm-debug.log
```
I use node version 6.2.0 with npm version 3.8.9

Here is the output of the command "echo %PATH% %NODE_PATH% && node -e "console.log(process.platform, process.versions)"":
```
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\Fabien\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft VS Code\bin %NODE_PATH%
win32 { http_parser: '2.7.0',
  node: '6.2.0',
  v8: '5.0.71.47',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2h' }
```

And here is the npm-debug.txt file (compressed in a zip because Github failed to attach a txt file)
[npm-debug.zip](https://github.com/yeoman/yeoman/files/270523/npm-debug.zip)

And here is the content of my global npm node_modules folder after I tried to install "yo":
![image](https://cloud.githubusercontent.com/assets/97023/15359587/5117acd6-1d0a-11e6-9477-1ce6f9013451.png)

**Comment by antid0te** [comment]
Same problem here.
I just installed previous version with 
`npm install -g yo@1.8.1 `
waiting for bug to be fixed

**Comment by kevva** [comment]
https://github.com/yeoman/yo/issues/437
