### ISSUE TITLE
Run concat : generated WARNING : Arguments to path.join must be string

### ISSUE THREAD

**Issue by sumayku-design** [yeoman/yeoman#1617]
I'm running grunt build in yeoman and get warning, i'm still new with yeoman structure in gruntfile.js with yeoman 
the issue is:
`
Running "concat:generated" (concat) task
Warning: Arguments to path.join must be strings Use --force to continue.
`
i already post an issue in [grunt concat](https://github.com/gruntjs/grunt-contrib-concat) [#163 ](https://github.com/gruntjs/grunt-contrib-concat/issues/163) but no response and run 
grunt --stack

`C:\wamp\www\mumu-2>grunt --task path.js:233 throw new TypeError('Arguments to path.join must be strings'); ^ TypeError: Arguments to path.join must be strings at Object.win32.join (path.js:233:13) at Object.file.exists (C:\wamp\www\mumu-2\node_modules\grunt\lib\grunt\file. js:381:28) at task.loadTasks (C:\wamp\www\mumu-2\node_modules\grunt\lib\grunt\task.js:3 71:18) at Array.forEach (native) at Task.task.init (C:\wamp\www\mumu-2\node_modules\grunt\lib\grunt\task.js:4 57:33) at Object.grunt.tasks (C:\wamp\www\mumu-2\node_modules\grunt\lib\grunt.js:12 0:8) at Object.module.exports [as cli] (C:\wamp\www\mumu-2\node_modules\grunt\lib \grunt\cli.js:38:9) at Object.<anonymous> (C:\Users\Sumayku\AppData\Roaming\npm\node_modules\gru nt-cli\bin\grunt:45:20) at Module._compile (module.js:460:26) at Object.Module._extensions..js (module.js:478:10)
` 
what file should i change to string function ?

**Comment by SBoudrias** [comment]
You should open this issue on the repository of the generator you used.
