### ISSUE TITLE
[CODELAB] Unit Tests on Step 6 Fail on karma.js

### ISSUE THREAD

**Issue by andymagill** [yeoman/yeoman#1621]
Not sure where to post this issue, so I apologize if this is not the correct place. On step 6 of the code lab here : http://yeoman.io/codelab/run-unit-tests.html the unit tests fails on karma,js. I have not modifed any file execpt header.js as described in the codelab. Here is the error.
```
[17:09:36] 'karma:single-run' errored after 23 s
[17:09:36] Error: Failed 1 tests.
    at c:\projects\test\mytodo\gulp_tasks\karma.js:11:22
    at removeAllListeners (c:\projects\test\mytodo\node_modules\karma\lib\server
.js:336:7)
    at Server.<anonymous> (c:\projects\test\mytodo\node_modules\karma\lib\server
.js:347:9)
    at Server.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at Server.emit (events.js:166:7)
    at emitCloseNT (net.js:1521:8)
    at nextTickCallbackWith1Arg (node.js:431:9)
    at process._tickDomainCallback (node.js:394:17)
```

I am running Win7. Here is the output when I run this command : `yo --version && echo %PATH% %NODE_PATH% && node -e "console.log(process.platform, process.versions)" && type gulpfile.js` (I changed gruntfile.js to gulpfile.js in this command i got from here : http://yeoman.io/contributing/opening-issues.html , seemed more appropriate since I don't have a gruntfile there. )

```
1.8.4
C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\Wind
owsPowerShell\v1.0\;C:\Program Files (x86)\Enterprise Vault\EVClient\;C:\Program
 Files (x86)\Heroku\bin;C:\Program Files (x86)\git\cmd;C:\Program Files (x86)\Gi
t\cmd;C:\Program Files\nodejs\;C:\RailsInstaller\Git\cmd;C:\RailsInstaller\Ruby2
.1.0\bin;C:\Ruby22-x64\bin;C:\Users\amagill\AppData\Roaming\npm %NODE_PATH%
win32 { http_parser: '2.5.2',
  node: '4.4.5',
  v8: '4.5.103.35',
  uv: '1.8.0',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '46',
  openssl: '1.0.2h' }
const gulp = require('gulp');
const HubRegistry = require('gulp-hub');
const browserSync = require('browser-sync');

const conf = require('./conf/gulp.conf');

// Load some files into the registry
const hub = new HubRegistry([conf.path.tasks('*.js')]);

// Tell gulp to use the tasks just loaded
gulp.registry(hub);

gulp.task('build', gulp.series(gulp.parallel('other', 'webpack:dist')));
gulp.task('test', gulp.series('karma:single-run'));
gulp.task('test:auto', gulp.series('karma:auto-run'));
gulp.task('serve', gulp.series('webpack:watch', 'watch', 'browsersync'));
gulp.task('serve:dist', gulp.series('default', 'browsersync:dist'));
gulp.task('default', gulp.series('clean', 'build'));
gulp.task('watch', watch);

function reloadBrowserSync(cb) {
  browserSync.reload();
  cb();
}

function watch(done) {
  gulp.watch(conf.path.tmp('index.html'), reloadBrowserSync);
  done();
}
```
I'm posting this because I believe I performed all steps correctly and this might represent a wider issue. Let me know if I screwed something up.

**Comment by dhinterlang** [comment]
Got this exact same issue. Using Windows 10.

**Comment by SBoudrias** [comment]
cc @zckrs

**Comment by zckrs** [comment]
I will look Monday. 😊

**Comment by zckrs** [comment]
@andymagill @dhinterlang can you try to edit in Header.spec.js the line 

`      expect(h1.props.children).toBe('todos');`

to

`      expect(h1.props.children).toBe('YO');`

**Comment by dhinterlang** [comment]
Hello @zckrs,

I made the change and I got the error saying it expected todos and got YO.

I then reverted back to todos and the test passed successfully.

I'll make a note here, that after playing with this project, I started
another project where I installed browser-sync globally, could this
potentially have an impact? Sorry, I'm rather new to all this.
