### ISSUE TITLE
yo: command not found (Vagrant / Homestead 5.0)

### ISSUE THREAD

**Issue by onebrightlight** [yeoman/yeoman#1624]
Hey there,

I'm running into a problem with accessing Yeoman after installing it on a fresh Homestead installation. Everything seems fine during the install after `npm install -g yo` and `yo doctor` runs just fine and finds no problem during the installation. However, after I've installed yeoman, `yo: command not found` is the error message I'm getting on my VM.

```
vagrant@homestead:~$ npm install -g yo
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
/home/vagrant/.node/bin/yo -> /home/vagrant/.node/lib/node_modules/yo/lib/cli.js
/home/vagrant/.node/bin/yo-complete -> /home/vagrant/.node/lib/node_modules/yo/lib/completion/index.js

> spawn-sync@1.0.15 postinstall /home/vagrant/.node/lib/node_modules/yo/node_modules/spawn-sync
> node postinstall


> yo@1.8.4 postinstall /home/vagrant/.node/lib/node_modules/yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version
✔ NODE_PATH matches the npm root

Everything looks all right!
/home/vagrant/.node/lib
└─┬ yo@1.8.4
  ├── async@1.5.2
  ├─┬ chalk@1.1.3
  │ ├── ansi-styles@2.2.1
  │ ├── escape-string-regexp@1.0.5
  │ ├── has-ansi@2.0.0
  │ ├── strip-ansi@3.0.1
  │ └── supports-color@2.0.0
  ├── cli-list@0.1.8
[[REMOVED FOR READABILITY]]
  └─┬ yosay@1.2.0
    ├── cli-boxes@1.0.0
    ├── pad-component@0.0.1
    ├─┬ taketalk@1.0.0
    │ ├── get-stdin@4.0.1
    │ └── minimist@1.2.0
    └── wrap-ansi@2.0.0

vagrant@homestead:~$ yo
yo: command not found
```

My path in `~/.bashrc` says the following: `PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/home/vagrant/.node/lib`

Is there anything else that I'm missing here that might be causing this?

**Comment by SBoudrias** [comment]
Please ask support questions on StackOverflow.

**Comment by onebrightlight** [comment]
Sure thing! Perhaps you should change your documentation on your website, as this is where the link for

> For issues with the Yeoman binary, such as being unable to run Yeoman at all you should submit a bug ticket to the [Yeoman issue tracker](https://github.com/yeoman/yeoman/issues) for further help.

**Comment by heshamelmasry77** [comment]
iam having the same problem

**Comment by mischah** [comment]
Please ask support questions on [gitter](https://gitter.im/yeoman/yeoman).

**Comment by chenchienhao** [comment]
Try: 

> export PATH=/home/vagrant/.node/bin:$PATH
