### ISSUE TITLE
unable to install yeoman in windows 7 64bit OS

### ISSUE THREAD

**Issue by sachacoder** [yeoman/yeoman#1627]
Hi,

I'm unable to install yeomen with latest version of node, npm and grunt-cli. 
npm 3.10.5
node v4.4.7
grunt-cli v1.2.0

Please help!

C:\Users\username>npm install -g yo
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Redirection\\username\\AppData\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "yo"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! path C:\Users\Redirection\username\AppData\npm\node_modules\yo
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\Redirection\username\AppData\npm\node_modules\yo' -> 'C:\Users\Redirection\username\AppData\npm\node_modules\.yo.DELETE'
npm ERR!     at moveAway (C:\Users\Redirection\username\AppData\npm\node_modules\npm\lib\install\action\finalize.js:38:5)
npm ERR!     at destStatted (C:\Users\Redirection\username\AppData\npm\node_modules\npm\lib\install\action\finalize.js:27:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:82:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\Redirection\username\AppData\npm\node_modules\yo' -> 'C:\Users\Redirection\username\AppData\npm\node_modules\.yo.DELETE'
npm ERR!     at Error (native)
npm ERR!  [Error: EPERM: operation not permitted, rename 'C:\Users\Redirection\username\AppData\npm\node_modules\yo' -> 'C:\Users\Redirection\username\AppData\npm\node_modules\.yo.DELETE']
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\username\npm-debug.log

**Comment by neilhem** [comment]
`npm ERR! Please try running this command again as root/Administrator.` looks like you should install yeoman with admin rights. Support questions like this should be asked in [stackoverflow](http://stackoverflow.com)
