### ISSUE TITLE
Extending custom generator and calling lifecycle methods

### ISSUE THREAD

**Issue by niksy** [yeoman/yeoman#1628]
I have a custom generator which I would like to extend, but when I extend it and call super methods, they are executed, but their corresponding actions are not (e.g. writing method is executed but nothing gets written on file system).

Here is the code:

```js
var Base = require('./custom-generator');

module.exports = Base.extend({

	initializing: function () {
		Base.prototype.initializing.apply(this, arguments);
	},

	prompting: function () {
		Base.prototype.prompting.apply(this, arguments);
	},

	writing: function () {
		Base.prototype.writing.apply(this, arguments);
	},

	install: function () {
		Base.prototype.install.apply(this, arguments);
	}

});
```

All these methods are defined in `./custom-generator`.

Am I doing something wrong? Is this the right approach to extending custom generator or should I use `composeWith` approach?

**Comment by niksy** [comment]
Found the solution - my `sourceRoot` wasn’t properly set.

**Comment by codekraft-studio** [comment]
@niksy can u explain?
i've a similar problem, I created a custom generator by extending the Generator class and than I want to use it to have common methods called, like contructor, end, ...
But the methods never get called from the "child" generator, can u help?
Sorry if I ask to you but I don't want to open a issue for that. :)

**custom-generator.js**
```javascript
var Generator = require('yeoman-generator');
module.exports = Generator.extend({

  constructor: function (args, opts) {
    Generator.apply(this, arguments);
    this.argument('appname', { type: String, required: true });
  },

  end: function() {
    this.log('Ciao Ciao!');
  }
});
```

**other-generator.js**
```javascript
var generator = require('./generator.js');
module.exports = generator.extend({
 prompt: function(){ // some code },
 writing: function(){ // some code }
});
```

**Comment by SBoudrias** [comment]
@codekraft-studio inherited methods are not run within the run loop.

> each function on the object returned by `Object.getPrototypeOf(Generator)` will be automatically run.

from http://yeoman.io/authoring/running-context.html

Inherited properties aren't found by `getPrototypeOf`.

A work around is to directly set the method on the children generator:

```js
var generator = require('./generator.js');
module.exports = generator.extend({
  end: generator.prototype.end
});
```

**Comment by codekraft-studio** [comment]
@SBoudrias awesome! Many thanks!
