### ISSUE TITLE
Consider a Synchronous version of `this.spawnCommand`

### ISSUE THREAD

**Issue by gaurav21r** [yeoman/yeoman#1629]
As mentioned in https://github.com/yeoman/generator/issues/545 `this.spawnCommand` is an extendion of Node's `spawn`. I've noticed a few issues with `this.spawnCommand` and here are my thoughts:

1. It is asynchronous and does not play well with the rest of the abstractions of Yeoman `this.config.get`, `this.fs.read` etc.

2. It does not return a callback nor a promise, so like what was described in https://github.com/yeoman/generator/issues/545 we need to listen for an `event`. And therefore, we can't use `this.async()` nor can we return a `Promise`, can we?
 
3. Yeoman already provides a lot of abstractions on top of popular tools / modules like `fs`, `grunt`, `gulp`, `inquirer` `grouped-queue` etc. Why not use a synchronous version of this? This seems to be possible in node -> http://stackoverflow.com/questions/4443597/node-js-execute-system-command-synchronously.

Note: I am on the latest version of Yeoman

**EDIT** As a side note, my specific use case is to call `apm install` (Atom Plugin Manager) only **after** I call `this.installDependencies()` and then I call another command which should execute only **after** `apm install`

**Comment by SBoudrias** [comment]
`spawnCommandSync` already exists: https://github.com/yeoman/generator/blob/master/lib/actions/spawn_command.js#L30

**Comment by gaurav21r** [comment]
Thank you @SBoudrias for your response! Seemed I missed it from here http://yeoman.io/generator/actions_spawn_command.html :disappointed: 

Do you think its a good idea to include the `sync` version of the command in the reference guide / tutorial given in yeoman.io ? I think it'll just work well with everything else being synchronous.

Also is there a sync version of `installDependencies`. My specific use case warrants the need for it. This time I checked http://yeoman.io/generator/actions_install.html :stuck_out_tongue: ! It says we shouldn't use `this.async()`

**Comment by SBoudrias** [comment]
@gaurav21r please send a PR improving our documentation, I'll be glad to merge it!

There's no sync command for install commands because that's not a pattern we recommend. `installDependencies` gets merge with every other generator running so it only run once for every projects.
