### ISSUE TITLE
Some parameters are not passed from generator-fountain-webapp to generator-fountain-angular1

### ISSUE THREAD

**Issue by otexier** [yeoman/yeoman#1630]
Hi,

I encounter an issue trying to generate a project with command line only (no user interaction because it is done in continous integration)

When I install fountain with 

`npm install -g generator-fountain-webapp@0.7.2`

And then I do

`yo fountain-webapp --skip-install --framework=angular1 --modules=inject --js=js --css=scss --html --ci=jenkins --sample=hello --router=uirouter`

Yeoman asks for sample and router, I have to chose hello and ui router. The others parameters are fine.

It is a problem for me. I don't want user interaction.

But if I install with

`npm install -g generator-fountain-angular1@0.7.2`

And I use the same command line

`yo fountain-webapp --skip-install --framework=angular1 --modules=inject --js=js --css=scss --html --ci=jenkins --sample=hello --router=uirouter`

My app is created with no questions asked. That's great.

How can I achieve that when installing module generator-fountain-webapp only ?

Thanks for your great tool and your time

**Comment by 876843240** [comment]
e....could you try to remove some you don't need parameters?

**Comment by SBoudrias** [comment]
Hi @otexier please open this issue on the repository of the generator you're using.

This particular issue tracker is for general concern with the Yeoman ecosystem - the core team doesn't offer support for third party generators. So you'll have a better chance of getting an answer on generator-fountain-webapp repository.

**Comment by otexier** [comment]
Oups !

Of course that's note the good project, it's not a Yeoman issue, but a FountainJS issue.
I don't know how I managed to post it here.

Sorry guys.
