### ISSUE TITLE
Yeoman.io/generators/  page won't load generatores

### ISSUE THREAD

**Issue by ASidlinskiy** [yeoman/yeoman#1631]
@[Yeoman.io/generators/](http://yeoman.io/generators/) won't load any generators but generates `'Uncaught TypeError: a.sort is not a function` error in the console. @theshortcut @hemanth

**Comment by Munter** [comment]
Works for me. Was this a temporary issue?

**Comment by kevva** [comment]
Works for me too.

**Comment by ASidlinskiy** [comment]
It works now.
