### ISSUE TITLE
yeoman.io/generators outdated

### ISSUE THREAD

**Issue by diegohaz** [yeoman/yeoman#1633]
I've noticed that some generators aren't getting updated on the generators page. I have a generator called [generator-rest](https://github.com/diegohaz/generator-rest) and the last update on the page was 3 days ago, even though I published a new version yesterday.

I don't know if it's the default behaviour though.

**Comment by eddiemonge** [comment]
Sometimes it takes awhile and sometime i have to kick it. That list is controlled by https://github.com/yeoman/yeoman-generator-list

**Comment by diegohaz** [comment]
Thank you for the answer. Can I do something to force this update?
