### ISSUE TITLE
broken link on yeoman.io "testing" page

### ISSUE THREAD

**Issue by grawk** [yeoman/yeoman#1638]
On the page at this URL: http://yeoman.io/authoring/testing.html

> "You can check the `full helpers API here`. These methods will usually be run inside a before block."

That URL, found on the , http://yeoman.io/generator/module-test_helpers.html, produces a 404 error.

**Comment by SBoudrias** [comment]
Oh, the link should be https://github.com/yeoman/yeoman-test - if you wanna send a PR fix.

**Comment by grawk** [comment]
Oh yeah definitely! Sorry didn't see immediately where the website branch was. Found it.
