### ISSUE TITLE
Error: Can't resolve 'fs' 

### ISSUE THREAD

**Issue by Merlyn007** [yeoman/yeoman#1639]
Im trying to use Webtorrent.

I installed it by:
npm install webtorrent --save

So then when I do NPM RUN SERVE in my application it gives me this error:

ERROR in ./~/webtorrent/lib/torrent.js
Module not found: Error: Can't resolve 'fs' in '/Users/macbook-lucas/refreex/node_modules/webtorrent/lib'
 @ ./~/webtorrent/lib/torrent.js 13:9-22
 @ ./~/webtorrent/index.js
 @ ./src/app/playlist/playlist.js
 @ ./src/app/playlist/index.js
 @ ./src/index.js

ERROR in ./~/create-torrent/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/macbook-lucas/refreex/node_modules/create-torrent'
 @ ./~/create-torrent/index.js 22:9-22
 @ ./~/webtorrent/index.js
 @ ./src/app/playlist/playlist.js
 @ ./src/app/playlist/index.js
 @ ./src/index.js

ERROR in ./~/parse-torrent/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/macbook-lucas/refreex/node_modules/parse-torrent'
 @ ./~/parse-torrent/index.js 7:9-22
 @ ./~/webtorrent/index.js
 @ ./src/app/playlist/playlist.js
 @ ./src/app/playlist/index.js
 @ ./src/index.js

ERROR in ./~/pump/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/macbook-lucas/refreex/node_modules/pump'
 @ ./~/pump/index.js 3:9-22
 @ ./~/webtorrent/lib/torrent.js
 @ ./~/webtorrent/index.js
 @ ./src/app/playlist/playlist.js
 @ ./src/app/playlist/index.js
 @ ./src/index.js

ERROR in ./~/is-file/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/macbook-lucas/refreex/node_modules/is-file'
 @ ./~/is-file/index.js 3:9-22
 @ ./~/create-torrent/index.js
 @ ./~/webtorrent/index.js
 @ ./src/app/playlist/playlist.js
 @ ./src/app/playlist/index.js
 @ ./src/index.js

Why Im having error with fs?? I try install it via npm but nothing like this:
npm install fs --save

but nothing.

Do you have any idea? i post here beacause there is no reddit or discus.

Thanks

**Comment by SBoudrias** [comment]
`fs` is a core node module https://nodejs.org/dist/latest-v6.x/docs/api/fs.html

Nothing to do with Yeoman. Are you running on Node?

**Comment by Merlyn007** [comment]
Yes I know the fact that fs is a core node module, and i know that is only a dummy package..

This package name is not currently in use, but was formerly occupied
by another package. To avoid malicious use, npm is hanging on to the
package name, but loosely, and we'll probably give it to you if you
want it.

You may adopt this package by contacting support@npmjs.com and
requesting the name.

So, my question is, why with the other node modules run perfectly and with webtorrent that I installed manually doesnt work ??

Im stuck about 2 days with this.

I use de generator http://fountainjs.io/ (Yeoman)

**Comment by SBoudrias** [comment]
@Merlyn007 maybe check the content of the node_modules and see if a dummy module is installed and shadow the core package?

**Comment by Merlyn007** [comment]
I check te content of the node_modules and it was the fs dummy module, so I deleted it and then i modified the packaje.json for disable this module. Then npm install.

But sadly nothing the error keeps in console
Module not found: Error: Can't resolve 'fs' in '/Users/macbook-lucas/refreex/node_modules/webtorrent/lib'
