### ISSUE TITLE
Press <space> to select

### ISSUE THREAD

**Issue by xcsweb** [yeoman/yeoman#1641]
but,I press "space",I can not select,Windows Environment

**Comment by eddiemonge** [comment]
What generator? What version of yo do you have?

**Comment by SBoudrias** [comment]
Some node version ship with a totally broken readline.

See https://github.com/nodejs/node/issues/5384 for more details. You'll want to try again on latest stable Node.js version.

**Comment by xcsweb** [comment]
I use git bash for windows 7

**Comment by SBoudrias** [comment]
@xcsweb git bash might also not be a proper TTY terminal on windows. Did you try with command.exe or powershell?
