### ISSUE TITLE
this is not an issue only a question

### ISSUE THREAD

**Issue by kalitas** [yeoman/yeoman#1642]
love this project. im ready to upload to aws my first web app however im using node and express and when i copy the dist files from the dist folder to the public folder in my express app all the resources have bad path.
the correct path in the dist is: /public/scripts/vendor.3e7967d7.js
and the correct path in dev is: /scripts/vendor.3e7967d7.js
so how can i configure that when run the command grunt dist (or grunt), the path would be /public and when i run grunt serve the path would be without the /public

**Comment by eddiemonge** [comment]
why is it running from public? Sounds like your express isnt configured correctly. You can change usemin to have the correct path, either with an option or change the path in your `<!-- build:....` line.

**Comment by kalitas** [comment]
Hi @eddiemonge thanks for the answer. you are right something is wrong with my express configuration. i downloaded the parse-platform [https://github.com/ParsePlatform/parse-server-example](url) and put the content of the dist folder inside the public directory. after your answer I understood that its not right to manage the code in one place and when its ready to deploy by copy the dist files to the public folder of the parse-server-example express app. So I wonder how can i migrate my yeoman app to this express app and keep using the wonderful generators in the gruntfile.js?

**Comment by kalitas** [comment]
Anyway I found a solution for my problem: `app.use(express.static('public'));`
then you dont need to change nothing in the grunt or usemin, because the express deal with it like:
localhost:5858/images, even though the absolute path of the images folder is /public/images...
