### ISSUE TITLE
Problem when I run yo on OSX El Capitan

### ISSUE THREAD

**Issue by DennisBoanini** [yeoman/yeoman#1643]
I've installed yeoman with this command
`sudo npm install -g yo`
but, when I try to run yo I receive this error
`wks-gtomberli:~ FrancescoMoresi$ yo`
`/usr/local/lib/node_modules/yo/node_modules/update-notifier/index.js:24
throw new Error('pkg.name and pkg.version required');
^
Error: pkg.name and pkg.version required
at new UpdateNotifier (/usr/local/lib/node_modules/yo/node_modules/update-no
tifier/index.js:24:9)
at module.exports (/usr/local/lib/node_modules/yo/node_modules/update-notifi
er/index.js:108:23)
at resolveGenerators (/usr/local/lib/node_modules/yo/lib/router.js:74:18)
at /usr/local/lib/node_modules/yo/node_modules/lodash/index.js:2874:23
at /usr/local/lib/node_modules/yo/node_modules/lodash/index.js:3073:15
at baseForOwn (/usr/local/lib/node_modules/yo/node_modules/lodash/index.js:2
046:14)
at /usr/local/lib/node_modules/yo/node_modules/lodash/index.js:3043:18
at Function.<anonymous> (/usr/local/lib/node_modules/yo/node_modules/lodash/
index.js:3346:13)
at Router.updateAvailableGenerators (/usr/local/lib/node_modules/yo/lib/rout
er.js:83:5)
at runYo (/usr/local/lib/node_modules/yo/lib/cli.js:158:10)`

**Comment by mischah** [comment]
What is the output if you run `yo doctor`?

**Comment by DennisBoanini** [comment]
Now work. Thanks

**Comment by DanJ210** [comment]
I'm getting this error now on Windows when I have been using Yeomin before. It was working at first but now all of a sudden I get the above "throw new Error('pkg.name and pkg.version required')" I've ran yo doctor which says everything is good, tried reinstalling yeoman, tried updating npm and node.js. I can use npm no problem.

I'm using Windows. As of now Yeoman no longer works for me and I don't know if I should try reinstalling everything which would be a pain or just give up.

Not sure if I should open a new issue or not either.

**Comment by SBoudrias** [comment]
@DanJ210 did you try `yo doctor`? And did you try updating yo?

**Comment by DanJ210** [comment]
Yes. My original post says I did run yo `yo doctor` and everything came out as good. I've also installed yo a few times and it says it installs.

**Comment by DanJ210** [comment]
Even when I try to scaffold out a project directly. It will go through the "install process" but nothing is ever created in the folder.

**Comment by SBoudrias** [comment]
What's your node version? Can you share the content of the package.json in the folder where yo is installed?

**Comment by DanJ210** [comment]
Node is v6.9.4, 

I went through the update process yesterday throughout the FAQ's online. I'm still somewhat a relative newbie to all of this so I really have no idea about where the package.json of yo is installed. I install yo globally and that's all I know that's happening. I've looked through the installation of VSCode in Program Files and cannot find where yo is installed. I find extensions but not something like yo. Neither is it in node_modules... 

Where could I find this package.json of yo?

**Comment by SBoudrias** [comment]
@DanJ210 the path is shown in the traceback of the error you screenshotted `C:\djackson\...\node_modules\yo`

**Comment by DanJ210** [comment]
Ok thanks for pointing that out. I've posted the entire contents below.

`{
  "_args": [
    [
      {
        "raw": "yo",
        "scope": null,
        "escapedName": "yo",
        "name": "yo",
        "rawSpec": "",
        "spec": "latest",
        "type": "tag"
      },
      "C:\\Users\\djackson\\Source\\Repos"
    ]
  ],
  "_from": "yo@latest",
  "_id": "yo@1.8.5",
  "_inCache": true,
  "_location": "/yo",
  "_nodeVersion": "6.3.1",
  "_npmOperationalInternal": {
    "host": "packages-12-west.internal.npmjs.com",
    "tmp": "tmp/yo-1.8.5.tgz_1472703392595_0.8789802109822631"
  },
  "_npmUser": {
    "name": "sboudrias",
    "email": "admin@simonboudrias.com"
  },
  "_npmVersion": "3.10.3",
  "_phantomChildren": {},
  "_requested": {
    "raw": "yo",
    "scope": null,
    "escapedName": "yo",
    "name": "yo",
    "rawSpec": "",
    "spec": "latest",
    "type": "tag"
  },
  "_requiredBy": [
    "#USER"
  ],
  "_resolved": "https://registry.npmjs.org/yo/-/yo-1.8.5.tgz",
  "_shasum": "776ab9ec79a7882f8d4f7a9e10214fdab050d928",
  "_shrinkwrap": null,
  "_spec": "yo",
  "_where": "C:\\Users\\djackson\\Source\\Repos",
  "author": {
    "name": "Yeoman"
  },
  "bin": {
    "yo": "lib/cli.js",
    "yo-complete": "lib/completion/index.js"
  },
  "bugs": {
    "url": "https://github.com/yeoman/yo/issues"
  },
  "dependencies": {
    "async": "^1.0.0",
    "chalk": "^1.0.0",
    "cli-list": "^0.1.1",
    "configstore": "^1.0.0",
    "cross-spawn": "^3.0.1",
    "figures": "^1.3.5",
    "fullname": "^2.0.0",
    "got": "^5.0.0",
    "humanize-string": "^1.0.0",
    "inquirer": "^0.11.0",
    "insight": "^0.7.0",
    "lodash": "^3.2.0",
    "meow": "^3.0.0",
    "npm-keyword": "^4.1.0",
    "opn": "^3.0.2",
    "package-json": "^2.1.0",
    "parse-help": "^0.1.1",
    "read-pkg-up": "^1.0.1",
    "repeating": "^2.0.0",
    "root-check": "^1.0.0",
    "sort-on": "^1.0.0",
    "string-length": "^1.0.0",
    "tabtab": "^1.3.0",
    "titleize": "^1.0.0",
    "update-notifier": "^0.6.0",
    "user-home": "^2.0.0",
    "yeoman-character": "^1.0.0",
    "yeoman-doctor": "^2.0.0",
    "yeoman-environment": "^1.6.1",
    "yosay": "^1.0.0"
  },
  "description": "CLI tool for running Yeoman generators",
  "devDependencies": {
    "gulp": "^3.6.0",
    "gulp-coveralls": "^0.1.0",
    "gulp-eslint": "^2.0.0",
    "gulp-exclude-gitignore": "^1.0.0",
    "gulp-istanbul": "^0.10.4",
    "gulp-mocha": "^2.0.0",
    "gulp-nsp": "^2.1.0",
    "gulp-plumber": "^1.0.0",
    "mocha": "^2.1.0",
    "mockery": "^1.4.0",
    "nock": "^8.0.0",
    "nsp": "^2.2.0",
    "proxyquire": "^1.0.1",
    "registry-url": "^3.0.0",
    "sinon": "^1.12.1"
  },
  "directories": {},
  "dist": {
    "shasum": "776ab9ec79a7882f8d4f7a9e10214fdab050d928",
    "tarball": "https://registry.npmjs.org/yo/-/yo-1.8.5.tgz"
  },
  "engines": {
    "node": ">=0.12.0"
  },
  "files": [
    "lib"
  ],
  "gitHead": "3be725bd6376ead2c593741da2d374082f673b05",
  "homepage": "http://yeoman.io",
  "keywords": [
    "cli-app",
    "cli",
    "front-end",
    "development",
    "dev",
    "build",
    "web",
    "tool",
    "scaffold",
    "stack",
    "yeoman",
    "generator",
    "generate",
    "app",
    "boilerplate"
  ],
  "license": "BSD-2-Clause",
  "main": "lib",
  "maintainers": [
    {
      "name": "sindresorhus",
      "email": "sindresorhus@gmail.com"
    },
    {
      "name": "paulirish",
      "email": "paul.irish@gmail.com"
    },
    {
      "name": "addyosmani",
      "email": "addyosmani@gmail.com"
    },
    {
      "name": "eddiemonge",
      "email": "eddie+npm@eddiemonge.com"
    },
    {
      "name": "passy",
      "email": "phartig@rdrei.net"
    },
    {
      "name": "sboudrias",
      "email": "admin@simonboudrias.com"
    },
    {
      "name": "arthurvr",
      "email": "contact@arthurverschaeve.be"
    }
  ],
  "name": "yo",
  "optionalDependencies": {},
  "readme": "# yo [![npm](https://badge.fury.io/js/yo.svg)](http://badge.fury.io/js/yo) [![Build Status](https://travis-ci.org/yeoman/yo.svg?branch=master)](https://travis-ci.org/yeoman/yo) [![Coverage Status](https://coveralls.io/repos/yeoman/yo/badge.svg)](https://coveralls.io/r/yeoman/yo) [![](https://img.shields.io/badge/unicorn-approved-ff69b4.svg)](https://www.youtube.com/watch?v=9auOCbH5Ns4) [![Gitter](https://img.shields.io/badge/Gitter-Join_the_Yeoman_chat_%E2%86%92-00d06f.svg)](https://gitter.im/yeoman/yeoman) [![OpenCollective](https://opencollective.com/yeoman/badge/backers.svg)](https://opencollective.com/yeoman#support)\n\n[![](https://raw.githubusercontent.com/yeoman/media/master/optimized/yeoman-masthead.png)](http://yeoman.io)\n\n<img src=\"screenshot.png\" width=\"569\">\n\n\n## What's Yeoman?\n\nYeoman helps you to kickstart new projects, prescribing best practices and tools to help you stay productive.\n\nTo do so, we provide a [generator ecosystem](http://yeoman.io/generators/). A generator is basically a plugin that can be run with the `yo` command to scaffold complete projects or useful parts.\n\n\n## Usage\n\n```sh\n# install yo\nnpm install --global yo\n\n# install a generator\nnpm install --global generator-webapp\n\n# run it\nyo webapp\n```\n\n*To create and distribute your own generator, refer to [our official documentation](http://yeoman.io/authoring/)*\n\n\n## Options\n\n- `--no-color` - Disable colors.\n- `--version` - Print the current `yo` version.\n- `--help` - Print `yo` help menu with the list of found generators.\n- `--[no-]insight` - Toggle anonymous [Insight](https://github.com/yeoman/insight) tracking which helps us improve Yeoman. Using either of these flags on the first run will prevent you from being prompted about it interactively. The flags can also be used to change it later on.\n- `--generators` - Print available generators.\n\n\n## Troubleshooting\n\nRunning `yo doctor` command can help you troubleshoot common issues.\n\nIf `doctor` doesn't help, then check opened issues for a similar problem. Open a new issue if your problem haven't been reported yet. Make sure to always include the version of `yo` (`yo --version`) and Node.js (`node --version`) you use.\n\nIf your issue only occurs using a generator, please report the issues on the generator's repository.\n\n\n## Contribute\n\nSee the [contributing docs](http://yeoman.io/contributing/).\n\n\n## Changelog\n\nSee the [release page](https://github.com/yeoman/yo/releases).\n\n## Backers\nLove Yeoman work and community? Help us keep it alive by donating funds to cover project expenses! <br />\n[[Become a backer](https://opencollective.com/yeoman#support)]\n\n  <a href=\"https://opencollective.com/yeoman/backers/0/website\" target=\"_blank\">\n    <img src=\"https://opencollective.com/yeoman/backers/0/avatar\">\n  </a>\n  <a href=\"https://opencollective.com/yeoman/backers/1/website\" target=\"_blank\">\n    <img src=\"https://opencollective.com/yeoman/backers/1/avatar\">\n  </a>\n  <a href=\"https://opencollective.com/yeoman/backers/2/website\" target=\"_blank\">\n    <img src=\"https://opencollective.com/yeoman/backers/2/avatar\">\n  </a>\n  <a href=\"https://opencollective.com/yeoman/backers/3/website\" target=\"_blank\">\n    <img src=\"https://opencollective.com/yeoman/backers/3/avatar\">\n  </a>\n  <a href=\"https://opencollective.com/yeoman/backers/4/website\" target=\"_blank\">\n    <img src=\"https://opencollective.com/yeoman/backers/4/avatar\">\n  </a>\n  <a href=\"https://opencollective.com/yeoman/backers/5/website\" target=\"_blank\">\n    <img src=\"https://opencollective.com/yeoman/backers/5/avatar\">\n  </a>\n  <a href=\"https://opencollective.com/yeoman/backers/6/website\" target=\"_blank\">\n    <img src=\"https://opencollective.com/yeoman/backers/6/avatar\">\n  </a>\n  <a href=\"https://opencollective.com/yeoman/backers/7/website\" target=\"_blank\">\n    <img src=\"https://opencollective.com/yeoman/backers/7/avatar\">\n  </a>\n  <a href=\"https://opencollective.com/yeoman/backers/8/website\" target=\"_blank\">\n    <img src=\"https://opencollective.com/yeoman/backers/8/avatar\">\n  </a>\n  <a href=\"https://opencollective.com/yeoman/backers/9/website\" target=\"_blank\">\n    <img src=\"https://opencollective.com/yeoman/backers/9/avatar\">\n  </a>\n  <a href=\"https://opencollective.com/yeoman/backers/10/website\" target=\"_blank\">\n    <img src=\"https://opencollective.com/yeoman/backers/10/avatar\">\n  </a>\n  <a href=\"https://opencollective.com/yeoman/backers/11/website\" target=\"_blank\">\n    <img src=\"https://opencollective.com/yeoman/backers/11/avatar\">\n  </a>\n  <a href=\"https://opencollective.com/yeoman/backers/12/website\" target=\"_blank\">\n    <img src=\"https://opencollective.com/yeoman/backers/12/avatar\">\n  </a>\n  <a href=\"https://opencollective.com/yeoman/backers/13/website\" target=\"_blank\">\n    <img src=\"https://opencollective.com/yeoman/backers/13/avatar\">\n  </a>\n  <a href=\"https://opencollective.com/yeoman/backers/14/website\" target=\"_blank\">\n    <img src=\"https://opencollective.com/yeoman/backers/14/avatar\">\n  </a>\n  <a href=\"https://opencollective.com/yeoman/backers/15/website\" target=\"_blank\">\n    <img src=\"https://opencollective.com/yeoman/backers/15/avatar\">\n  </a>\n  <a href=\"https://opencollective.com/yeoman/backers/16/website\" target=\"_blank\">\n    <img src=\"https://opencollective.com/yeoman/backers/16/avatar\">\n  </a>\n  <a href=\"https://opencollective.com/yeoman/backers/17/website\" target=\"_blank\">\n    <img src=\"https://opencollective.com/yeoman/backers/17/avatar\">\n  </a>\n  <a href=\"https://opencollective.com/yeoman/backers/18/website\" target=\"_blank\">\n    <img src=\"https://opencollective.com/yeoman/backers/18/avatar\">\n  </a>\n  <a href=\"https://opencollective.com/yeoman/backers/19/website\" target=\"_blank\">\n    <img src=\"https://opencollective.com/yeoman/backers/19/avatar\">\n  </a>\n  <a href=\"https://opencollective.com/yeoman/backers/20/website\" target=\"_blank\">\n    <img src=\"https://opencollective.com/yeoman/backers/20/avatar\">\n  </a>\n  <a href=\"https://opencollective.com/yeoman/backers/21/website\" target=\"_blank\">\n    <img src=\"https://opencollective.com/yeoman/backers/21/avatar\">\n  </a>\n  <a href=\"https://opencollective.com/yeoman/backers/22/website\" target=\"_blank\">\n    <img src=\"https://opencollective.com/yeoman/backers/22/avatar\">\n  </a>\n  <a href=\"https://opencollective.com/yeoman/backers/23/website\" target=\"_blank\">\n    <img src=\"https://opencollective.com/yeoman/backers/23/avatar\">\n  </a>\n  <a href=\"https://opencollective.com/yeoman/backers/24/website\" target=\"_blank\">\n    <img src=\"https://opencollective.com/yeoman/backers/24/avatar\">\n  </a>\n  <a href=\"https://opencollective.com/yeoman/backers/25/website\" target=\"_blank\">\n    <img src=\"https://opencollective.com/yeoman/backers/25/avatar\">\n  </a>\n  <a href=\"https://opencollective.com/yeoman/backers/26/website\" target=\"_blank\">\n    <img src=\"https://opencollective.com/yeoman/backers/26/avatar\">\n  </a>\n  <a href=\"https://opencollective.com/yeoman/backers/27/website\" target=\"_blank\">\n    <img src=\"https://opencollective.com/yeoman/backers/27/avatar\">\n  </a>\n  <a href=\"https://opencollective.com/yeoman/backers/28/website\" target=\"_blank\">\n    <img src=\"https://opencollective.com/yeoman/backers/28/avatar\">\n  </a>\n  <a href=\"https://opencollective.com/yeoman/backers/29/website\" target=\"_blank\">\n    <img src=\"https://opencollective.com/yeoman/backers/29/avatar\">\n  </a>\n\n\n## License\n\nBSD-2-Clause © Google\n",
  "readmeFilename": "readme.md",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/yeoman/yo.git"
  },
  "scripts": {
    "postinstall": "yodoctor",
    "postupdate": "yodoctor",
    "prepublish": "gulp prepublish",
    "test": "gulp"
  },
  "tabtab": {
    "yo": [
      "-f",
      "--force",
      "--version",
      "--no-color",
      "--no-insight",
      "--insight",
      "--generators"
    ]
  },
  "version": "1.8.5"
}
`

**Comment by DanJ210** [comment]
Here is the zip of it since the above is so wild.

[package.json](https://github.com/yeoman/yeoman/files/947732/package.zip)

**Comment by DanJ210** [comment]
@SBoudrias Any ideas at all? Appreciate the time.

**Comment by SBoudrias** [comment]
Not really any idea at the moment... @DennisBoanini what fixed it for you?

**Comment by DanJ210** [comment]
Is there any real way to remove it and reinstall completely? I can reinstall it as many times as I want but it does nothing and doctor says it's all good.

**Comment by DanJ210** [comment]
@SBoudrias @DennisBoanini Anyone ever get anywhere? Still can't use yo. If I remove the files manually is that completely removing it for a fresh install?

**Comment by SBoudrias** [comment]
I think I've been very responsive helping you fix that issue. Now it didn't work and I'm short on ideas to help you further. Not exactly top priority at the moment given it doesn't affect other user.

I'm maintaining and helping Yeoman's user for free here. I don't owe you anything. Thanks for understanding.

**Comment by DanJ210** [comment]
@SBoudrias My apologies if I gave the impression that you owed me something or haven't been responsive enough. I don't know your background or any reasons for your place here. All I did was come here like suggested in Yeoman's support pages.

Just to be clear... The only thing I've been suggested to do was use `yo doctor` and then share my project.json file which I did but never got any feedback on. I haven't been rude about it either. Then I've been asking if there was a way to remove Yeoman completely and start over without breaking anything further, suggesting that I'm working a solution on my own to help.

Sounds like it's best I reach someone else. I appreciate your time.

**Comment by DanJ210** [comment]
And just to be fair... I may not be the only one with this issue as the OP above seems to have had the same issue.

**Comment by kuyoonjo** [comment]
Hi, it may be late. I got the same issue. Try list out all generators you installed and remove them.

**Comment by bnheise** [comment]
Same issue here.

**Comment by bnheise** [comment]
I was able to solve it by using NVM to switch to lts/erbium and then installing yeoman again (without installing first). I have no idea why switching to erbium had any effect by it seems to have worked.

**Comment by eamodio** [comment]
Same issue here. I've tried `yo doctor` says everything is fine. I've uninstalled all the generators, yo, etc -- and nuked my local and roaming npm-cache and still get the same issue.
