### ISSUE TITLE
2 yeoman paths

### ISSUE THREAD

**Issue by heinhoang** [yeoman/yeoman#1645]
wins 8
node -v
v6.9.1
npm -v
3.10.8
yo --version
1.7.0

I try to update to yo 1.8 using command: `npm -g install yo@1.8.5`
but then I check yo --version, it remains 1.7.0
then I check:

`where npm`
C:\Program Files\nodejs\npm
C:\Program Files\nodejs\npm.cmd

`where yo`
C:\Users\Hein Hoang\AppData\Roaming\npm\yo
C:\Users\Hein Hoang\AppData\Roaming\npm\yo.cmd

but the command npm -g install yo@1.8.5 installed yo at 
 yo@1.8.5 postinstall C:\usr\local\node_modules\yo

how to point yo from C:\Users\Hein Hoang\AppData\Roaming\npm\yo to C:\usr\local\node_modules\yo? is it good to do so?

**Comment by SBoudrias** [comment]
Looks like you have two npm installed adding packages in different folders.

Also, I'd guess your PATH variable points to the AppDate folder by default, and not to the `local/node_modules` one.

**Comment by mischah** [comment]
Not a windows user here. But it seems to be a »global npm on windows issue« and is not related to Yeoman only.

A quick interweb search should lead you to a solution:
https://www.google.de/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=windows%20npm%20global%20path
