### ISSUE TITLE
Say allo' to Michael joining the Yeoman core team

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/yeoman#1646]
@mischah has been an [active contributor](https://github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Amischah+user%3Ayeoman+) to many core part of Yeoman now. Given all his help, it is only natural to invite him to join our core team and be an even more active part of the Yeoman community.

Thanks for all your hard work!

(Please send a PR adding your information to the contributors section of this repo readme and on https://yeoman.io)

**Comment by hemanth** [comment]
Congrats and welcome to Michael Kühnel! 👍

**Comment by sindresorhus** [comment]
✨🎉✨

**Comment by mischah** [comment]
Whoop Whoop. Thanks. 💖
PRs will follow 😊

**Comment by mischah** [comment]
PRs are done 😗 

- https://github.com/yeoman/yeoman/pull/1647
- https://github.com/yeoman/yeoman.github.io/pull/694

**Comment by mischah** [comment]
Question to all team members: How do you communicate beside Github issues? 

I thought about creating an internal Gitter room like this:
![image](https://cloud.githubusercontent.com/assets/441011/20525527/28e549fe-b0c0-11e6-972b-73951826effb.png)

Or is there any IRC channel or something?

**Comment by DerZyklop** [comment]
Yeah! \o/

**Comment by arthurvr** [comment]
Welcome! ❤️

**Comment by mischah** [comment]
Thanks :yellow_heart:
