### ISSUE TITLE
How to communicate in the core team?

### ISSUE THREAD

**Issue by mischah** [yeoman/yeoman#1648]
Hej there,

question to all @yeoman team members: How do you communicate beside Github issues? 

I thought about creating an internal Gitter room like this:
![image](https://cloud.githubusercontent.com/assets/441011/20525527/28e549fe-b0c0-11e6-972b-73951826effb.png)

Or is there any IRC channel or something?

Yours, Michael

**Comment by SBoudrias** [comment]
Contacted you in private :)
