### ISSUE TITLE
Welcome Mehdy Dara to Yeoman core team

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/yeoman#1649]
You probably know @zckrs as the author of the our new codelab. But [he's been active](https://github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Azckrs+user%3Ayeoman+) for a while!

He's had commit permission on our repo for a few months now, but we never officially welcomed him! So welcome, we count ourselves lucky to have you as a contributor and look forward to what we can still accomplish together!

(Please send a PR adding your information to the contributors section of this repo readme and on https://yeoman.io)

**Comment by mischah** [comment]
Whoop :tada:

I know @zckrs as the one who fixed the generator list 😍

**Comment by sindresorhus** [comment]
![welcome](https://cloud.githubusercontent.com/assets/170270/20554485/e2f6c48e-b18e-11e6-9ffa-803fa9d56e54.gif)

**Comment by ragingwind** [comment]
👍 Welcome! 🎉

**Comment by zckrs** [comment]
:tada: :rabbit: :tada: 

Thanks :heartpulse: 

PR landed!
https://github.com/yeoman/yeoman.github.io/pull/695 
https://github.com/yeoman/yeoman/pull/1650

**Comment by mischah** [comment]
💖  PRs merged 💖
