### ISSUE TITLE
Yo & Facebook's flux issue? 

### ISSUE THREAD

**Issue by micahstartnow** [yeoman/yeoman#1656]
It appears YO is corrupted? 

I can successfully run -> npm install -g yo and it returns
Everything looks all right!

yet something triggered and the yo command now returns 

'yo' is not recognized as an internal or external command, operable program or batch file.

I think it started happening after I installed Facebook's npm flux package.

I don't know if I should have avoided doing that? If that is even relative... If I'm missing something easy...
Thanks

**Comment by SBoudrias** [comment]
Your npm binaries needs to be in your system `PATH` environment variable.
