### ISSUE TITLE
[Feature Request?]Scaffolding controller using yo aspnet:mvccontroller  

### ISSUE THREAD

**Issue by ssjsk** [yeoman/yeoman#1657]
Hello Yeoman team,
First of all, thank you for great work you guys are doing.

I'm still learning ASP.NET Core and yo aspnet is my preferred generator as of now, pardon my lack of awareness about your roadmap/issue list in case it's already being addressed or going to be.

I was trying to generate MVC Controller with scaffolding based on model class using yeoman generator in ASP.NET Core on OSx, using Visual Studio Code. On Windows+Visual Studio 2015 with MVC 6, screen for scaffolding a controller with model would look like screenshot ( https://s27.postimg.org/ipfpqhvoj/Screen_Shot_2016_12_26_at_6_12_11_PM.png ) I assume, but it's not there on OSx. When I use yo aspnet:mvccontroller ControllerClassName I get a controller but it doesn't create CRUD Views or db migration. Is there any other generator switch that I'm missing? I didn't find much information on yeoman.io including its github.

**Comment by SBoudrias** [comment]
Hi, the Yeoman team doesn't maintains generator-aspnet. You should ask the maintainers your question directly https://github.com/OmniSharp/generator-aspnet
