### ISSUE TITLE
Yeoman search not working

### ISSUE THREAD

**Issue by cassidoo** [yeoman/yeoman#1658]
Tried with multiple browsers, the search function isn't working on the site.

Here's the console output when I try to use it:
![image](https://cloud.githubusercontent.com/assets/1454517/21952193/d5ae24ac-d9ca-11e6-9049-e3756b48d838.png)

**Comment by SBoudrias** [comment]
@zckrs did we generated broken data in our batch?

**Comment by zckrs** [comment]
I just check. And everything works fine =\

**Comment by cassidoo** [comment]
It works now!  Not sure what happened there.  Thanks friends!

**Comment by labago** [comment]
Just as a note this does not seem to be fixed, I am on http://yeoman.io/generators/ and seeing the exact same behavior

**Comment by zckrs** [comment]
https://registry.npmjs.org/-/_view/byKeyword?startkey=[%22yeoman-generator%22]&endkey=[%22yeoman-generator%22,%7B%7D]&group_level=2 return a timeout page in XML when we try to refresh the list.

That result is a array of 0 element.

I just push a commit who catch this error. 

If you remove your cookie (TTL=30min) on http://yeoman.io/generators/  you should saw the list without error.

**Comment by labago** [comment]
After removing cookies it seems to be working again, thanks for the quick fix!
