### ISSUE TITLE
Wanted a cli-tool to run a Yeoman generator silently

### ISSUE THREAD

**Issue by evil-shrike** [yeoman/yeoman#1660]
Hi.

I needed to integrate one of my generator with some tool (maven archetype). Actually all I needed is an ability to have a config (json) with answers for the generator and run it silently. I easily implemented a custom a node-base tool which creates my generator and run with answers. After I implemented it I came up with an idea to create a generic CLI tool to run arbitrary generator (by name) with a answer file. But I just can't believe that nobody implemented something similar before. 

I searched through npmjs for "yeoman-" but didn't find anything useful. The only package which looks to be related to this problem is [yeoman-prompting-helpers](https://www.npmjs.com/package/yeoman-prompting-helpers) but it uses a different approach.

So let me ask here, does somebody know about a CLI-tool like this?

P.S. BTW it'd be nice to separate all npm packages related to Yeoman itself (helpers/utils/tools and so on) with a tag. Because "yeoman" tag is used by all generators (i.e. packages which use Yeoman but not extend).

**Comment by SBoudrias** [comment]
I don't think using a generator as part of a build process is as common as you assume. For most people, Yeoman is a local tool.

FWIW, you should read [this guide](http://yeoman.io/authoring/integrating-yeoman.html) to learn how to wrap yeoman in a custom runner.

But also, maybe just using `--force` and passing all values as command line arguments/options would be good enough. This depends if the generator you're using has all the required options as available options.

**Comment by evil-shrike** [comment]
Well, if someone needs to run a yeoman-generator non-interactively here's a tool - https://www.npmjs.com/package/yeoman-gen-run
