### ISSUE TITLE
yeoman creates project always in same directory

### ISSUE THREAD

**Issue by s3c0nDD** [yeoman/yeoman#1663]
I'm for example in mu brand new dir for project like ~/Projects/testproject 

then i do `yo` and generate project from some generator.

but all files are created in ~/Projects

is it bug or feature?

**Comment by mischah** [comment]
Never experienced that behavior.

Is this reproducible with any generator?
Or in other words: Which generator are you using?

**Comment by mischah** [comment]
Another thing: Do you have a `.yo-rc.json` in `~/Projects`? Might cause these type of problems.

**Comment by s3c0nDD** [comment]
yes i have a .yo-rc.json in ~/Projects

**Comment by SBoudrias** [comment]
Remove the `.yo-rc.json` from that directory. It's a file Yeoman uses to detect the root of your current project.

**Comment by s3c0nDD** [comment]
ok i have no files from generator, i `mkdir testapp` then `mkdir testapp` and then `yo` follwoing all intructions, and ill update here what i get ok

**Comment by s3c0nDD** [comment]
ok it seems everything now generates in right directory.
