### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mdemarco1234** [yeoman/yeoman#1669]
I am an angular2 developer. I generated an application using the fountain generator. There is no instructions on how to start the application.  I did see a hello.html page which by definition should have a selector element called fountain-app in the html file because it is in the hello.ts file. It's not there. Is there documentation that describes how to start the application?

**Comment by SBoudrias** [comment]
You should contact generator-fountain maintainers. Yeoman's maintainers cannot maintains our 6000+ community generators 🙈
