### ISSUE TITLE
Change npm/bower install path.

### ISSUE THREAD

**Issue by Davy-F** [yeoman/yeoman#1670]
Currently the yeoman generator attempts to run the npm and bower install commands in the root of the app directory.

We have created a generator which contains a full blown app, including a nested web-client. This web-client includes our package.json, so ideally we would like yeoman to point to this.

Our folder structure:

> generators
>>app **(where yeoman looks)**
>>> templates
>>>> application
>>>>> webclient **(want to run npm update here)**
>>>>>> package.json **(file to run)**

Are there any configuration options to do this?

**Comment by SBoudrias** [comment]
Can you use `.yo-rc.json`?

**Comment by Davy-F** [comment]
@SBoudrias Hi Simon, i'm not sure. Would I be able to add a 'change directory' command in the promptValues? Thanks.

**Comment by Davy-F** [comment]
I was able to get around this problem by adding the following in the index.js install method:

```
  install() {  
    // Change working directory subfolder
    var npmdir = process.cwd() + '/webclient';
    process.chdir(npmdir);	    
    this.installDependencies();
  }
```

**Comment by SBoudrias** [comment]
You can also use `this.npmInstall(null, {}, { cwd: 'webclient' })`. Might be more reliable than changing the current dir.

**Comment by Davy-F** [comment]
Thanks, @SBoudrias. Would I need to call {cwd: 'webclient' } for both this.npmInstall and this.bowerInstall?

E.g.
```
this.npmInstall(null, {}, { cwd: 'webclient' })
this.bowerInstall(null, {}, { cwd: 'webclient' })
```

**Comment by SBoudrias** [comment]
Yeah, this would change where a command is spawned.

The 3 arguments is the spawn function options: https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options

**Comment by Davy-F** [comment]
Excellent, thanks.
