### ISSUE TITLE
HTTPS support on homepage

### ISSUE THREAD

**Issue by dfuentes77** [yeoman/yeoman#1677]
In accordance with https://www.eff.org/https-everywhere

**Comment by SBoudrias** [comment]
gh pages supports https now, we can totally do that now: https://help.github.com/articles/securing-your-github-pages-site-with-https/

Just need to make sure we don't get mixed content bugs when we turn it on.

**Comment by mischah** [comment]
> HTTPS is not supported for GitHub Pages using custom domains.

😞 

Closing this since it’s a duplicate of https://github.com/yeoman/yeoman.github.io/issues/529
