### ISSUE TITLE
Periods on prompt names are not being used as object paths

### ISSUE THREAD

**Issue by danielo515** [yeoman/yeoman#1679]
Hello,

According to yeoman documentation you are using inquirer for prompting the user and you refer to their API docs for advanced usage.
Today I found one case where you are not honoring the inquirer API. According to inquirer docs:

> name: (String) The name to use when storing the answer in the answers hash. **If the name contains periods, it will define a path in the answers hash**.

I tested this with the version of inquirer that yeoman installs, and it works correctly, so it should be a bug on how yeoman extends it.

Here is an example. Having the following prompts:

```js
const prompts = [
      {
        type: `input`,
        name: ['service', 'name'],
        message: `Server Name`,
      }
      , {
        type: `input`,
        name: 'service.port',
        message: `Default port of the server`,
        default: 3000
      }
]
```

Yeoman generates the following:

```js
this.prompt(prompts)
// => { 'service,name': 'testing-generators', 'service.port': 3000 }
```

while inquirer will do it correctly

```js
inquirer.prompt(prompts)
// => { service: { name: 'testing-generators', port: 3000 } }
```

This is a BIG advantage when you want to properly organize and namespace options.
Do you have intention to fix this ? Any possible workaround meanwhile ? Taking in account that I want to use the store option.

Thanks and regards.

**Comment by danielo515** [comment]
I can confirm that this happens for 1.8.5 but works correctly on 2.0.0
How can I specify which minimum version of yeoman my generator needs ?

**Comment by SBoudrias** [comment]
@danielo515 might just be due to the version of Inquirer yeoman-environment is using. There's not really a way to enforce a version of `yo` on end users machines.

**Comment by SBoudrias** [comment]
I'll close this issue as I can't see a way to really resolve this in a satisfactory manner.

New features are added with new release, and we can't really force users to update (that being said, with `update-notifier` we try to push as much as we can).
