### ISSUE TITLE
http://yeoman.io/generators/ - page hangs

### ISSUE THREAD

**Issue by pwujek** [yeoman/yeoman#1682]
I would like to learn about yeoman generators but this page is stuck in wait mode and doesn't complete loading.

Tested in Ubuntu 17.10 with Chrome and Firefox.

**Comment by mischah** [comment]
Hej @pwujek,

No problems with loading the page over here. It has to load 400kb of JSON, though.

Please check your browsers console if there are any errors in case it still doesn’t work for you.

Cheers, Michael
