### ISSUE TITLE
authoring documentation outdated - Generator.extend()

### ISSUE THREAD

**Issue by cancerberoSgx** [yeoman/yeoman#1688]
documentation provided here is outdated http://yeoman.io/authoring/ - it will only work for yaoman-generator 1.x but today, if you run `npm install --save yaoman-generator` the version is 2.x . 

For example, this will fail (snippet taken from that doc): 

```javascript
var Generator = require('yeoman-generator');
module.exports = Generator.extend({
    
})
```

with the error `Generator.extend is not a function`

In concrete, is not clear if/how to author a new generator using es5

Thanks - BTW yeoman is great ! :)

**Comment by SBoudrias** [comment]
Thanks for the notice, I removed the notes from the documentation.

For es5, you'd need to rely on `util.inherit` or the verbose es5 way to extend base classes.

That being said, I'd suggest you to update your Node version to a LTS version.

**Comment by cancerberoSgx** [comment]
thanks, already did tha myselft, is just that we still have some customers that (for other reasons) still need to use old node.js ...
