### ISSUE TITLE
how to delete yeoman from windows?

### ISSUE THREAD

**Issue by vasyliv** [yeoman/yeoman#1690]
How to completely delete yeoman from windows?

**Comment by SBoudrias** [comment]
Should be `npm uninstall -g yo`

Link to relevant npm documentation: https://docs.npmjs.com/getting-started/uninstalling-global-packages

**Comment by vasyliv** [comment]
thanks

**Comment by leonardofrp5** [comment]
Doesn't work @SBoudrias

**Comment by eddiemonge** [comment]
What didn't work?

**Comment by leonardofrp5** [comment]
I couldn't uninstall yeoman wthi that Link to relevant npm documentation: https://docs.npmjs.com/getting-started/uninstalling-global-packages @eddiemonge

**Comment by eddiemonge** [comment]
did you get any errors?
