### ISSUE TITLE
Categorize Generators

### ISSUE THREAD

**Issue by ev1stensberg** [yeoman/yeoman#1691]
Hi and congratulations on a new release! 

## Summary

It would be convenient to categorize generators at the search page so that library authors can specify specific grammar for their generator names. This way, it's easier for those authors to create ecosystems for their generator based logic.

Categorizing dependencies isn't only good for finding the right generator, but also for authors. Authors have the possibility to have specific namespaces for their generators and this way creates a viable ecosystem for their libraries. Furthermore, specifying categorizes will allow authors to directly link to the generators related to their projects.

One example of this would be:

`babel-generator-react` where first case specifies project, second and third one feature/target  ( which is normal convention )

**Comment by mischah** [comment]
Hej Even,

thanks for your input. Could you please copy the content of the issue and open a new on on the correct repo for the website?

https://github.com/yeoman/yeoman.github.io/issues/new

Cheers, Michael

**Comment by ev1stensberg** [comment]
Will do!
