### ISSUE TITLE
Getting fast-glob dependency error

### ISSUE THREAD

**Issue by matthewfarlymn** [yeoman/yeoman#1692]
Whenever we install the current version 2.0.2 through NPM we receive the following error when trying to us the yo command

```
/usr/local/lib/node_modules/yo/node_modules/fast-glob/out/providers/reader-sync.js:45
throw err;
^
```

I have the previous version 2.0.1 installed on my system which I haven't updated and works fine. When trying to downgrade on a new install this version also doesn't work.

Any help would be great. Thanks

**Comment by SBoudrias** [comment]
Could it be related to https://github.com/yeoman/environment/issues/97 ?

**Comment by matthewfarlymn** [comment]
Looks like this is no longer an issue.
