### ISSUE TITLE
Yeoman execution delays for several minutes before running

### ISSUE THREAD

**Issue by wsrast** [yeoman/yeoman#1695]
I created a Yeoman generator that used to work in a snappy manner, but recently, performance has plummeted, requiring me to wait as much as five minutes every time I can a simple `yo`. I've verified that the same command is working properly on another team member's system, where they run in a second or two.

I've tried turning on the verbose Yeoman debugging, and after five minutes of waiting, the very first `yeoman:generator` statement appears. Here's what I get after my command of `yo @my/generator:subgen`:

    > yo @my/generator:subgen tryNumberOne
      yeoman:generator Queueing initializing in initializing +0ms
      yeoman:generator Queueing prompting in prompting +4ms
      yeoman:generator Queueing writing in writing +0ms
      yeoman:generator Queueing end in end +0ms
      yeoman:generator Running initializing +4ms
    Creating pure component file

    - Initializing
      yeoman:generator Running prompting +4ms

The only thing I can think of is that there's something amiss with how Yeoman is looking for dependencies on my machine, or it's trying to find something over the network and timing out silently, then running normally. Unfortunately, there's no way for me to test my theory that I can see.

Following the [documentation](http://yeoman.io/authoring/debugging.html) and trying to run the node inspector on Yeoman doesn't work:

```
> where yo
C:\Program Files\nodejs\yo
C:\Program Files\nodejs\yo.cmd
```
Then:
```
node --inspect "C:\Program Files\nodejs\yo" @my/generator:subgen

> node --inspect "c:\program files\nodejs\yo" @my/generator:subgen
Debugger listening on ws://127.0.0.1:9229/9af26a63-fdc3-4d5f-b48e-a467abcb6d84
For help see https://nodejs.org/en/docs/inspector
C:\Users\rastwe\AppData\Roaming\nvm\v8.11.3\yo:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```
Using the ws:// protocol url above doesn't work in the browser, of course. You have to change it to http://, then add /json/list, and pull the real url from there to open the debugger in Chrome. Even then, the output is still `SyntaxError: missing ) after argument list`

I can even run just a simple `yo` command and the gruelling wait is still in place, so even the generator itself isn't the issue:

```
> yo

waaaaaaaaaiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiit (5 minutes+)

? 'Allo myuser! What would you like to do? (Use arrow keys)
  Run a generator
> @my/generator
  ──────────────
  Update your generators
  Install a generator
  Find some help
  Get me out of here!
(Move up and down to reveal more choices)
```

I've uninstalled and reinstalled Yeoman several times (2.0.3 doesn't work for me, as detailed in another open issue, so I'm using 2.0.2). Swapped to the LTS version of node (8.11), forced the clearing of my npm cache, tried using Yarn to install Yeoman, all to no avail.

Does anyone have any idea what's going on here?

**Comment by SBoudrias** [comment]
Hey, let's move this discussion to https://github.com/yeoman/yo/issues/176 - other users are experiencing this, but didn't quite figure out the root cause yet.

Do you use a proxy by any chance?

**Comment by wsrast** [comment]
Yes, I do use a corporate proxy.
