### ISSUE TITLE
Cann install yeoman on Windows 7 machine

### ISSUE THREAD

**Issue by BARRJ303** [yeoman/yeoman#1696]
When I run the command 'npm install --global yo' in cmd.
I am getting error message.
Please see screen below.

![image](https://user-images.githubusercontent.com/41379684/42887037-a0da97a0-8ad7-11e8-8aae-d48a29127af5.png)

Please advice.
Thanks,

**Comment by SBoudrias** [comment]
This is an npm issue. You could try to get support from their community.
