### ISSUE TITLE
Not Found yeoman-generator

### ISSUE THREAD

**Issue by LeeHyungGeun** [yeoman/yeoman#1700]
I got an error.

```
npm ERR! 404 Not Found: yeoman-generators@http://github.com/yeoman/generators/archive/0.9.5.tar.gz
```

**Comment by SBoudrias** [comment]
Hey, there's never been a `0.9.5` version. You can check that out by running `npm view yeoman-generator versions` (but there was a `yeoman` package release as 0.9.5 - but they're very different)

I'd recommend you looking to our official documentation if you're trying to get started with Yeoman: http://yeoman.io - I'm worried you might try to follow a very old and outdated tutorial.

Let us know if we can do anything else to help out. Cheers

**Comment by LeeHyungGeun** [comment]
@SBoudrias There is no 0.9.5 version on my local with `npm view yeoman-generator versions`. Is it incorrect to install yeoman-generator by `npm i -g yo` ?

**Comment by SBoudrias** [comment]
`npm i -g yo` isn't going to install `yeoman-generator`.

- `yo` is the main tool for end users
- `yeoman-generator` is the core framework to write your own generators

**Comment by LeeHyungGeun** [comment]
@SBoudrias Thank you. As I checked what you mentioned above the `npm view yeoman-generator versions`, the version what I wanted to use is not in the versions. That is why I got the error. Thanks again.
