### ISSUE TITLE
Docs: Broken and/or Inaccessible

### ISSUE THREAD

**Issue by geoffdavis92** [yeoman/yeoman#1704]
[Full API Documentation link](http://yeoman.io/generator/)

When I go to the above link, accessed from the [`/authoring`](http://yeoman.io/authoring/) directory, I get the 404 page:

![yeoman.io 404 screen](https://image.prntscr.com/image/TjHCXnG2QPe3hu2feMFImQ.png)

I was looking for more detailed information on the API, but was unable to access the page. There is also a dead link on [`/authoring/user-interactions`](http://yeoman.io/authoring/user-interactions.html) labeled as an API doc link.

![user-interactions page API dead link](https://image.prntscr.com/image/TQB2d_StSVub68gNmHY-dQ.png)

Do these API docs exist?

**Comment by SBoudrias** [comment]
Duplicate from https://github.com/yeoman/yeoman.github.io/issues/771

For some reason our packages gh-pages stopped working. For now you can get the raw files here https://github.com/yeoman/environment/tree/gh-pages

I'll close this one, but feel free to follow up on the other issue.
