### ISSUE TITLE
[question] use yeoman in a single (npx) script

### ISSUE THREAD

**Issue by daKmoR** [yeoman/yeoman#1705]
hey,

sorry for posting this as an issue - I just feel more comfortable on github 🤗  If I shall move this somewhere else just let me know 🤗 

So I currently have a few generators in my package `generator-open-wc`. Now for my users they do 
```
npm i -g yeoman
npm i -g generator-open-wc

yo open-wc
```

with npm6 there would now be the possibility to make it an single
```
npm init open-wc
```
command by providing it as an npx command.
[Offical Docs](https://docs.npmjs.com/cli/init?_ga=2.171397024.1844451416.1549225069-454735496.1546688166#description:) and [Info I got from the npm forum](https://npm.community/t/custom-npm-init-command-npm-init-open-wc/5099/2?u=dakmor)

However the question is now how can I trigger yoman from a single script?

Is there a programmatically way of triggering a specific yoman generator?

maybe something like? ... I'm just throwing ideas around 🙈  I hope you can tell me better 🤗 
```js
// index.js
const yo = require('yo');
const owc = require('generator-open-wc');

yo.execute(owc);
```

**Comment by SBoudrias** [comment]
To use with npx, I'd suggest to run as `npm init yo foo`

For more details, see the [`create-yo` package](https://boneskull.com/create-yo/)

If you still want to use Yeoman programmatically, there's an official API for this, and it is document in this page on our website: https://yeoman.io/authoring/integrating-yeoman.html

**Comment by daKmoR** [comment]
uhhh awesome... thxxx ❤️ 
exactly what I was looking for 🤗

**Comment by kirillgroshkov** [comment]
Doesn't work for me if I use generator with scoped package name, e.g `@naturalcycles/generator-nodejs-lib` :(

**Comment by arleyGuoLei** [comment]
> Doesn't work for me if I use generator with scoped package name, e.g `@naturalcycles/generator-nodejs-lib` :(

Would you like a solution?
