### ISSUE TITLE
A way to get value out of composed generator?

### ISSUE THREAD

**Issue by thejohnfreeman** [yeoman/yeoman#1708]
I'd like to send my users to [generator-license](https://github.com/jozefizso/generator-license) to let them choose a license, but I need to know that choice after it runs to put it in the project metadata file I generate. Is there an API for getting values out of subgenerators? Can there be?

**Comment by SBoudrias** [comment]
You could read it from the `package.json` file after the `generator-license` run.

There's no API to pass data outside a composed generator. The system isn't design to allow this kind of interactions.

**Comment by thejohnfreeman** [comment]
`generator-license` does not emit a `package.json`, nor do I want it to. I'm trying to scaffold a Python project. Thank you for the answer regardless!

**Comment by FrederickEngelhardt** [comment]
One way to do this would be to bind an update function to an object. Firing the function would then update the original generator.

Example:
```
// Generator 1
module.exports = class extends Generator {
constructor(args: any, opts: any) {
    super(args, opts)

    this.packageJson = {
      name: 'test'
    }

    this._updatePackageJson = this._updatePackageJson.bind(this)
  }
  initializing() {
    this.composeWith('generator2', {
      configuration: this.configuration,
      updatePackageJson: this._updatePackageJson,
    })
  }
}
```

```
// generator 2
module.exports = class extends Generator {
constructor(args: any, opts: any) {
    super(args, opts)
    this.updatePackageJson = opts.updatePackageJson
  }

  updatePackageFunction(){
     this.updatePackageJson({ name: 'hello world' })
 }
}
```

**Comment by thejohnfreeman** [comment]
That requires both generators to be aware of each other. It doesn't work when composing with an arbitrary generator.

**Comment by mshima** [comment]
> That requires both generators to be aware of each other. It doesn't work when composing with an arbitrary generator.

Yep, a new composing api is in experimental, it will be enable composing with arbitrary generator.
But it's not backward compatible.
https://github.com/mshima/generators/blob/3dead1692fd2716048c4282f5fe846d4627c88da/%40mshima/generator-generator/generators/app/index.js#L38-L89

Should be enabled by `yo --experimental`.
