### ISSUE TITLE
Can't enter project name with any generators

### ISSUE THREAD

**Issue by Tanddant** [yeoman/yeoman#1714]
We are having an issue where when we go to create a project the generator (Tested with both  @microsoft/sharepoint and node module generator) it will start the prompt, and we'll select the options that are required using the arrow keys, then we get to the point where it needs a solution name, and then all keyboard inputs are just ignored, the cursor is still blinking.

The issue occures on ~10 PCs, all running windows 10, some domain joined and some not, both inside and outside out network

We've tried:
- Reboot
- Updating and downgrade node.js
- Update yeoman, and our generators (and downgrade)
- Tested with older versions of windows 10
- Tried using CMD, PowerShell, Cmder and the terminal in VS Code

This is where we get stuck, nothing seems to work
![Capture](https://user-images.githubusercontent.com/6947024/59849278-72e47480-9367-11e9-98a2-d53deb45a944.PNG)

Info from[ HOW TO OPEN AN HELPFUL ISSUE](https://yeoman.io/contributing/opening-issues.html)

`2.0.6
C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;%NVM_HOME%;%NVM_SYMLINK%;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Plantronics\Spokes3G\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Users\datot\AppData\Local\Microsoft\WindowsApps;C:\Users\datot\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\datot\AppData\Roaming\nvm;C:\Program Files\nodejs; %NODE_PATH%
win32 { http_parser: '2.8.0',
  node: '10.15.3',
  v8: '6.8.275.32-node.51',
  uv: '1.23.2',
  zlib: '1.2.11',
  ares: '1.15.0',
  modules: '64',
  nghttp2: '1.34.0',
  napi: '3',
  openssl: '1.1.0j',
  icu: '62.1',
  unicode: '11.0',
  cldr: '33.1',
  tz: '2018e' }
The system cannot find the file specified.`

**Comment by raymondfeng** [comment]
It is probably caused by inquirer@6.4.0. Downgrading to inquirer@6.3.1 works for https://github.com/strongloop/loopback-next/issues/3187.

**Comment by Tanddant** [comment]
Just tired a fresh install of all my npms and installing inquirer@6.3.1, issue persists

**Comment by Tanddant** [comment]
[This](https://github.com/microsoft/vscode-generator-code/issues/173#issuecomment-504280731) seems to have fixed the issue for us

- Navigate to %USERPROFILE%\AppData\Roaming\npm\node_modules\yo
- `npm uninstall inquirer`
- `npm install inquirer@6.3.1`

We do use NVM and had to change the path a bit, but downgrading inquirer in your YO folder does do the trick.

This is a workaround and should still be fixed.

**Comment by SBoudrias** [comment]
You can try again, I've just published a fix for Inquirer.

**Comment by Tanddant** [comment]
I just tested, it seems to work, thanks 👍
