### ISSUE TITLE
Couldn't find the 'yo' binary error when installing

### ISSUE THREAD

**Issue by ishaisagi** [yeoman/yeoman#1716]
I cannot figure out what is going on. I installed latest NodeJS version (also tried removing it and installing version 10) and I always get the following error when trying to install Yeoman (after yodoctor and a lot of MaxListenersExceededWarning)

{ Error: Couldn't find the 'yo' binary. Make sure it's installed and in your $PATH
    at notFoundError (C:\ProgramData\Microsoft\VisualStudio\MDA\864bc21e\taco-toolset-6.3.1\node_modules\yo\node_modules\yeoman-doctor\node_modules\bin-version-check\node_modules\bin-version\node_modules\execa\node_modules\cross-spawn-async\lib\enoent.js:8:11)
    at verifyENOENT (C:\ProgramData\Microsoft\VisualStudio\MDA\864bc21e\taco-toolset-6.3.1\node_modules\yo\node_modules\yeoman-doctor\node_modules\bin-version-check\node_modules\bin-version\node_modules\execa\node_modules\cross-spawn-async\lib\enoent.js:43:16)
    at ChildProcess.cp.emit (C:\ProgramData\Microsoft\VisualStudio\MDA\864bc21e\taco-toolset-6.3.1\node_modules\yo\node_modules\yeoman-doctor\node_modules\bin-version-check\node_modules\bin-version\node_modules\execa\node_modules\cross-spawn-async\lib\enoent.js:30:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn yo',
  cmd: 'C:\\WINDOWS\\system32\\cmd.exe /s /c "yo "--version""' }
× yo version
{ Error: Couldn't find the 'yo' binary. Make sure it's installed and in your $PATH
    at notFoundError (C:\ProgramData\Microsoft\VisualStudio\MDA\864bc21e\taco-toolset-6.3.1\node_modules\yo\node_modules\yeoman-doctor\node_modules\bin-version-check\node_modules\bin-version\node_modules\execa\node_modules\cross-spawn-async\lib\enoent.js:8:11)
    at verifyENOENT (C:\ProgramData\Microsoft\VisualStudio\MDA\864bc21e\taco-toolset-6.3.1\node_modules\yo\node_modules\yeoman-doctor\node_modules\bin-version-check\node_modules\bin-version\node_modules\execa\node_modules\cross-spawn-async\lib\enoent.js:43:16)
    at ChildProcess.cp.emit (C:\ProgramData\Microsoft\VisualStudio\MDA\864bc21e\taco-toolset-6.3.1\node_modules\yo\node_modules\yeoman-doctor\node_modules\bin-version-check\node_modules\bin-version\node_modules\execa\node_modules\cross-spawn-async\lib\enoent.js:30:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn yo',
  cmd: 'C:\\WINDOWS\\system32\\cmd.exe /s /c "yo "--version""' }

Found potential issues on your machine :(
yo@3.1.0 C:\ProgramData\Microsoft\VisualStudio\MDA\864bc21e\taco-toolset-6.3.1\node_modules\yo
├── cli-list@0.2.0
├── titleize@1.0.1
├── figures@2.0.0 (escape-string-regexp@1.0.5)
├── user-home@2.0.0 (os-homedir@1.0.2)
├── humanize-string@1.0.2 (decamelize@1.2.0)
├── open@6.4.0 (is-wsl@1.1.0)
├── string-length@2.0.0 (astral-regex@1.0.0, strip-ansi@4.0.0)
├── sort-on@3.0.0 (arrify@1.0.1, dot-prop@4.2.0)
├── yeoman-character@1.1.0 (supports-color@3.2.3)
├── configstore@3.1.2 (xdg-basedir@3.0.0, graceful-fs@4.2.0, make-dir@1.3.0, dot-prop@4.2.0, unique-string@1.0.0, write-file-atomic@2.4.3)
├── cross-spawn@6.0.5 (path-key@2.0.1, nice-try@1.0.5, semver@5.7.0, shebang-command@1.2.0, which@1.3.1)
├── parse-help@1.0.0 (execall@1.0.0)
├── chalk@2.4.2 (escape-string-regexp@1.0.5, supports-color@5.5.0, ansi-styles@3.2.1)
├── global-tunnel-ng@2.7.1 (encodeurl@1.0.2, tunnel@0.0.6, npm-conf@1.1.3)
├── root-check@1.0.0 (downgrade-root@1.2.2, sudo-block@1.2.0)
├── yosay@2.0.2 (strip-ansi@3.0.1, ansi-regex@2.1.1, cli-boxes@1.0.0, pad-component@0.0.1, chalk@1.1.3, string-width@2.1.1, taketalk@1.0.0, ansi-styles@3.2.1, wrap-ansi@2.1.0)
├── package-json@5.0.0 (semver@5.7.0, registry-url@3.1.0, registry-auth-token@3.4.0)
├── npm-keyword@5.0.0 (registry-url@3.1.0, got@7.1.0)
├── got@8.3.2 (lowercase-keys@1.0.1, p-cancelable@0.4.1, duplexer3@0.1.4, timed-out@4.0.1, decompress-response@3.3.0, pify@3.0.0, is-retry-allowed@1.1.0, mimic-response@1.0.1, url-to-options@1.0.1, get-stream@3.0.0, safe-buffer@5.2.0, @sindresorhus/is@0.7.0, url-parse-lax@3.0.0, p-timeout@2.0.1, cacheable-request@2.1.4, isurl@1.0.0, into-stream@3.1.0)
├── fullname@3.3.0 (p-try@1.0.0, filter-obj@1.1.0, mem@1.1.0, rc@1.2.8, p-any@1.1.0, execa@0.6.3, passwd-user@2.1.0)
├── update-notifier@2.5.0 (is-npm@1.0.0, xdg-basedir@3.0.0, import-lazy@2.1.0, is-ci@1.2.1, semver-diff@2.1.0, is-installed-globally@0.1.0, latest-version@3.1.0, boxen@1.3.0)
├── async@2.6.3
├── meow@3.7.0 (map-obj@1.0.1, decamelize@1.2.0, trim-newlines@1.0.0, object-assign@4.1.1, minimist@1.2.0, camelcase-keys@2.1.0, loud-rejection@1.6.0, redent@1.0.0, read-pkg-up@1.0.1, normalize-package-data@2.5.0)
├── read-pkg-up@4.0.0 (find-up@3.0.0, read-pkg@3.0.0)
├── insight@0.10.3 (lodash.debounce@4.0.8, uuid@3.3.2, tough-cookie@3.0.1, conf@1.4.0, os-name@3.1.0, request@2.88.0)
├── yeoman-environment@2.4.0 (escape-string-regexp@1.0.5, untildify@3.0.3, grouped-queue@0.3.3, log-symbols@2.2.0, text-table@0.2.0, strip-ansi@4.0.0, is-scoped@1.0.0, debug@3.2.6, diff@3.5.0, mem-fs@1.1.3, globby@8.0.2)
├── tabtab@1.3.2 (object-assign@4.1.1, minimist@1.2.0, debug@2.6.9, mkdirp@0.5.1, npmlog@2.0.4, inquirer@1.2.3)
├── yeoman-doctor@4.0.0 (log-symbols@2.2.0, semver@5.7.0, ansi-styles@3.2.1, bin-version-check@3.0.0, latest-version@3.1.0, twig@1.13.3)
├── lodash@4.17.14
├── global-agent@2.0.0 (es6-error@4.1.1, boolean@1.0.0, semver@6.2.0, matcher@2.0.0, serialize-error@4.1.0, roarr@2.13.2, core-js@3.1.4)
└── inquirer@6.5.0 (ansi-escapes@3.2.0, cli-width@2.2.0, through@2.3.8, mute-stream@0.0.7, strip-ansi@5.2.0, run-async@2.3.0, string-width@2.1.1, cli-cursor@2.1.0, external-editor@3.1.0, rxjs@6.5.2)

**Comment by SBoudrias** [comment]
I think your global node_modules binary folder isn't in your system `PATH` variable.

You can google how to fix that. https://stackoverflow.com/questions/27864040/fixing-npm-path-in-windows-8-and-10

**Comment by ishaisagi** [comment]
no, that is not the case. it is in the path, and yodoctor gets installed etc, but not the yo...

**Comment by SBoudrias** [comment]
@ishaisagi can you provide your current `$PATH`? And the result of `npm prefix --global`?

**Comment by ishaisagi** [comment]
C:\ProgramData\Microsoft\VisualStudio\MDA\864bc21e\taco-toolset-6.3.1


PATH=C:\Users\IYoga\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\nodejs\node_modules\npm\bin;C:\Users\IYoga\AppData\Local\Microsoft\WindowsApps;C:\Users\IYoga\AppData\Local\Programs\Fiddler;C:\Users\IYoga\AppData\Local\Microsoft\WindowsApps;C:\Users\IYoga\AppData\Local\Programs\Microsoft VS Code\bin

**Comment by ishaisagi** [comment]
anyone has any ideas? at the moment I resorted to installing vs2019 to see if that helps, but if it doesnt, does that mean my machine is broken or that yeoman is?

**Comment by SBoudrias** [comment]
Are other global npm installed tools working? like `david` for example?

I'd say there's 95% chances it's an issue on your machine otherwise we'd have a lot of bug tickets opened that we broken Yeoman, but there's no other tickets.

**Comment by ishaisagi** [comment]
Thanks for responding Simon.
I just tried, and david installation ran smoothly. however, I have no idea how it is used (I have never used nodejs) so I cannot tell if it is correctly installed

**Comment by SBoudrias** [comment]
oh I was thinking you could just run like `david --help` to see if the binary is found in your PATH or not.

**Comment by mlshv** [comment]
I'm installing yeoman on Mac OS and having the same issue. Executing:
```nom i -g yo```
Getting error message: ```Error: Couldn't find the 'yo' binary. Make sure it's installed and in your $PATH```

I have other global packages and they work absolutely fine.

**Comment by csetoihid** [comment]
I am also having same issue on windows 10
I used npm install -g yo.
Error: Couldn't find the 'yo' binary. Make sure it's installed and in your $PATH.

Thanks,
Toihid

**Comment by ishaisagi** [comment]
I ended up resolving it by reinstalling windows

**Comment by caijunjie815** [comment]
I have the same issue, and I fixed it by redownloading Node.js. I think you need to update node.js and npm to the latest version. hope it helpful.

**Comment by Austinbreathesair** [comment]
I am also having the same issue on windows 10.

**Comment by willianfalbo** [comment]
I managed to fix it by installing the Latest Features of Node.js (12.9.1)

**Comment by vashuraghav** [comment]
To do so try with yarn package manager.  
yarn global add yo
this command will install yo globally in your mac

**Comment by tjl352** [comment]
I got the same issue.  I solved it by adding these two:
```
C:\Program Files\nodejs\;
%AppData%\npm;
```
 to my **Path** in my User Environment variable (It was already in my **Path** System Environment variable).

**Comment by flienard** [comment]
Added C:\Users\[User Name]\.npm-packages to Path system environment variable to get it to work.

**Comment by danielmijarra** [comment]
> 
> 
> Added C:\Users[User Name].npm-packages to Path system environment variable to get it to work.

Great!! Works fine!!

Thank you flienard!!

**Comment by downstevedown** [comment]
Tore my hair out over this one - uninstalled and reinstalled twice. Tried adding every path suggested in every thread. 

Finally, I opened %AppData% by itself, not %AppData%\npm or %appData%\npm\npm_modules, and found yo.cmd there! Added it to my path and all is well.

**Comment by bharanidharanspm** [comment]
Hi @downstevedown , You are right. It worked for me following your steps.

To be clear any user who is facing this issue should accordingly add/edit below path in their environment variables

C:\Users\YourName\AppData\Roaming\npm

**Comment by 534591395** [comment]
I am also having the same issue on windows 10.  I managed to fix it by installing the Latest Features of Node.js (v14.16.1)
