### ISSUE TITLE
How to remove the yeoman cache?

### ISSUE THREAD

**Issue by trusktr** [yeoman/yeoman#1719]
How do I make Yeoman start fresh? How do I completely blow away any yeoman cache from my global `yo` install?

For example, how do I make it ask me again if I want to provide anonymous usage data?

I tried uninstalling and reinstalling, but it does not prompt.

**Comment by SBoudrias** [comment]
We do not expose such an option as far as I remember. You would need to remove the `.yo-rc.json` file and the global one.

**Comment by trusktr** [comment]
Where's that global one?

**Comment by SBoudrias** [comment]
It is here: `node -e "console.log(require('os').homedir() + '/.yo-rc-global.json')"`

**Comment by trusktr** [comment]
Hmmm, I thought I looked there, but I didn't see anything that started with `~/.yo`. I've factory-reset my machine anyways, so I'll check it out next time. Thanks!
