### ISSUE TITLE
alfresco generator

### ISSUE THREAD

**Issue by SamuelBds** [yeoman/yeoman#1733]
Hi, I am new to yeoman, npm, alfresco, docker etc.
I am trying to install alfresco for a production environment and came across npm/yeoman.  I was able (with difficulty) to get yeoman installed. 
I managed also to run the alfresco docker generator.

My problem is now the postgres database container is shutting down after running docker-compose up. 
I have attached a screenshot of the first failure message found
![postgres fail](https://user-images.githubusercontent.com/57236563/75910318-10170880-5e24-11ea-8c0e-be6aa824a5de.png)

Other errors found may be related to this failure.

How can I find and correct this failure to get the system functioning?

**Comment by mshima** [comment]
This is a generator specific error and should be posted on the alfresco generator project.
Probably https://github.com/alfresco/alfresco-docker-installer/issues.
If you have problems with yo command, then you should open an issue here.
