### ISSUE TITLE
The Discovering Generators page on the Yeoman website does not add generators with scoped package names

### ISSUE THREAD

**Issue by lynn14m** [yeoman/yeoman#1742]
I created a generator that uses a scoped naming convention rather than the naming convention stated on the Yeoman website, and had it published on the npm registry. The generator that I created still isn’t showing up on the Discovering Generators page of the Yeoman website. I understand that Yeoman has scoped name support from a previous release, but I’m unsure of how this feature affects how the Discovering Generators list is populated on the website, and I’m unsure whether the problems I am facing are due to my own mistakes in the naming or with Yeoman. Any help would be appreciated!

This is the link to the github repository with the generator for reference: https://github.com/hyperledger/caliper/tree/master/packages/generator-caliper

I’m not sure if this was the correct repository to submit this type of issue and I apologise in advance if it wasn’t!

**Comment by UlisesGascon** [comment]
mmm... Not very sure why the generator is not listed. @mischah can you confirm if we support organization names in the indexation process like: `@hyperledger/generator-caliper` and not only `generator-caliper`?

**Comment by mshima** [comment]
@UlisesGascon I think this is a npm.org api limitation.
Filtering by keyword does not show scoped packages.

**Comment by lynn14m** [comment]
Ahh I see, no worries then. Thank you for the response!
