### ISSUE TITLE
Unable to Install yo and generator-code Due to Deprecated Packages

### ISSUE THREAD

**Issue by glendnoob** [yeoman/yeoman#1777]
I am encountering issues while trying to install yo and generator-code globally using npm. The installation process is interrupted by warnings about deprecated packages as well as a no longer supported message. Here is a replication of what I get when I run it in PS.

PS C:\Users\Projects\foobaar> npm install --global yo generator-code
npm warn deprecated npmlog@2.0.4: This package is no longer supported.
npm warn deprecated gauge@1.2.7: This package is no longer supported.
npm warn deprecated are-we-there-yet@1.1.7: This package is no longer supported.

**Comment by Ignacio-Ucedo** [comment]
i was facing the exact same issue. I ran:

npm exec --package=yo -- yo

At first, i saw the very same deprecation warings, but below that, now i was able to navigate the yeoman's menu. 
then i move around the menu for install the generator-code searching for it manually. 
hope this helps.

**Comment by glendnoob** [comment]
Hey, Thanks for the help, it worked perfectly.

> i was facing the exact same issue. I ran:
> 
> npm exec --package=yo -- yo
> 
> At first, i saw the very same deprecation warings, but below that, now i was able to navigate the yeoman's menu. then i move around the menu for install the generator-code searching for it manually. hope this helps.
