### ISSUE TITLE
Homebrew install path returns 404, test is also wrong

### ISSUE THREAD

**Issue by AvnerCohen** [yeoman/yeoman#266]
In setup/install.sh , homebrew is tested and if not existing is installed using:
https://raw.github.com/mxcl/homebrew/master/Library/Contributions/install_homebrew.rb

This github file is no longer present and so the script returns a 404.

I am a complete newbie here, so I might be all wrong, but I think this can be resolved in two ways:
either, 1 : Use the Homebrew installation method as suggest by Max Howell:
ruby <(curl -fsSkL raw.github.com/mxcl/homebrew/go)

and test using a specific check on the brew command (something like `which brew` ?).

or, 2: Test existence of brew and skip installation if not exist, i.e. leave the installation of homebrew outside of Yeoman.

I hope it makes some sense.

**Comment by nauti1314** [comment]
What was the solution for mac..?

**Comment by AvnerCohen** [comment]
Welcome @nauti1314 . This is a full 5 years closed issue.

Yeoman, NodeJs, World Control and NBA Champions came & go during these years .. :)

I would suggest to start a new issue with full details of whatever problem you are facing.

Make sure to follow the issue submission guidelines:
https://github.com/yeoman/yeoman/blob/master/contributing.md#issue-submission

**Comment by nauti1314** [comment]
Than you avner, but the same day i have installed ruby on rails, i solve the problem. 
Best regards to you
