### ISSUE TITLE
Feature request for tab completion

### ISSUE THREAD

**Issue by wburningham** [yeoman/yeoman#357]
I would consider this a low priority but useful feature. Tab completion for the yeoman task/generators/subgenerators.

**Comment by markusgattol** [comment]
any news on tab completion, https://github.com/yeoman/yeoman/issues/357 is pointing back here so not sure what the current status of tab completion is?

**Comment by SBoudrias** [comment]
@markusgattol the ticket is open. We just need someone to make it happens. Please use the issue on yo for further discussions.
