### ISSUE TITLE
Yeoman forgets to bundle font-awesome and the sprite images for bootstrap

### ISSUE THREAD

**Issue by KingScooty** [yeoman/yeoman#419]
I'm not sure whether this was done intentionally, but the sprite images and the fonts for font-awesome don't seem to be included with the sass twitter bootstrap.

I'ts not a big deal, and i could have just installed the compass bootstrap gem, but I've just gone to use sprites in a project and noticed the file is still referencing the original `img` path:

`../img/glyphicons-halflings.png`

It'd be real sweet if these sprites, and the font awesome counterpart came bundled with the project if opted in during the `init` sequence.

**Comment by programmerdave** [comment]
If anyone else is having a problem with "image-url" not working correctly with use-min, you can do the following to disable compass' cache buster which will let use-min find the correctly revved files:

Put this into .compass.rb
asset_cache_buster :none
