### ISSUE TITLE
Manually pointing PATH to yeoman after install

### ISSUE THREAD

**Issue by chrisdl** [yeoman/yeoman#430]
Got the "There looks to be a problem with the install. :(" message and tried uninstalling, reinstalling cleaning npm cache etc. 

Also tried installing with `curl -L get.yeoman.io | bash` and `curl -L get.yeoman.io | sh` and doing a manual install.

I think the issue might be that I use ZSH? I solved the issue by manually adding `/usr/local/share/npm/lib/node_modules/yeoman/bin/` in my ~/.zshrc file.

Yeoman now seems to be working correctly.

Did I miss something obvious? Was there some other fix? What was causing the issue?

**Comment by LouRectoret** [comment]
Hey ! I had the same trouble !
I used : 
*$HOME/npm/bin*
And it pretty worked for me !! :dancers:

**Comment by nettles-sync** [comment]
Ran into the same issue using ZSH and the yeoman plugin. 
Add: export PATH=$HOME/npm/bin:$PATH to your path and yo will work.
