### ISSUE TITLE
PhantomJs cannot connect to X server

### ISSUE THREAD

**Issue by aubricus** [yeoman/yeoman#446]
Running Yeoman On:

OS: Linux 
HostName: vagrant-ubuntu-server-i386 
Version: 3.2.0-23-virtual Ubuntu i686 i386 GNU/Linux

---

Having trouble running phantom js under "yeoman test". 

Error:

vagrant@vagrant-ubuntu-server-i386:~/projects/test$ yeoman test
Running "mocha:all" (mocha) task
Testing index.html
Running PhantomJS...ERROR
2012-09-14T11:09:43 [WARNING] phantomjs: cannot connect to X server
<WARN> PhantomJS exited unexpectedly with exit code 1. Use --force to continue. </WARN>

Aborted due to warnings.

---

Everything else is working great, but I would like to have the uint testing suite working. Any help would be appreciated. Thanks!

This might be related to the fact that the vagrant box runs headless. Are there any workarounds?

**Comment by degli** [comment]
@arnski, thanks that worked like a charm!
