### ISSUE TITLE
Yeoman seems to install but does not run; dependency checker can't see it

### ISSUE THREAD

**Issue by shodanuk** [yeoman/yeoman#466]
I've installed everything that the dependency checker script asks for and have attempted to installed Yeoman with:

```
node install -g yeoman
```

.. both with and without sudo. In either case, Yeoman "appears" to install ie. lots of output, no errors but doesn't actually run when I enter "yeoman" and when I run the dependency checker script again, it still says it hasn't installed.

I can see a yeoman folder in ~./npm and that contains a 0.9.1 folder containing a package folder etc.

I'm on OSX Mountain Lion and am running Node 0.8.8 installed via Brew.

**Comment by LouRectoret** [comment]
Hi there, I'm workin' on MAC X OS  and can't fix this by my own,
I tryed by so many ways and I just messed up. :P

I read lots of pots on the net, so I got a totally mess in my files .(,bashrc & .bash_profile) , and I don't know nothing about $PATH stuff. So that's what I got  <a href="http://codepen.io/blackersoul/pen/NPJorv"> --> Link </a>

Could someone help this lost and desperate soul ?? 

Thanx in advance !

**Comment by landed1** [comment]
the PATH is as simple as a text file that the OS reads when it wants to know if what you typed in exists somewhere on the system. Without that you will get the not known command not found error.

the sudo is a super user strength login - best not to have to do things using sudo , if things work using sudo its a clue but you should be able to run as a regular user of your mac. So thats what to aim for.

So what are your specific errors ?

I think you can delete the 'npm' and other folders on a mac without causing too much if any issue. But I would not do that on windows for installed programs. But I wouldn't delete stuff just yet.

I would go and take a look and get used to sudo and the command line a bit before deleting stuff. I am no super hero coder so welcome others advice here too and often ask questions myself but keep pluging away and you will start to get there and start to love the mac as a dev environment.

What I really love is developers who can help us less experienced using normal non fancy lingo not like AUGMENT YOUR PATH OBJECT ;)

**Comment by LouRectoret** [comment]
I used : 
$HOME/npm/bin
and it pretty worked for me !! :dancers:

**Comment by dagnaldo** [comment]
for new users ...

I used:
export PATH=$HOME/npm/bin:$PATH

And worked for me

**Comment by jogotta** [comment]
None of this is working for me:
~$ echo $PATH
/home/jogotta/npm/bin:/usr/local/bin/npm:/usr/local/bin:/usr/local/lib/node_modules:/usr/local/share/npm/bin:/home/jogotta/.node/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

**Comment by SBoudrias** [comment]
@jogotta http://yeoman.io/learning/index.html

**Comment by jogotta** [comment]
sudo npm install -g generator-webapp
[sudo] password for jogotta: 
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0

> spawn-sync@1.0.15 postinstall /home/jogotta/.node/lib/node_modules/generator-webapp/node_modules/spawn-sync
> node postinstall

module.js:327
    throw err;
    ^

Error: Cannot find module '/home/jogotta/.node/lib/node_modules/generator-webapp/node_modules/spawn-sync/postinstall'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:429:10)
    at startup (node.js:139:18)
    at node.js:999:3
npm WARN install:spawn-sync@1.0.15 spawn-sync@1.0.15 postinstall: `node postinstall`
npm WARN install:spawn-sync@1.0.15 Exit status 1
/home/jogotta/.node/lib
└── (empty)

**Comment by SBoudrias** [comment]
@jogotta never use sudo. Now you've probably messed up your permissions. https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by jogotta** [comment]
OF COURSE!!  Other sites said use sudo.. 
I ran it without sudo and it seems to have worked but I still get command not found when I run yo

 yo webapp
yo: command not found

**Comment by SBoudrias** [comment]
@jogotta this mean you need to add npm packages binaries to your PATH.

**Comment by jogotta** [comment]
Here is my path .. 
~$ echo $PATH
/home/jogotta/.npm:/home/jogotta/.npm/yo:/home/jogotta/.npm:/home/jogotta/npm/bin:/usr/local/bin/npm:/usr/local/bin:/usr/local/lib/node_modules:/usr/local/share/npm/bin:/home/jogotta/.node/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

**Comment by jogotta** [comment]
still it says command not found when I type yo

**Comment by jogotta** [comment]
Where are the npm binaries installed?

**Comment by jogotta** [comment]
I'm about to lose my mind trying to figure out wtf is going on with this install?  This is insane.

**Comment by jogotta** [comment]
This is what I get when I install yo:

jogotta@jogotta-70A4000HUX:~$ npm install yo
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm

> yo@1.6.0 postinstall /home/jogotta/node_modules/yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version

**Comment by jogotta** [comment]
Thank Christ.. I finally got angular to install .. I'm SURE it's wrong.. but the freaking command worked.. I probably did it from the wrong directory.. lost in spaghetti lol

**Comment by maniskasyap** [comment]
facing 'yo: command not found' on Ubuntu 16.04

leanowl@leanowl:~$ npm install --global yo bower grunt-cli
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
/home/leanowl/.npm-packages/bin/bower -> /home/leanowl/.npm-packages/lib/node_modules/bower/bin/bower
/home/leanowl/.npm-packages/bin/grunt -> /home/leanowl/.npm-packages/lib/node_modules/grunt-cli/bin/grunt
/home/leanowl/.npm-packages/bin/yo -> /home/leanowl/.npm-packages/lib/node_modules/yo/lib/cli.js
/home/leanowl/.npm-packages/bin/yo-complete -> /home/leanowl/.npm-packages/lib/node_modules/yo/lib/completion/index.js

> yo@1.8.4 postinstall /home/leanowl/.npm-packages/lib/node_modules/yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version

then a long tree.

echo $PATH gives:
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

tried changing path in profile but doesn't work. Please help.

**Comment by borgymanotoy** [comment]
Anyone knows how I can get the folder of the package binaries? I could not find it in my machine, I am using ubuntu 17. TIA
