### ISSUE TITLE
Yeoman Watch / Vagrant share folder : Watch process fails to pick up change in file.

### ISSUE THREAD

**Issue by aubricus** [yeoman/yeoman#528]
**System Information**
Physical Box:
Windows 7 Professional SP1
Intel i7

Virtual Box (Vagrant):
Distributor ID: Ubuntu
Description:    Ubuntu 12.04 LTS
Release:        12.04
Codename:       precise

**Yeoman Version**
v0.9.1

**Yeoman Init Process**
`yeoman init`
[?] Would you like to include Twitter Bootstrap for Compass? Y
[?] Would you like to include the Twitter Bootstrap plugins? (Y/n) Y
[?] Would you like to include RequireJS (for AMD support)? (Y/n) Y
[?] Would you like to support writing ECMAScript 6 modules? (Y/n) N

**Vagrant Setup**

``` bash
# (omitting non essential config values)

# port forwarding
config.vm.forward_port 80, 8080
config.vm.forward_port 3501, 3510 # yeoman server port

# share folders
# ex: config.vm.share_folder "key", "guest/path/", "./host/path/"
config.vm.share_folder "public", "/home/vagrant/projects/project-name/public", "./public"
```

**Steps to Reproduce**
1. Initialize a new vagrant vm
2. Configure Vagrant file: to share folder from host machine & forward port 3501 to 3501 (see above)
3. ssh into vagrant box
4. Install yeoman & dependencies
5. Run `yeoman init` from within the shared folder
6. Run `yeoman server`
7. On the host machine open 'app/styles/main.scss' in a text editor
8. Add a new value to the main.scss file & save.
9. Open 'temp/styles/main.css' and observe the new value has not been compiled in

---

Hey guys. I am having somewhat of an obscure issue. Any support you might provide would be greatly appreciated. :^)

I have installed yeoman (including dependencies) on the vagrant box listed above. The audit script checks out and all yeoman commands seem to run without issue. 

The problem I am having is when I run `yeoman server` and editing and saving, for example, 'main.scss'. The watch process does not pick up the change in the file. 

If you take a look at the vagrant setup I've included above you can see I'm sharing the 'public' folder in my project's root with the vagrant vm. That means the yeoman server process is running directly on the VM while the 'main.scss' exists on my host machine and the VM simultaneously. 

I really think the problem lies there but as I'm completely unfamiliar with what is actually running the server process I haven't been able to gain any insight into why editing the 'main.scss' file and saving it does not trigger the update in the watch process.

Of course I wouldn't post an issue without doing _some_ digging. 

I discovered that editing the 'main.css' file from vim directly on the VM does indeed trigger the watch process to recompile. So the watch process is at least running.

I also tested this set up with just compass. In a new folder (also shared on the host) I ran  `compass create /path/to/project --using blueprint`. This init's a basic compass project. I then ran `compass watch`. 

Much to my surprise editing the a .scss file on the host machine successfully triggers the watch update from compass.

Stumped. :^)

Thanks again!

**Comment by diegolorenzetti** [comment]
Try these mount options in your Vagrantfile:

type: "nfs", mount_options: ['actimeo=1']

This will greatly reduce the NFS file attribute caching timeout.
Sometimes it can causes an error when try to save the file on your text editor, but it solves the delay problem for me.
