### ISSUE TITLE
npm install -g yeoman fails with a 502 Bad Gateway

### ISSUE THREAD

**Issue by jblanche** [yeoman/yeoman#564]
The install fails on the yeoman_generators dependency trying to download the latest tarball.
npm http 502 https://nodeload.github.com/yeoman/generators/tarball/282b0b4c51

Full error log here : https://gist.github.com/3807600

**Comment by cmshiyas** [comment]
I am facing this problem while trying to install typescript. Any help?

***log as below***
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\SHIYAS\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'typescript' ]
2 info using npm@5.3.0
3 info using node@v6.11.1
4 verbose npm-session ba810b286e4d3326
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 502 https://registry.npmjs.com/typescript 72639ms attempt #3
8 silly fetchPackageMetaData error for typescript@latest 502 Bad Gateway: typescript@latest
9 verbose stack Error: 502 Bad Gateway: typescript@latest
9 verbose stack     at fetch.then.res (C:\Users\SHIYAS\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:41:19)
9 verbose stack     at tryCatcher (C:\Users\SHIYAS\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\SHIYAS\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
9 verbose stack     at Promise._settlePromise (C:\Users\SHIYAS\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (C:\Users\SHIYAS\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
9 verbose stack     at Promise._settlePromises (C:\Users\SHIYAS\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
9 verbose stack     at Async._drainQueue (C:\Users\SHIYAS\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
9 verbose stack     at Async._drainQueues (C:\Users\SHIYAS\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues (C:\Users\SHIYAS\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
9 verbose stack     at runCallback (timers.js:672:20)
9 verbose stack     at tryOnImmediate (timers.js:645:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:617:5)
10 verbose cwd C:\Users\SHIYAS
11 verbose Windows_NT 10.0.15063
12 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\SHIYAS\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "typescript"
13 verbose node v6.11.1
14 verbose npm  v5.3.0
15 error code E502
16 error 502 Bad Gateway: typescript@latest
17 verbose exit [ 1, true ]
