### ISSUE TITLE
Incorrect Compass generated path for sprites 

### ISSUE THREAD

**Issue by darren131** [yeoman/yeoman#596]
Howdy,

I'm getting this compass issue when running yeoman server. This is my setup:
- I'm running OS X Mountain Lion
- I have all the latest versions of all the things.
- I've updated my `Gruntfile.js` to read a `compass.rb` config file.

here is the compass part of my gruntfile:

``` javascript
compass: { 
  dist: { 
    options: { 
      config: '.compass.rb', 
      force: true 
    } 
  } 
} 
```

here is my .compass.rb file:

``` ruby
http_path = "/" 
css_dir= 'temp/styles' 
sass_dir= 'app/styles' 
images_dir= 'app/images' 
javascripts_dir= 'temp/scripts' 
```

The problem is that when running the yeoman server the output css file is referencing `/app/images/generatedsprite-123489124.png` rather than `/images/generatedsprite-123489124.png`

Here's the output of the yeoman server console:

```
Starting static web server on port 3501
  - /Volumes/Macintosh HD/Users/darren/Work/Webstock/web/app
I'll also watch your files for changes, recompile if neccessary and live reload the page.
Hit Ctrl+C to quit.

Running "clean" task

Running "coffee:dist" (coffee) task

Running "compass:dist" (compass) task
directory temp/styles/ 
   remove app/images/i-s0ee4d00b40.png
   create app/images/i-s0ee4d00b40.png
   create temp/styles/main.css 

Running "open-browser" task

Running "watch" task
Waiting...Error: /app/images/i-s0ee4d00b40.png Not Found
    at Object.error (/usr/local/lib/node_modules/yeoman/node_modules/connect/lib/utils.js:43:13)
    at Object.errorHandler [as handle] (/usr/local/lib/node_modules/yeoman/tasks/server.js:360:31)
    at next (/usr/local/lib/node_modules/yeoman/node_modules/connect/lib/proto.js:190:15)
    at Object.oncomplete (/usr/local/lib/node_modules/yeoman/node_modules/connect/lib/middleware/static.js:157:11)
OK
>> File "app/images/i-s0ee4d00b40.png" changed.
```

I have tried several combinations of `images_path`, `http_images_path` and `http_generated_images_path` as outline here: http://compass-style.org/help/tutorials/configuration-reference/

So far all I've managed to do is grow older and more annoyed.

I'm hoping this is a bug and not me being n00b... 

Thanks!

**Comment by ChukoSosa** [comment]
You need to enter in the "config.rb" and you need to delete the "#" to able the "relative_assets = true", and work fine.

NOTE. don´t change the HTTP_PATH.. only need to able the relative assets

Example:
# To enable relative paths to assets via compass helper functions. Uncomment:
relative_assets = true
