### ISSUE TITLE
Yeoman init creates files in my home directory not the current directory

### ISSUE THREAD

**Issue by adamzr** [yeoman/yeoman#635]
I ran these commands:
    cd ~/myproject
    yeoman init bbb

The app and test directories were placed in my home directory `~` and not in the current directory `myproject`.

**Comment by SamJacobs** [comment]
.yo-rc also solved it for me!
Strange though, I attempted to delete all files by date created and this one showed up as created way earlier than I've been futzing with this. So, thought it belonged to something else. Anyone know why that might be?

**Comment by Torone** [comment]
Sometimes if you accidentally start a yeoman app in a wrong directory and you stop it typing "ctrl + c" or closing the terminal it will generate few hidden files.
So, what you need to do is to show hidden files and delete the various unnecessary files to solve the problem.

**Comment by Munter** [comment]
I wonder if it would be feasible to log the time the `yo`-command was started, then try to keep track of the transaction and undo the damage if we catch a `SIGINT` or similar kill signal. We should know the files that will be generated. If not, we could probably just glob by files after the `yo` launch time

**Comment by magicfaker** [comment]
pursuerdeMacBook-Pro:grunt-by-yo-wfg pursuer$ yo webapp grunt-by-yo-wfg

Just found a `.yo-rc.json` in a parent directory.
Setting the project root at: /Users/pursuer


     _-----_
    |       |    .--------------------------.
    |--(o)--|    |    Welcome to Yeoman,    |
   `---------´   |   ladies and gentlemen!  |
    ( _´U`_ )    '--------------------------'
    /___A___\    
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

Out of the box I include HTML5 Boilerplate, jQuery, and a Gruntfile.js to build your app.
? What more would you like? Bootstrap, Sass, Modernizr
? Would you like to use libsass? Read up more at 
https://github.com/andrew/node-sass#node-sass: No
 conflict Gruntfile.js
? Overwrite Gruntfile.js? overwrite
    force Gruntfile.js
 conflict package.json
? Overwrite package.json? overwrite
    force package.json
 conflict .gitignore
? Overwrite .gitignore? overwrite
    force .gitignore
identical .gitattributes
identical .bowerrc
 conflict bower.json
? Overwrite bower.json? overwrite
    force bower.json
identical .jshintrc
identical .editorconfig
identical app/styles/main.scss
identical app/favicon.ico
identical app/robots.txt
 conflict app/index.html
? Overwrite app/index.html? overwrite
    force app/index.html
identical app/scripts/main.js
   invoke   mocha


I'm all done. Running bower install & npm install for you to install the required dependencies. If this fails, try running the command yourself.


identical     test/bower.json
identical     test/.bowerrc
identical     test/spec/test.js
identical     test/index.html
npm WARN package.json grunt-by-yo-wfg@ No description
npm WARN package.json grunt-by-yo-wfg@ No repository field.
npm WARN package.json grunt-by-yo-wfg@ No README data
npm WARN package.json grunt-by-yo-wfg@ No license field.
pursuerdeMacBook-Pro:grunt-by-yo-wfg pursuer$

**Comment by magicfaker** [comment]
help me

**Comment by magicfaker** [comment]
I built a new project, but I could not find the file where it was generated.,

**Comment by SBoudrias** [comment]
@magicfaker Please read your log, everything is in what you posted us:

The relevant part is:

> Just found a .yo-rc.json in a parent directory.
> Setting the project root at: /Users/pursuer

**Comment by chalder** [comment]
@SBoudrias removing .yo-rc.json from home dir fixed the issue. Thanks a lot !!!

**Comment by harishkumarchellappa** [comment]
yes removing .yo-rc.json solved the issue...thank you very much guys

**Comment by Gardezi1** [comment]
maybe this solutio may help 

https://github.com/yeoman/yo/issues/204

**Comment by nagendertank** [comment]
Hi i also facing the same issue and i did everything which is mentioned in above steps(Removing .yo-rc.json and removing Gruntfile.js from parent directory) But still problem is not resolved. Please help me.

**Comment by SBoudrias** [comment]
@nagendertank Nothing else would cause this issue. You still have a `.yo-rc.json` file in a parent directory. You can google how to display hidden files.

**Comment by nagendertank** [comment]
@SBoudrias Hidden files are displaying and searched again for .yo.rc.json file and it is not showing anywhere in my system. still problem exists.

**Comment by SBoudrias** [comment]
@nagendertank You can use [findup](https://www.npmjs.com/package/findup). Then just type from your project folder: `findup .yo-rc.json`

It doesn't need to be in your home folder, it could be in any parent folder.

Also, yeoman warns you when it decides to run outside of the current directory. Read your log and you'll see where that file is.

**Comment by nagendertank** [comment]
@SBoudrias this is my log and Yo doctor is showing everything is fine but dont know why its creating all the files in home directory instead of project folder.

Nagendras-MacBook-Pro:DatePicker nagendratank$ yo doctor

Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version

Everything looks all right!
Nagendras-MacBook-Pro:DatePicker nagendratank$ findup .yo.rc.json
not found
Nagendras-MacBook-Pro:DatePicker nagendratank$

**Comment by SBoudrias** [comment]
It's `.yo-rc.json`, not `.yo.rc.json`

**Comment by nagendertank** [comment]
@SBoudrias Thanks a lot!!!! finally its working.

**Comment by magicfaker** [comment]
Why I run gulp build needs to be modified after the inside of the dist picture path removed. The. / can be displayed

**Comment by magicfaker** [comment]
为什么我运行gulp build之后需要修改dist里面的图片路径删除../才可以显示出来

**Comment by GuyHarwood** [comment]
+1 on removing .yo-rc.json 
worked for me

**Comment by ldexterldesign** [comment]
+1

Good few hours wasted diagnosing this

A more obvious mention on http://yeoman.io/ (i.e. http://yeoman.io/authoring/ > http://yeoman.io/authoring/user-interactions.html ) would be useful!

Thanks

**Comment by SBoudrias** [comment]
PR is welcomed if you feel the documentation is missing.

FWIW, yeoman will print a warning on your console when this is happening. Also, as always, `yo doctor` will detect this issue - and many other you could run into.

**Comment by gregoryderner** [comment]
+1 on removing .yo-rc.json 
worked for me

(Vagrant, Virtualbox, Ubuntu_Trusty-64)

Thanks
@SBoudrias

**Comment by mahanare** [comment]
Its even applicable now and removing the .yo-rc.json helped.

Thanks
Hari

**Comment by jbeckton** [comment]
why does .yo-rc.json have to be a hidden file?

**Comment by chaosyuan** [comment]
@sterlingw  thank you very much. removing the .yo-rc file

**Comment by jaspersorrio** [comment]
@SBoudrias good job on spotting the .yo-rc.json on parent folders!

Doing `rm .yo-rc.json` on folder that files are always created helped!!

So if `yo something` on yourPATHfolder/app/ created files at yourPATHfolder/,
`cd yourPATHfolder/` and `rm .yo-rc.json`

**Comment by andrewrenfroe** [comment]
in home or whereever the problem is
$ls-a
$rm .yo-rc.json 
$cd desired/path
&yo 

This worked for me

**Comment by bownie** [comment]
Would suggest the workflow for this 'feature' is changed. It just got me too. This is annoying and wrong.

**Comment by jadeye** [comment]
@koaning removing `.yo-rc.json` did it for me! Thanx

**Comment by bretonio** [comment]
Removing `Gruntfile.js` did not work for me. Removing both it and .yo-rc.json did! High drama. IOU beer.

**Comment by TangMonk** [comment]
same problem

**Comment by Gardezi1** [comment]
@TangMonk try this solution this might help : https://github.com/yeoman/yo/issues/204

**Comment by TangMonk** [comment]
@Gardezi1 thanks, I am using `yo doctor` to fixed

**Comment by Gardezi1** [comment]
@TangMonk  awesome

**Comment by prakashshaurya** [comment]
Search for .yo-rc.json by ctrl+h and delete it. change the directory to project directory and generate project , worked for me.

**Comment by khosiDigital** [comment]
.yo-rc was  in the parent directory....solved it!

**Comment by sadafnakhtare** [comment]
Copy the .yo-rc in the folder you want to create project. It solved my problem
