### ISSUE TITLE
Yeoman won't install at all

### ISSUE THREAD

**Issue by darokel** [yeoman/yeoman#691]
I can't seem to install yeoman at all, every time I run <code>npm install -g yeoman</code> (note: changed user permissions so I don't have to run sudo) I keep getting the following output:

<code>npm http GET https://registry.npmjs.org/yeoman
npm http 200 https://registry.npmjs.org/yeoman
npm http GET https://registry.npmjs.org/yeoman/-/yeoman-0.9.4.tgz
npm http 200 https://registry.npmjs.org/yeoman/-/yeoman-0.9.4.tgz
npm http GET http://nodeload.github.com/gruntjs/grunt/tarball/0ba6d4b529
npm http GET http://nodeload.github.com/yeoman/generators/tarball/3d709c61cd
npm http GET https://registry.npmjs.org/bower
npm http GET https://registry.npmjs.org/open/0.0.2
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/requirejs
npm http GET https://registry.npmjs.org/clean-css
npm http GET https://registry.npmjs.org/connect
npm http GET https://registry.npmjs.org/html-minifier
npm http GET https://registry.npmjs.org/which
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/fstream
npm http GET https://registry.npmjs.org/fstream-ignore/0.0.5
npm http GET https://registry.npmjs.org/cheerio
npm http GET https://registry.npmjs.org/tar
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/grunt-jasmine-task
npm http GET https://registry.npmjs.org/faye-websocket
npm http GET https://registry.npmjs.org/shelljs
npm http GET https://registry.npmjs.org/prompt
npm http GET https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/grunt-mocha
npm http GET https://registry.npmjs.org/es6-collections
npm http GET https://registry.npmjs.org/grunt-contrib-coffee
npm http 404 http://nodeload.github.com/gruntjs/grunt/tarball/0ba6d4b529
npm ERR! fetch failed http://nodeload.github.com/gruntjs/grunt/tarball/0ba6d4b529
npm http 404 http://nodeload.github.com/yeoman/generators/tarball/3d709c61cd
npm ERR! fetch failed http://nodeload.github.com/yeoman/generators/tarball/3d709c61cd
npm ERR! Error: 404 Not Found
npm ERR!     at null.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/fetch.js:47:16)
npm ERR!     at EventEmitter.emit (events.js:123:20)
npm ERR!     at WriteStream.flush (fs.js:1517:12)
npm ERR!     at fs.close (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:90:5)
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Darwin 11.4.2
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "yeoman"
npm ERR! cwd /Users/david/Sites/Node
npm ERR! node -v v0.8.12
npm ERR! npm -v 1.1.65
npm http 304 https://registry.npmjs.org/bower
npm http 304 https://registry.npmjs.org/open/0.0.2
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/requirejs
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/clean-css
npm http 304 https://registry.npmjs.org/connect
npm http 304 https://registry.npmjs.org/html-minifier
npm http 304 https://registry.npmjs.org/which
npm http 304 https://registry.npmjs.org/request
npm WARN package.json connect@2.2.2 No README.md file found!
npm http 304 https://registry.npmjs.org/fstream
npm http 304 https://registry.npmjs.org/fstream-ignore/0.0.5
npm http 304 https://registry.npmjs.org/cheerio
npm http 304 https://registry.npmjs.org/tar
npm http 304 https://registry.npmjs.org/coffee-script
npm http 304 https://registry.npmjs.org/grunt-jasmine-task
npm http 304 https://registry.npmjs.org/faye-websocket
npm http 304 https://registry.npmjs.org/shelljs
npm http 304 https://registry.npmjs.org/prompt
npm http 304 https://registry.npmjs.org/colors
npm http 304 https://registry.npmjs.org/grunt-mocha
npm http 304 https://registry.npmjs.org/es6-collections
npm http 304 https://registry.npmjs.org/grunt-contrib-coffee
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/david/Sites/Node/npm-debug.log
npm ERR! not ok code 0 </code>

I've followed the uninstallation instructions on this page https://github.com/yeoman/yeoman/wiki/Additional-FAQ but still get the same output.

**Comment by myxibrium** [comment]
I'm really confused here. Shouldn't we just use 
`npm install -g yo`
That's what's on http://yeoman.io/

**Comment by SBoudrias** [comment]
@myxibrium yes. You're looking at a thread from 2012.

**Comment by colt05** [comment]
running yo after running that code does absolutely nothing
