### ISSUE TITLE
yeoman watch issue

### ISSUE THREAD

**Issue by CeilingHoles** [yeoman/yeoman#717]
There seems to be an issue with the watch task. Let me know of any information you would need to help debug.
- I installed everything in the install script (all green checkmarks)
- I ran "yeoman init angular" in an empty directory -  all the files created successfully
- When I run "yeoman server", everything seems fine up until the watch task. The command line outputs over and over:
  
  ```
  Running "watch" task
  Waiting...<WARN> watch ENOSPC Use --force to continue. </WARN>
  ```
  
  And finally it ends by outputing:
  
  ```
  Running "watch" task
  Waiting...<FATAL> Cannot read property 'message' of undefined </FATAL>
  ```

**Comment by bchukiat** [comment]
Yeoman 1.4.7 on Ubuntu 14.04 work immediately  after running
   echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
thank so much.
