### ISSUE TITLE
Compass task very slow

### ISSUE THREAD

**Issue by ventrebleu** [yeoman/yeoman#793]
Hi,

I noticed that in my project, the yeoman task compiling compass files (yeoman server) is very slow - around 10 seconds - but if I use compass watch, it's much faster - just a second or two.

My first clue: I'm using the sprite magic with @import "nav/*_/_.png"; 

It might be that but I don't know what to do with it now... except maybe compile my sass files separately.

Anyway, I thought it was worth mentioning and if someone has a solution, I'll take it!

Thanks

**Comment by craig-o-curtis** [comment]
Mine takes between 30 and 45 seconds.
