### ISSUE TITLE
Suggestion : Custom HTML5 project templates with Initializr

### ISSUE THREAD

**Issue by lauterry** [yeoman/yeoman#802]
Hi,

Yeoman use HTML5 Boilerplate and it's a good thing.

However, one might not want every features included in HTML5 Boilerplate and want to have a custom 
HTML5 project.

Please consider using [Initializr](http://www.initializr.com/), a HTML5 template generator based on HTML5 boilerplate that enable you to fine tuned your configuration and select only the features you really need.

Yeoman ask questions to have the best project configuration. Initializr have the same philosophy.

I'm sure they can work together to make yeoman much more configurable.

Thank a lot for your job, btw !

Best regards

Thierry LAU

**Comment by ErikEvenson** [comment]
If anyone has done this, or does this in the future, it would be great to hear about it.
