### ISSUE TITLE
"usemin:css" doesn't generate correct image paths for relative urls

### ISSUE THREAD

**Issue by taktran** [yeoman/yeoman#824]
I've generated a project using yeoman, and I have the following scss file which references an image using relative paths:

```
.compare {
  background-image: url("../img/insulin-v2.jpg");
}
```

However, it does not get properly converted to the correct `../img/[random-hash].insulin-v2.jpg` format. 

If I change it to an absolute path, it does convert it correctly, ie,

```
.compare {
  background-image: url("/img/insulin-v2.jpg");
}
```

...generates this in the `yeoman build` output

```
Running "usemin:css" (usemin) task

usemin:css - styles/4dcce6a3.styles.css
>> img/insulin-v2.jpg
was url("/img/insulin-v2.jpg")
now url("/img/46ee3ef4.insulin-v2.jpg")
```

(the previous relative url version doesn't produce any output after `Running "usemin:css" (usemin) task`)

I can't use absolute paths because I need to host somewhere where it is not the root directory. Any ideas?

---

My folder structure is

```
./app:
    index.html
./app/img
    insulin-v2.jpg
./app/sass:
    _grid.scss
    _normalize.scss 
    styles.scss
```

`Gruntfile.js` build settings are

```
// Build configuration
// -------------------

// the staging directory used during the process
staging: 'temp',
// final build output
output: 'dist',

mkdirs: {
  staging: 'app/'
},

// Below, all paths are relative to the staging directory, which is a copy
// of the app/ directory. Any .gitignore, .ignore and .buildignore file
// that might appear in the app/ tree are used to ignore these values
// during the copy process.

// concat style/**/*.css files, inline @import, output a single minified css
css: {
  'styles/styles.css': ['styles/**/*.css']
},

// renames JS/CSS to prepend a hash of their contents for easier
// versioning
rev: {
  js: 'scripts/**/*.js',
  css: 'styles/**/*.css',
  img: 'img/**'
},

// usemin handler should point to the file containing
// the usemin blocks to be parsed
'usemin-handler': {
  html: 'index.html'
},

// update references in HTML/CSS to revved files
usemin: {
  html: ['**/*.html'],
  css: ['**/*.css']
},

// HTML minification
html: {
  files: ['**/*.html']
},

// Optimizes JPGs and PNGs (with jpegtran & optipng)
img: {
  dist: '<config:rev.img>'
},

// rjs configuration. You don't necessarily need to specify the typical
// `path` configuration, the rjs task will parse these values from your
// main module, using http://requirejs.org/docs/optimization.html#mainConfigFile
//
// name / out / mainConfig file should be used. You can let it blank if
// you're using usemin-handler to parse rjs config from markup (default
// setup)
rjs: {
  // no minification, is done by the min task
  optimize: 'none',
  baseUrl: './scripts',
  wrap: true,
  name: 'main'
}
```

---

This could be related to #419, but I tried the `.compass.rb` file addition and the `relative_assets: true`, but they both didn't work.

**Comment by Ouadie** [comment]
**V 1.3.3** and still have the `background:url('.tmp/images/bg.png')` instead of `background:url('../images/bg.png')` using the default **gruntfile.js** for **angular-generator**

**Comment by bmatto** [comment]
I'm having this issue as well @Ouadie - did you find any work around?

**Comment by Ouadie** [comment]
For now I used `$img-path:'../../../images;'` instead of `$img-path:'../images';` and it works for `grunt serve` and `grunt build`

**Comment by bmatto** [comment]
Thank you kind sir.

**Comment by viz** [comment]
just encountered this problem in a project created very recently using yeoman 1.4.8
I thought that I should post how I resolved it here for the benefit of others. I went to try @marcalj 's solution above, but the default config generated by yeoman looked like it was already doing that.

There was a subtle difference though. The default looked like:

    usemin: {
      html: ['<%= yeoman.dist %>/client/!(bower_components){,*/}*.html'],
      css: ['<%= yeoman.dist %>/client/!(bower_components){,*/}*.css'],
      js: ['<%= yeoman.dist %>/client/!(bower_components){,*/}*.js'],
      options: {
        assetsDirs: [
          '<%= yeoman.dist %>/client',
          '<%= yeoman.dist %>/client/assets/images'
        ],

which didn't work (the asset reference in the stylesheet wasn't updated by usemin.

To get it working, I added the `assets drectory into the assetDir array:

    usemin: {
      html: ['<%= yeoman.dist %>/client/!(bower_components){,*/}*.html'],
      css: ['<%= yeoman.dist %>/client/!(bower_components){,*/}*.css'],
      js: ['<%= yeoman.dist %>/client/!(bower_components){,*/}*.js'],
      options: {
        assetsDirs: [
          '<%= yeoman.dist %>/client',
          '<%= yeoman.dist %>/client/assets',
          '<%= yeoman.dist %>/client/assets/images'
        ],

 which resolved the issue.

**Comment by Wirwing** [comment]
Thanks @viz. adding assets directory did the trick!

**Comment by gugol2** [comment]
None of the solutions here worked for me.
I am using generator-angular 0.15.1
