### ISSUE TITLE
deploy dist folder to heroku

### ISSUE THREAD

**Issue by cioddi** [yeoman/yeoman#903]
I have started a very basic yeoman project using the command 

$ yeoman init angular:all

after running 

$ yeoman server 

everything is running just fine. Creating the build in dist directory using

$ yeoman build

$ yeoman server:dist // also works great locally

now I like to deploy this to heroku so I am running the following commands in terminal
$ git init
$ git add .
$ git commit -m 'initial'
$ heroku create

everything works great until this step but when I try to push it to heroku using
$ git subtree push --prefix dist heroku master

I get the following error:
!     Heroku push rejected, no Cedar-supported app detected

that is because there is no package.json file inside the dist folder
so I tried 
$ cp package.json dist/package.json
$ git add .
$ git commit -m 'package.json'
$ git subtree push --prefix dist heroku master

that way the deployment process finishes without an error
but after calling the app url in my browser  "Application Error"
http://aqueous-shore-3066.herokuapp.com/

I have uploaded the project to my github repository
https://github.com/cioddi/vinetv

thx in advance to anyone who can and will help me with this

forgot to mention I am running Mac OS 10.6.8 and yeoman 0.9.6

**Comment by kalinchernev** [comment]
This page is popular googling "how deploy yo webapp on heroku".

With few changes, the solution at https://github.com/yeoman/yeoman/issues/903#issuecomment-13252674 is still today very helpful.

1) Good to save express as dependency
```javascript
$ npm install --save express
```

2) body-parser should be installed, not in core any more
```javascript
$ npm install --save body-parser
```
and app.js correspondingly:

```javascript
var express = require('express');
var bodyParser = require('body-parser')
var path = require('path');

app = express();

// parse application/x-www-form-urlencoded
app.use(bodyParser.urlencoded({ extended: true }));
app.use(express.static(__dirname + '/dist'));

var port = process.env.PORT || 5000;

app.listen(port);

console.log('server started ' + port);
```

3) bower dependencies via scripts
```javascript
  "scripts": {
    "start": "node app.js",
    "test": "grunt test",
    "postinstall": "./node_modules/bower/bin/bower install"
  },
```

**Comment by carlosdarienvizcaino** [comment]
@cioddi how are you using your dist/ folder when deploying? I noticed you added it to your git by doing *git add app.js package.json node_modules/ dist/*. But when you do "git push heroku master" Heroku calls *npm start* after is done installing all the dependencies. Are you saying *node dist/server/* in your npm start. 

Thanks in advance.

**Comment by kalinchernev** [comment]
@carlosdarienvizcaino this was so long time ago that I'm sure both the package I've been talking about and the heroku service have changed. So, best is to follow the heroku docs to ensure you follow the best source of truth now. :)
