### ISSUE TITLE
Have you considered Yeoman and SailsJS integration for complete Front-End & Back-End scaffolding generation?

### ISSUE THREAD

**Issue by Gnex77** [yeoman/yeoman#994]

**Comment by guysopher** [comment]
Can I bump this thread?
It's been a while and I don't think there is a proper solution for that. Has anyone found a way to make yeoman work with sails?

**Comment by SBoudrias** [comment]
Search for _sails_ here http://yeoman.io/generators/ - there's a lot of options.
